ipfs/js-ipfs

- README.md
This is in direct response to https://github.com/ipfs/node-ipfs/issues/15 and https://github.com/ipfs/node-ipfs/issues/14.
> Added a Contribute section, with small rewrites

- package.json
- src/http-api/index.js
- src/http-api/resources/id.js
- src/http-api/resources/index.js
- src/http-api/routes/id.js
- src/http-api/routes/index.js
- src/ipfs-core/index.js
- tests/test-api/index.js
- tests/test-api/test-id.js
- tests/test-api/test-version.js
- tests/test-cli-offline/index.js
- tests/test-cli-offline/test-id.js
- tests/test-cli-offline/test-version.js
- tests/test-cli/index.js
- tests/test-cli/test-id.js
- tests/test-cli/test-version.js
- tests/test-core/index.js
- tests/test-core/test-id.js
- tests/test-core/test-version.js
Also added ability to stop the server
> ID impl + tests (core+api+cli)

- .travis.yml
- karma.conf.js
- package.json
- src/ipfs-core/config.js
- src/ipfs-core/default-repo/browser.js
- src/ipfs-core/default-repo/index.js
- src/ipfs-core/default-repo/node.js
- src/ipfs-core/index.js
- tests/test-core/browser.js
- tests/test-core/index.js
- tests/test-core/test-config.js
- tests/test-core/test-id.js
- tests/test-core/test-version.js
This is mostly the same as https://github.com/ipfs/js-ipfs-repo/pull/26.
Changed IPFS core to allow it to be instantiated with a custom `ipfs-repo`, but if none is provided it will use the default with `fs-blob-store` for `node`, or with `local-storage-blob-store` for the browser.
Also had to replace `let`'s by `const`'s on the tests [because of Firefox](https://travis-ci.org/ipfs/js-ipfs/jobs/104435637#L867).
> Run core tests in the browser

- package.json
- tests/test-core/browser.js
- tests/test-core/test-block.js
I implemented a simple [`buffer-loader`](https://github.com/xicombd/buffer-loader) based on the `binary-loader` which fixes the two missing tests.
However I got a weird bug with webpack as it doesn't seem to define `Buffer` if it is not used outside the tests, so  [I added an hack on top of the file](https://github.com/ipfs/js-ipfs/compare/update/ipfs-repo...xicombd:use-buffer-loader?expand=1#diff-9c147124754a0b48ca1d40235e76a0b6R14). 
@dignifiedquire do you have any idea how to avoid this?
> Use buffer-loader for tests

- src/http-api/resources/config.js
- src/http-api/routes/config.js
- tests/test-http-api/test-config.js
Implements the `/api/v0/config/show` as specified at https://github.com/ipfs/http-api-spec/pull/29
Related to #49 & very similar to #72
> Add /api/v0/config/show endpoint

- src/cli/commands/commands.js
- tests/test-cli/test-commands.js
> Add ipfs commands to cli

- package.json
- src/http-api/resources/config.js
- src/http-api/routes/config.js
- tests/badconfig
- tests/otherconfig
- tests/test-http-api/test-config.js
Implements the `/api/v0/config/replace` as specified at https://github.com/ipfs/http-api-spec/pull/29
Uses [`ipfs-multipart` ](https://github.com/xicombd/ipfs-multipart) to process the payload that `js-ipfs-api` sends.
Related to #49 & similar to #72 & #74 :rocket:
> Add /api/v0/config/replace endpoint

- src/cli/commands/id.js
- src/cli/utils.js
- tests/test-cli/test-bootstrap.js
Add `getIPFS` method to cli utils that returns a `js-ipfs-api` instance if a daemon is running or a new core instance if not. 
Simplifies the cli commands as the two APIs are mostly equal :)
> Add getIPFS util and refactor id command to use it

- src/cli/commands/version.js
- src/http-api/index.js
- src/http-api/resources/version.js
- src/http-api/routes/block.js
- src/http-api/routes/bootstrap.js
- src/http-api/routes/config.js
- src/http-api/routes/id.js
- src/http-api/routes/index.js
- src/http-api/routes/object.js
- src/http-api/routes/repo.js
- src/http-api/routes/version.js
- tests/test-cli/test-version.js
- tests/test-http-api/test-version.js
Use dependency injection on routes so that we can start and stop the http-api multiple times without issues on the tests. 
~~Updated `jsipfs version` to work with the api running and added a test to make sure it works :)~~ Got similar bug to #70
> Refactor HTTP API routes

- package.json
- src/cli/commands/object/data.js
- src/cli/commands/object/get.js
- src/cli/commands/object/links.js
- src/cli/commands/object/new.js
- src/cli/commands/object/put.js
- src/cli/commands/object/stat.js
- src/http-api/resources/object.js
- src/http-api/routes/index.js
- src/http-api/routes/object.js
- tests/badnode.json
- tests/node.json
- tests/test-cli/test-commands.js
- tests/test-cli/test-object.js
- tests/test-http-api/test-object.js
Implemented most of #58, except for the `object patch` commands as the http API changed for 0.4.0 and the spec isn't not finished yet (https://github.com/ipfs/http-api-spec/pull/32#issuecomment-189491059)
> Add object endpoints and cli commands

- package.json
- src/cli/commands/object/patch/add-link.js
- src/cli/commands/object/patch/append-data.js
- src/cli/commands/object/patch/rm-link.js
- src/cli/commands/object/patch/set-data.js
- src/core/index.js
- src/http-api/resources/object.js
- src/http-api/routes/object.js
- tests/test-cli/test-commands.js
- tests/test-cli/test-object.js
- tests/test-core/test-object.js
- tests/test-http-api/test-object.js
> Add object patch endpoints and cli commands

- src/cli/commands/init.js
- src/cli/utils.js
- tests/test-cli/test-init.js
No HTTP route/tests, since initialization is pre-req of having an HTTP API available.
> 'ipfs init': CLI + tests

- src/core/index.js
- src/core/init.js
- test/core-tests/test-init.js
Motivated by https://github.com/ipfs/go-ipfs/pull/2479. It's not clear that
this is a necessary / standardizable feature, so let's omit it until we're sure
we need it. After all, odds are [YouArentGonnaNeedIt](http://c2.com/cgi/wiki?YouArentGonnaNeedIt).
> removes --force

- .gitignore
- src/cli/commands/block/get.js
- src/cli/commands/block/put.js
- src/cli/commands/block/rm.js
- src/cli/commands/block/stat.js
- src/http-api/resources/block.js
- src/http-api/routes/block.js
- src/http-api/routes/index.js
- test/cli-tests/test-block.js
- test/cli-tests/test-commands.js
- test/http-api-tests/test-block.js
- test/test-data/hello
So, I stubbed out a couple of files, but I'm not sure this is what I am actually supposed to be doing here. It is hard without more examples, and I don't know how to run, or what sort of development environment I should be using to test the code as I go along.
> jsipfs block http-api and cli

- karma.conf.js
- package.json
Fixes #131 & #130 
The `postLoader` can be removed when we switch to `dignified.js`. 
Thanks @dignifiedquire for the help :)
> Fix peer-id errors on browser tests

- test/node.js
To make it easier to select which tests to run (running the whole thing takes time 🕰
> select tests by process env

- test/core-tests/repo-path.js
the one time I don’t wait for CI, a 1 line change PR, something was indeed broken (the browser couldn’t take the crazy path for indexedDB). Fixed now.
https://github.com/ipfs/js-ipfs/pull/273
I guess this teaches me a lesson, that I kind of knew xD :D
> fix repo path for tests in browser

- src/cli/commands/files/add.js
- test/cli/test-files.js
- fixes 'files add' CLI to work with `createAddStream` changes
- adds tests
> fix `ipfs files add` CLI command.

- README.md
- ROADMAP.md
This PR updates the project roadmap.
//cc @em-ly
> Update project roadmap

- src/core/ipfs/files.js
This is needed for interface-ipfs-core consistency.
Depends on https://github.com/ipfs/js-ipfs-unixfs-engine/pull/52
> Promisify ipfs.files.get

- README.md
- package.json
Confirms that ipfs.files.get exists in core
Also, for interface updates, see: https://github.com/ipfs/interface-ipfs-core/issues/55
> feat(interface): update interface-ipfs-core to v0.6.0

- package.json
- test/cli/test-version.js
- test/core/both/test-files.js
- test/core/both/test-object.js
- test/core/both/test-version.js
- test/http-api/test-version.js
- test/utils/factory/default-config.json
- test/utils/factory/index.js
> feat(factory): add ipfs factory, verify it works with object tests

- src/http-api/resources/object.js
I found that this was causing incorrect returns when writing the ```add``` http resource. JS-IPFS-API makes http requests to the js-ipfs ```object``` core now with the addition of the new ```add``` support for core <a href="https://github.com/ipfs/js-ipfs-api/blob/master/src/get-dagnode.js#L19">here</a>.
If the data is a string then the buffer is sent correctly, however if the data field is something else it seems to be wrapping the buffer with some extra maybe new line characters. 
@diasdavid @dignifiedquire 
Is there a specific reason for the data to be return as a string in the ```object/data``` http resource?
<a href="https://github.com/ipfs/js-ipfs/pull/323">PR 323</a> Is blocked by this issue.
> remove toString

- README.md
> update the `script` tag in an example provided by `README.md`

- src/cli/commands/files/cat.js
- test/cli/test-files.js
Add tests for making sure .cat shows right output and fix that test by
using the right argument from cli. Ref: issue #476
> fix(cli): use right argument for cli .cat

- src/cli/commands/init.js
- src/cli/utils.js
- src/core/ipfs/init.js
Shows exactly same information as go-ipfs except for change of the cmd +
cat so `ipfs cat` turns into `jsipfs files cat` instead. Ref: issue #286
> fix(cli): add output for cli init

- ROADMAP.md
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
//cc @flyingzumwalt @em-ly
> roadmap update

- src/core/ipfs/id.js
- src/core/ipfs/libp2p.js
- test/cli/test-swarm.js
- test/core/both/test-bitswap.js
- test/core/node-only/test-swarm-2.js
- test/core/node-only/test-swarm.js
- test/http-api/inject/test-swarm.js
- test/http-api/ipfs-api/test-swarm.js
This contributes to https://github.com/ipfs/js-ipfs/issues/439
Only missing:
> feat(swarm): interface-ipfs-core swarm compatibility

- package.json
- src/cli/commands/files/add.js
- src/cli/commands/files/cat.js
- test/cli/test-files.js
Found while testing the cli :)
> fix(cli): pipe content to the cli from cat it is a stream

- src/cli/commands/files/add.js
- src/core/ipfs/files.js
- test/cli/test-files.js
Fixes https://github.com/ipfs/js-ipfs/issues/480
> fix(cli): start fixing files add

- package.json
- src/cli/commands/swarm/addrs.js
- src/cli/commands/swarm/addrs/local.js
- src/cli/commands/swarm/peers.js
- src/core/components/swarm.js
- src/http-api/resources/swarm.js
- src/http-api/routes/swarm.js
- test/cli/test-swarm.js
- test/http-api/interface-ipfs-core-over-ipfs-api/test-swarm.js
Currently fails on `ipfs swarm addrs` tests. `ipfs-api` currently expects to get a map, of addresses indexed by peers. It then flattens it, so that the current results for `ipfs swarm peers` and `ipfs swarm addrs` are identical, which makes little sense to me.
I suggest keeping `peers` as is, but changing `ipfs swarm addrs` to return a map as go ipfs does:
```
> ipfs swarm addrs
QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64 (5)
/ip4/104.236.76.40/tcp/4001
/ip4/127.0.0.1/tcp/4001
/ip4/172.17.0.1/tcp/4001
/ip6/::1/tcp/4001
/ip6/fcd8:a4e5:3af7:557e:72e5:f9d1:a599:e329/tcp/4001
QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx (5)
/ip4/104.236.151.122/tcp/4001
/ip4/127.0.0.1/tcp/4001
/ip4/172.17.0.1/tcp/4001
/ip6/::1/tcp/4001
/ip6/fc3d:9a4e:3c96:2fd2:1afa:18fe:8dd2:b602/tcp/4001
```
mapping …
> feat(http): make swarm interface-ipfs-core compliant

- src/cli/commands/config.js
- src/cli/commands/version.js
- src/http-api/resources/config.js
- src/http-api/resources/version.js
- src/http-api/routes/config.js
- test/cli/test-config.js
- test/cli/test-id.js
- test/cli/test-version.js
- test/http-api/inject/test-version.js
- test/http-api/ipfs-api/test-config.js
I found some tests that were skipped and resulted in actual broken code. This is fixed now and things are more http-api and interface-ipfs-core compliant than before :)
> Less skipped tests

- src/cli/bin.js
- test/cli/test-commands.js
Be explicit about where to grab package information from, fixes https://github.com/ipfs/js-ipfs/issues/497
> fix(cli): Fix issue with right cwd not being set

- src/cli/bin.js
- test/cli/test-files.js
Aliases add, cat and get to be in the top-level namespace of the cli.
Reference: https://github.com/ipfs/js-ipfs/issues/455#issuecomment-245939074
Left to do:
> fix(cli): alias add, cat and get to top-level cli

- src/core/components/libp2p.js
This PR will make sure errors are caught coming from libp2p.start()
> Handled errors that bubble up from libp2p.start()

- package.json
- src/core/components/swarm.js
- src/http-api/resources/swarm.js
Ref https://github.com/ipfs/js-ipfs-api/pull/427
> feat(swarm): update swarm.peers to new api

- src/cli/commands/daemon.js
- src/http-api/index.js
- test/cli/test-daemon.js
From https://github.com/ipfs/js-ipfs/pull/631
Had to create PR with branch from ipfs/js-ipfs instead of my fork, since running Sauce Labs would fail otherwise. See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
> fix(cli): Tell user to init repo if not initialized when starting daemon

- src/cli/commands/swarm/disconnect.js
- test/cli/test-swarm.js
> Add swarm disconnect cli

- package.json
- src/cli/commands/bootstrap/add.js
- src/cli/commands/bootstrap/list.js
- src/cli/commands/bootstrap/rm.js
- src/core/components/bootstrap.js
- src/http-api/resources/bootstrap.js
- src/http-api/routes/bootstrap.js
- test/cli/test-bootstrap.js
- test/core/both/test-bootstrap.js
- test/http-api/custom-ipfs-api/test-bootstrap.js
- test/http-api/inject/test-bootstrap.js
Fixes #668 
Available in the cli, http-api and core:
- `bootstrap add <peer>`
- `bootstrap add --default`
- `bootstrap rm <peer>`
- `bootstrap rm --all`
- `bootstrap list`
Same output and as go-ipfs  and js-ipfs-api.
> Implement more bootstrap commands

- test/sharness/t0015-basic-sh-functions.sh
All the tests in t0015-basic-sh-functions.sh pass as this test is testing our own shell functions.
> sharness: add t0015-basic-sh-functions.sh

- test/sharness/t0022-init-default.sh
This adds 6 go-ipfs tests that pass.
> sharness: add t0022-init-default.sh

- examples/transfer-files/README.md
Started rewriting it. 
@diasdavid I'm having issues with npm start - it doesn't work at `8080`, but at `http://127.0.0.1:12345`, and I'm not sure I am running the right thing. Is that the right thing? Should I be in `/js-ipfs/examples/transfer-files/complete`?
> First pass looking at interop example tutorial

- README.md
- src/cli/commands/swarm/peers.js
- src/core/components/libp2p.js
needs: 
- https://github.com/ipfs/js-libp2p-ipfs-nodejs/pull/64
- https://github.com/ipfs/js-libp2p-ipfs-browser/pull/145
> feat: bootstrap as an option

- package.json
- test/cli/test-files.js
because github closed https://github.com/ipfs/js-ipfs/pull/742
> test: another add recursive test

- src/http-api/resources/block.js
value may be a binary buffer, it should be returned as is instead of coerced into unicode
note: if request is sent from the browser, the requestor can set the `responseType` to get the result as an ArrayBuffer in order to accurately get the binary data
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data
> http-api - block - get - return value raw

- examples/basics/index.js
- test/cli/init.js
- test/utils/ipfs-exec.js
- test/utils/ipfs-factory-daemon/index.js
- test/utils/on-and-off.js
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
os.tmpdir was added in Node v0.9.9 and os.tmpDir deprecated in Node v7.0.0. More info:
nodejs/node#6739
https://nodejs.org/en/blog/release/v7.0.0/
https://nodejs.org/api/os.html#os_os_tmpdir
> os.tmpDir has been depricated in favor of os.tmpdir

- test/sharness/t0010-basic-commands.sh
This add some failing tests.
The first failure is:
```
expecting success: 
ipfs version --all > version_all.txt &&
grep "go-ipfs version" version_all.txt &&
grep "Repo version" version_all.txt &&
grep "System version" version_all.txt &&
grep "Golang version" version_all.txt
not ok 5 - ipfs version --all has all required fields
```
This is because `jsipfs version --all` returns "js-ipfs version: 0.17.0" while:
```
$ ipfs version --all
go-ipfs version: 0.4.4-dev-8830aae
Repo version: 4
System version: amd64/linux
Golang version: go1.5.3
```
I understand that jsipfs cannot give a go-ipfs version or a golang version, but it could give equivalent information about the js-ipfs version and the js engine.
In go-ipfs reports we ask users to copy paste the output of `ipfs version --all` when …
> sharness: t0010- jsipfs version

- README.md
With node 4.4 one gets errors like:
$ jsipfs --help
/usr/local/lib/node_modules/ipfs/node_modules/ethereumjs-util/index.js:31
exports.SHA3_NULL = Buffer.from(exports.SHA3_NULL_S, 'hex')
^
TypeError: hex is not a function
at Function.from (native)
at Function.from (native)
at Object.<anonymous> (/usr/local/lib/node_modules/ipfs/node_modules/ethereumjs-util/index.js:31:28)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/usr/local/lib/node_modules/ipfs/node_modules/ethereumjs-block/header.js:1:77)
So it really looks like node >= 4.5 is needed.
> README: node >= 4.5 is needed

- src/core/index.js
Allow IPFS object to be created without supplying configOpts to prevent the following code, from the readme, from failing:
```Javascript
const IPFS = require('ipfs')
const node = new IPFS()
```
> Allow IPFS object to be created without supplying configOpts

- package.json
- src/core/components/go-online.js
- src/core/components/libp2p.js
- src/core/components/swarm.js
- test/interop/daemons/go.js
- test/interop/daemons/js.js
- test/interop/index.js
- test/interop/util.js
- test/node.js
- go-ipfs: https://github.com/ipfs/go-ipfs/pull/3695 ✅ 
- ~~go-multiplex: https://github.com/whyrusleeping/go-multiplex/pull/4~~
- multiplex: https://github.com/dignifiedquire/multiplex ✅ 
- bitswap: https://github.com/ipfs/js-ipfs-bitswap/pull/113 ✅ 
- libp2p-multiplex: https://github.com/libp2p/js-libp2p-multiplex/pull/59 ✅ 
```
LIBP2P_MUX_PREFS="/mplex/6.7.0" IPFS_EXEC=`which ipfs` LIBP2P_MUXER=multiplex npm run test:interop:node
```
Will fix https://github.com/ipfs/in-web-browsers/issues/19 once completed
> Multiplex with go

- src/core/components/files.js
There was a new test added for js-ipfs-api that needed a fix here too.
> fix(files.add): error on invalid input

- README.md
- examples/basics/index.js
- examples/browser-script-tag/index.html
- examples/bundle-browserify/src/index.js
- examples/bundle-webpack/src/components/app.js
- examples/dag/create-node.js
- gulpfile.js
- src/cli/commands/init.js
- src/cli/utils.js
- src/core/components/index.js
- src/core/components/is-online.js
- src/core/components/pre-start.js
- src/core/components/start.js
- src/core/components/stop.js
- src/core/default-repo.js
- src/core/index.js
- src/http-api/index.js
- test/core/bitswap.spec.js
- test/core/bootstrap.spec.js
- test/core/create-node.spec.js
- test/core/init.spec.js
- test/utils/ipfs-factory-daemon/index.js
- test/utils/ipfs-factory-instance/index.js
For https://github.com/ipfs/docs/issues/22
> All new way of initing a node.

- src/core/components/id.js
- src/core/components/pre-start.js
One of those simple things that will make everyone's life so much easier
> feat: no need anymore to append ipfs/Qmhash to webrtc-star multiaddrs

- src/cli/commands/files/add.js
- test/cli/files.js
> Wrap with directory option

- src/core/components/init-assets.js
- src/core/components/init.js
- src/init-files/init-docs/security-notes
- test/core/init.spec.js
Not sure which other steps are involved here when updating init-docs.
> Add security@ipfs.io GPG key

- package.json
- src/cli/commands/init.js
- test/sharness/t0020-init.sh
@chriscool I'm trying to get sharding tests to work, something changed with our update to `init`, but from what I can read, it should be golden. Could you shed some light?
> sharding tests

- src/core/boot.js
- test/core/create-node.spec.js
This PR will make it so if you start a node twice with the same path, it won't crash when trying to initialize a new repo. Synonym with doing `ipfs daemon --init` with go-ipfs in terminal.
> Loosen up init requirements: accept already initialised repos

- src/core/components/files.js
`ipfs.createAddStream` stream provided no back-pressure mechanism after [this fix](4b064a166428dfd94a8d3ef1ede6f5c48948e797).
This change now makes this stream wait for a flush before invoking the`.write()` callback.
> fix: added backpressure to the add stream

- src/cli/bin.js
Starting jsipfs without any commands crashes it and gives a slightly unclear error message from yargs.
I changed this to have yargs display the original help message on starting jsipfs with no commands.
Also there is a fix for the --help command messages not being displayed at all.
> Fixed error message outputs/handling for help commands in CLI

- src/cli/commands/daemon.js
- src/cli/commands/files/add.js
- src/core/components/files.js
- src/core/index.js
- src/http-api/index.js
- test/core/files-sharding.spec.js
Added and propagated `--enable-sharding-experiments` on CLI and Daemon.
(By the way, also, `--enable-pubsub-experiment` on daemon.)
When daemon is on, enabling this flag on the CLI raises an error.
> enabling sharding experimental flag

- circle.yml
- package.json
I'm adding interop tests to circle, as I've found today that they broke with the latest unixfs-engine changes.
@pgte could you take a look? It seems that the objects that go-ipfs seems might be missing some fields that now js-ipfs expects.
> test: add interop to circle

- examples/transfer-files/public/js/app.js
- src/init-files/default-config-browser.json
- src/init-files/default-config-node.json
- test/http-api/spec/bootstrap.js
Added the bootstrappers [@lgierth created](https://github.com/ipfs/pm/issues/310#issuecomment-275968934) to the Bootstraper list. This is still not 100% working as it requires some updates throughout the dialing code (DNS addrs need to be valid wss/tcp).
Assignee: @dryajov
> 🌟 feat: add websocket bootstrapers to the config

- README.md
- src/core/components/init.js
- src/init-files/default-config-browser.json
- src/init-files/default-config-node.json
- test/core/bitswap.spec.js
- test/core/bootstrap.spec.js
- test/core/create-node.spec.js
- test/core/files-sharding.spec.js
I want to add this in, but cope with the scenarios where there is no webrtc-support. The current way does it, but also it makes it annoying to disable webrtc only, you'd have to swap all the multiaddrs at the same time to stop supporting webrtc. Will look into a better way.
> feat: webrtc by default if supported

- src/core/boot.js
- src/core/components/init.js
- src/init-files/default-config-browser.json
fixes https://github.com/ipfs/js-ipfs/issues/858
> fix: issue-858

- README.md
- examples/bundle-browserify/README.md
- examples/bundle-browserify/package.json
- examples/bundle-webpack/README.md
- examples/bundle-webpack/package.json
- examples/bundle-webpack/webpack.config.js
closes https://github.com/ipfs/js-ipfs/issues/758
> docs: browserify-zlib-next begone!

- src/core/components/bootstrap.js
- src/core/components/stop.js
- test/http-api/over-ipfs-api/bootstrap.js
> fix(bootstrap:add): prevent duplicate inserts

- src/core/components/swarm.js
we sre accidentally filtering for isConnected on `swarm.addr` instead of `swarm.peers`
discussion here https://github.com/libp2p/js-libp2p-swarm/issues/221
> swarm - move isConnected filter from addrs to peers

- src/cli/commands/daemon.js
- src/http-api/index.js
- Respect `--enable-experimental-pubsub`
- Don't overload repo config with cli args (fixes #868)
- Typo
---
I was unable to run tests, linting or anything. Did not work on node 8.1.2 or 6.11.1
> Fix js-ipfs daemon config params

- CONTRIBUTING.md
Spotted wrong project name, and link, in contributing guide, - fixed.
> docs: fix link to contribution guidelines, and project name

- src/cli/commands/init.js
- src/cli/commands/repo/version.js
Fixes small inconsistency in style:
Most of the commands in the CLI throws on error,
with a few exceptions that prints a message to stderr instead.
It looks at if it by random (and not intentional), 
and looked a bit odd when I was going through the code earlier,
so this pull request make them all handle errors the same way.
> refactor: consistent error handling in cli

- .travis.yml
- README.md
- package.json
ref: https://github.com/ipfs/js-ipfs/issues/781
> chore: remove official support for Node.js 4 (rm it from tests and docs)

- README.md
Noticed few typos in the README example when testing webrtc/node.
> Fix typos in webRTC code snippet

- examples/browser-video-streaming/README.md
- examples/browser-video-streaming/index.html
- examples/browser-video-streaming/streaming.js
This is work in progress, but creating this PR now so you can track it if you like.
The example now gets the hlsjs-ipfs-loader module from unpkg.com instead of the user having to build it.
The old audio example has been replaced with a Big Buck Bunny video (small, for now), which has been pinned in the gateways.
TODO:
> Add basic video streaming example

- src/cli/commands/files/add.js
- src/core/components/files.js
- src/http-api/resources/files.js
- src/http-api/routes/files.js
- test/cli/files.js
Allows `--cid-version=1` to be passed to get a V1 CID for response `Hash`es.
Caveat is that if `--cid-version=1` is passed then you must also pass `--raw-leaves=false` since raw leaves haven't yet been implemented and the default is to set `--raw-leaves=true` unless it is passed explicitly (behaviour from the go-ipfs implementation).
**requires https://github.com/ipfs/js-ipfs-api/pull/589**
> Add --cid-version option to ipfs files add

- package.json
- src/http/gateway/resources/gateway.js
- src/http/gateway/resources/index.js
Some clean up for gateway (tested on node v6 and v8.4.0).
Current Todo:
License: MIT
Signed-off-by: Yahya <ya7yaz@gmail.com>
> clean up , working builds on node v8.4.0

- examples/ipfs-101/1.js
- examples/ipfs-101/package.json
fixes https://github.com/ipfs/js-ipfs/issues/977
> docs: fix example ipfs-101

- examples/exchange-files-in-browser/package.json
- examples/exchange-files-in-browser/public/index.html
- examples/exchange-files-in-browser/public/js/app.js
Hey , this is a fix for issue #952 
This uses `createAddStream` instead of add to add a fairly large file in the browser without crashing.
> fix #952 : adding +50Mb files via createAddStream

- src/http/gateway/dir-view/index.js
- src/http/gateway/resolver.js
- src/http/gateway/resources/gateway.js
- test/gateway/index.js
These are the required changes requested by @dignifiedquire in #968 
**UDPATE**: I just noticed @VictorBjelkholm requested changes, I'll implement them and push them to this branch as well.
Changes:
Please Let me know if there are any other changes required. Thanks for your help 👍
> required changes for the gateway

- test/cli/swarm.js
fixes - https://github.com/ipfs/js-ipfs/issues/992
tests are coming.
> WIP: fix: prevent swarm peers from throwing after a peer disconnects

- .gitignore
This crept in from my last merged PR (https://github.com/ipfs/js-ipfs/pull/1032). I had commented out `node_modules` to make my IDE detect them. Apologies for the silly slip.
> Uncomment node_modules from .gitignore

- examples/browser-webpack/package.json
Added react-dom and babel-preset-stage-0 to dev dependencies
Fixes #1021
> fix(examples): Include required modules for browser-webpack example

- src/cli/commands/files/add.js
- src/core/components/files.js
- src/http/api/resources/files.js
> fix: progress bar flakiness

- examples/ipfs-101/README.md
Please check for other occurrences around the repo, might not be the only one.
> Fix 404 links to API docs

- src/core/components/bitswap.js
- src/core/components/pubsub.js
- src/core/components/swarm.js
- src/core/utils.js
... by throwing a new error instead of a cached one.
> make offline error retain stack

- examples/exchange-files-in-browser/README.md
you changed folder name without update the readme file
> update folder name in readme

- package.json
- src/core/components/libp2p.js
- test/core/circuit-relay.spec.js
- test/core/files-sharding.spec.js
- test/utils/create-repo-browser.js
- test/utils/create-repo-nodejs.js
- test/utils/ipfs-factory-instance/index.js
Solved some issues on the sharding tsts, but still seems something is weird with that codebase, see:
> Figure out why tests are failing

- src/cli/commands/daemon.js
- src/core/components/pre-start.js
- test/cli/daemon.js
This is needed to make js-ipfs consistent with how go-ipfs behaves - needed for https://github.com/ipfs/js-ipfsd-ctl/pull/170.
> feat: make js-ipfs cli and daemon behave like go-ipfs

- src/cli/commands/ls.js
- src/core/components/stop.js
- src/http/api/resources/files.js
- test/core/create-node.spec.js
This PR will promisify stop().
Closes #1076 
The effective changes are in stop.js and in create-node.spec.js. The changes to ls and files are purely to make linter happy.
> Fix: Promisify stop

- src/core/components/block.js
This PR will promisify the functions in .block
Depends on https://github.com/ipfs/interface-ipfs-core/pull/170
> fix: Promisify .block (get, put, rm, stat)

- src/cli/bin.js
- src/cli/utils.js
Mimicking go-ipfs, support the `--api=<multiaddr>` option to force being an HTTP client.
> CLI: --api option

- README.md
> FAQ: add custom signaling server description

- README.md
This change removes the `pubsub` settings for configuring a custom `signaling server`.
> FAQ: custom signaling server

- package.json
- test/cli/daemon.js
Tests are failing due to timeouts. These tests are awfully slow, we might want to consider skipping them on normal runs?
> fix SIG tests

- src/cli/commands/files/add.js
A fix for https://github.com/ipfs/js-ipfs-api/issues/637
> CLI recursive file add on windows

- package.json
- src/core/runtime/libp2p-browser.js
- src/core/runtime/libp2p-nodejs.js
Adding websocket-star transport
> feat: WebSocketStar

- README.md
The original link of files API was https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES. But it should be changed to https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md.
> docs: fix a link of files API in README.md

- examples/explore-ethereum-blockchain/README.md
The eth-stuffs folder is located in the explore-ethereum-blockchain folder, which is a same level of README.md, so the link of eth-stuffs folder should be changed to ./eth-stuffs.
> docs(examples): fix a link of eth-stuffs in README.md

- test/cli/daemon.js
- test/core/bitswap.spec.js
- test/core/create-node.spec.js
- test/interop/repo.js
- test/utils/interop-daemon-spawner/util.js
- test/utils/ipfs-factory-instance/index.js
See https://github.com/ipfs/js-ipfs/issues/1075
> test: use os.tmpdir()

- src/core/components/pubsub.js
- src/http/api/resources/pubsub.js
- test/http-api/spec/pubsub.js
> fix(pubsub.peers): remove the requirement for a topic

- src/http/api/resources/config.js
- test/cli/config.js
- test/utils/interop-daemon-spawner/util.js
When setting configs to null in daemon mode, the handler should check if value is defined/null since `typeof null === 'object'`
> fix: config handler should check if value is null

- src/core/components/pubsub.js
`Pubsub.subscribe` was not returning a `Promise` when the callback argument was not specified.
Tests are in https://github.com/ipfs/interface-ipfs-core/pull/181
Should resolve https://github.com/ipfs/interface-ipfs-core/issues/174, https://github.com/ipfs/js-ipfs/issues/1137 and https://github.com/ipfs/js-ipfs/issues/1129
> fix(pubsub): subscribe promises

- package.json
- src/core/components/files.js
> fix: files.cat: detect and handle errors when unknown path and cat dir

- src/core/components/files.js
> fix: cat: test file existence after filtering

- package.json
- src/core/components/bitswap.js
- test/core/bitswap.spec.js
Adapts to the new Bitswap stats API.
> Fix: use new bitswap stats

- src/core/components/files.js
- test/cli/bitswap.js
- test/cli/files.js
> fix: ipfs.ls: allow any depth

- src/cli/commands/files/add.js
- test/cli/files.js
- test/fixtures/odd-name-[v0]/odd name [v1]/hello
`glob` was interpreting the '[' as a special magic character.  According to its documentation, a caller should be able to escape it with `\`; but it does not work.
See the [glob issue](https://github.com/isaacs/node-glob/issues/277).
> fix(files.add): directory with odd name

- README.md
ref: https://github.com/ipfs/js-ipfs/issues/843#issuecomment-332088905
> docs: add FAQ about Electron

- src/cli/commands/bitswap.js
- src/cli/commands/block.js
- src/cli/commands/bootstrap.js
- src/cli/commands/dag.js
- src/cli/commands/file.js
- src/cli/commands/files.js
- src/cli/commands/object.js
- src/cli/commands/pubsub.js
- src/cli/commands/repo.js
- src/cli/commands/swarm.js
If subcommands are called, e.g. `jsipfs dag` there was no output
at all. Now the help message (which you also get with `--help`
is displayed.
> fix(cli): show help for subcommands

- package.json
Instead of running the linting and tests on pre-commit, do it
on pre-push. That makes it less frequent (and annoying) while
doing local development.
> chore: change from pre-commit to pre-push hooks

- src/core/components/init-assets.js
This fixes the command "init" on windows. Before this change, none of
the files where actually added to your local repository. With this
change, files are correctly added to the repository as windows uses "\"
as the path separator instead of "/" (posix)
> fix: (cli/init) use cross-platform path separator

- package.json
- src/cli/commands/version.js
- src/core/components/repo.js
- src/core/components/version.js
- test/cli/files.js
- test/cli/repo.js
- test/cli/version.js
- test/sharness/t0010-basic-commands.sh
original: https://github.com/ipfs/js-ipfs/pull/1181
This implements `ipfs repo version` and the `--all`, `--repo`, `--number`, and `--commit` (partially) flags for `ipfs version`.
`ipfs version --all` output looks like:
```
$ js-ipfs version --all
js-ipfs version: 0.27.7-
Repo version: 6
System version: x64/win32
Node.js version: v8.5.0
````
I'm having trouble running sharness tests, am hoping that CI will point out any issues there.
Would love any feedback :)
> `ipfs version` flags and `ipfs repo version`

- src/cli/commands/dag/get.js
If a dag node is JSON, print the stringified version of it, so that
it shows the actual JSON and not just `[object Object]`.
> fix(dag): print data in a readable way if it is JSON

- src/http/api/resources/swarm.js
Closes #1176 
Returning errors as json the cli now receives treated messages as bellow:
```
/Users/paulogr/dev/js-ipfs/src/cli/commands/swarm/connect.js:20
throw err
^
Error: no protocol with name: libp2p-webrtc-star
at parseError (/Users/paulogr/dev/js-ipfs/node_modules/ipfs-api/src/utils/send-request.js:16:17)
at ClientRequest.<anonymous> (/Users/paulogr/dev/js-ipfs/node_modules/ipfs-api/src/utils/send-request.js:39:14)
at Object.onceWrapper (events.js:255:19)
at ClientRequest.emit (events.js:160:13)
```
> fix: Return swarm http errors as json

- examples/browser-script-tag/index.html
Since this link is not using IPFS, it's broken 😩 . Here is the correct one.
> Fixed broken link referencing IPFS-Core API docs in example project

- test/core/bitswap.spec.js
- test/http-api/spec/bitswap.js
> fix: stats tests

- src/cli/commands/version.js
- src/core/components/repo.js
- src/core/components/version.js
- test/cli/files.js
- test/cli/repo.js
- test/cli/version.js
- test/sharness/t0010-basic-commands.sh
@JonKrone I've found the issue, see: https://github.com/ipfs/js-ipfs/pull/1181/files#r163727102
Wanna take a stab at finishing the PR?
You can see where the error comes from if you run `make test --verbose`
```
» ./t0010-basic-commands.sh --verbose
expecting success:
echo "It works!" > test.txt
ok 1 - current dir is writable
expecting success:
ipfs version > version.txt
/Users/imp/code/js-ipfs/src/core/components/version.js:16
throw err
^
Error: ENOENT: no such file or directory, open '/Users/imp/code/js-ipfs/test/sharness/trash directory.t0010-basic-commands.sh/.jsipfs/version'
```
> feat: `ipfs version` flags + `ipfs repo version` (#1181)

- src/core/components/bootstrap.js
- test/core/bootstrap.spec.js
mafmt handles both instances of multiaddr and multiaddrs in strings.
isMultiaddr only handles instances of multiaddr.
Demonstration:
```
> const ma = require('multiaddr')
> const mafmt = require('mafmt').IPFS.matches
> mafmt('/ip4/0.0.0.0/tcp/5001/ipfs/Qm')
true
> ma.isMultiaddr('/ip4/0.0.0.0/tcp/5001/ipfs/Qm')
false
> m = ma('/ip4/0.0.0.0/tcp/5001/ipfs/Qm')
<Multiaddr 0400000000061389a503020562 - /ip4/0.0.0.0/tcp/5001/ipfs/Qm>
> mafmt(m)
true
> ma.isMultiaddr(m)
true
```
> Better validation of Multiaddrs in bootstrap command

- examples/README.md
- examples/browser-add-readable-stream/README.md
- examples/browser-add-readable-stream/index.html
- examples/browser-add-readable-stream/index.js
Addresses #1053 by adding an example of how to use the streaming interface to add files sequentially and obtain the hash of the directory containing the files.
> docs: Add browser example for streaming files

- Dockerfile
- init-and-daemon.sh
- Smaller size (from 1.52GB to 875MB)
- Ignore errors with init as repository could already be initialized if
we restart a running container for example
- Locks down version of wrtc
- Upgrade from node@6 to node@9.5
> Various improvements to Docker Image

- src/http/gateway/resources/gateway.js
This catches the following error. which results in a less crashy gateway as mentioned here https://github.com/ipfs/js-ipfs/issues/804#issuecomment-369912316
```bash
Error: write after end
at writeAfterEnd (/media/op/w3/js-ipfs/node_modules/readable-stream/lib/_stream_writable.js:288:12)
at PassThrough.Writable.write (/media/op/w3/js-ipfs/node_modules/readable-stream/lib/_stream_writable.js:332:20)
at pull.through (/media/op/w3/js-ipfs/src/http/gateway/resources/gateway.js:134:21)
at /media/op/w3/js-ipfs/node_modules/pull-stream/throughs/through.js:17:24
at drain (/media/op/w3/js-ipfs/node_modules/stream-to-pull-stream/index.js:141:18)
at Stream.<anonymous> (/media/op/w3/js-ipfs/node_modules/stream-to-pull-stream/index.js:150:5)
at Stream.emit (events.js:159:13)
at next …
```
> Less Crashy gateway. catch stream2 error

- examples/circuit-relaying/README.md
This is an amendment to #1063. @dryajov feel free to take these or not as you like. I figured it was easy to make a bunch of minor technical language edits directly instead of trying to explain them in PR comments.
> Add minor grammar/spelling fixes to Circuit Relay example doc

- package.json
- src/core/components/files.js
Adding back ability to pass objects to `files.add` - `{path: <string>, data: Buffer.from('hello')}`. This regressed in 4b79066b924b8e8bf7f8a0fde0da40c3c1b84f31
> fix: accept objects in file.add

- package.json
- src/core/config.js
- src/core/index.js
- test/core/config.spec.js
This PR validates config options passed to IPFS and throws immediately if they are not as expected.
This is a proposal to fix #1193.
We use `joi` to validate config as it's expressive and already included in the project. It's also the best validation library I've come across.
I've verified the config objects used in all the tests work but **I can't say for sure if this is a breaking change or not so you should probably regard it as one when releasing**.
The idea is that the validation should be flexible and shouldn't block new features landing in JS-IPFS. Validation of values that are objects **allows for unknown keys** so that features can land, and validation for the config can be backfilled at a later date if needs be.
I've also configured the `browser` field in `package.json` to use …
> feat: add config validation

- src/core/components/dht.js
This PR reinstates the non local block check in `dht.provide` to mirror the functionality of go-ipfs.
Please see [this discussion](https://github.com/ipfs/interface-ipfs-core/pull/221#issuecomment-370938018) for the context.
> fix: reinstates the non local block check in dht.provide

- package.json
Let's see if this -- https://github.com/ipfs/js-ipfsd-ctl/pull/215 -- makes things faster.
> chore: update ipfsd-ctl to use smaller key size for daemon tests

- bw
- package.json
- src/cli/commands/stats/bw.js
- src/core/components/stats.js
- src/core/components/swarm.js
- src/http/api/resources/stats.js
- src/http/api/routes/stats.js
- test/cli/commands.js
It was decided on #1198 that the implementation of the Bandwidth Stats should be done in a different PR since it first needs https://github.com/libp2p/js-libp2p/issues/157 to get merged. This issue is used to track the progress on that.
> feat: .stats.bw* - Bandwidth Stats

- src/cli/commands/files/add.js
- src/core/components/files.js
- src/http/api/resources/files.js
- test/cli/config.js
- test/cli/files.js
- test/http-api/files.js
- test/utils/ipfs-exec.js
Continuing the work from #1233
> feat: jsipfs add --only-hash (#1233)

- README.md
In the Table of Contents, there is a link of npm.
But it did't work, because npm wasn't a header.
It's necessary to add a npm header to work a link of it well.
> docs: add a npm header in the README.md

- README.md
> docs: add stats.bw* to README

- src/core/components/swarm.js
Removed an unused var that was producing a linter error.
> fix: remove unused var

- Dockerfile
Make it possible to run `jsipfs` commands inside the container :+1:
> chore: symlink the jsipfs bin to /usr/local/bin in the Dockerfile

- package.json
`npm run test:node:core` was failing to run the interface test suite beneath core. This fixes the glob to ensure the whole core suite is runnable via the command.
resolves #1276
> test: update glob for node core test runner

- README.md
This adds some description to the "advanced options" documentation for the `IPFS` constructor detailing that `init: false` should really be used if a repo has already been initialized *by IPFS* and that simply calling `repoInstance.init()` doesn't init a repo with everything IPFS needs.
This partially handles #1245, but other parts of the experience (e.g. #1262) could also be improved.
Does this help clarify things? Or is it too confusing?
Is there anywhere else these options are documented that I need to update? (I couldn’t find anywhere, but I wouldn’t be surprised if I missed something.)
> Describe when and why to use `init: false`

- src/cli/commands/init.js
Connects to https://github.com/ipfs/js-ipfs/issues/1213.
I tried using .usage() from the yargs package, but it just seems to be a different way of doing normal yargs configuration (no special ability to add a prologue).
> cli: add IPFS_PATH info to init command help

- README.md
This adds more descriptive and organized definitions for all the available options to the `IPFS` constructor as well as a full reference of events and the `start()` and `stop()` methods.
Some open questions here:
- I documented `start()` and `stop()`, but wasn’t sure which of the other methods are considered `public` that we should document.
- I used `node` to refer to the `IPFS` instance throughout example code and in references for methods (`start` and `stop`). That matches the pre-existing usage examples. However, the core API reference uses `ipfs.xyz`. I think we should make both the same for clarity. `node` sounds *slightly* better to me, but I do not have a strong opinion.
- I don’t know enough to say more than what we already had about the `EXPERIMENTAL.dht` option. Is there …
> Document constructor options more formally

- src/cli/commands/files/add.js
- src/core/components/files.js
- src/core/components/object.js
- src/http/api/resources/files.js
- test/cli/files.js
Since [PR 1005](https://github.com/ipfs/js-ipfs/pull/1005/) has been blocked for a while, I went through it. 
As the PR origin is from an external organization, I created a new branch instead of rebasing it in its origin. Shortly, I got the @alanshaw (thanks :D ) implementation with `js-ipfs` master branch and made a few changes, as a consequence of the modifications that occurred meanwhile in `components/objects`, as well as in `resources` and a minor refactor. 
Finally, I added tests for several hash algorithms, since there are more than [300](https://github.com/multiformats/js-multihash/blob/master/src/constants.js). Should I add more to the tests?
> feat: Add support for specifying hash algorithms in files.add

- src/cli/bin.js
- src/cli/commands/daemon.js
- src/cli/commands/init.js
- src/cli/utils.js
- test/cli/daemon.js
- test/cli/init.js
Aiming to have a consistent menu with `go-ipfs`, I added the `IPFS_PATH` as it is presented in Go implementation.
```
ipfs uses a repository in the local file system. By default, the repo is
located at ~/.ipfs. To change the repo location, set the $IPFS_PATH
environment variable:
export IPFS_PATH=/path/to/ipfsrepo
```
In PR https://github.com/ipfs/js-ipfs/pull/1274, it was added to `jsipfs init --help`, but it was presented before the options description, instead of in the end.
In this solution, I changed the previous implementation. Using `yargs epilog`, I added the `IPFS_PATH` message to the epilogue which is displayed for the following cases:
- `jsipfs`
- `jsipfs --help`
- `jsipfs init --help`
- `jsipfs daemon --help`
Closes #1213
> fix: Add ipfs path to cli help

- README.md
I thought I’d done this in the initial round of docs, but apparently I missed it! (Noticed while looking at #1316)
> Document object form of `init` constructor option

- src/cli/commands/stats/bitswap.js
The `stats bitswap` command is an alias of `bitswap stat`. That should
also be reflected in the code.
> refactor: remove duplicated code

- src/cli/commands/daemon.js
- src/http/index.js
This will allow to spin ipfs nodes using `js-ipfsd-ctl` and the DHT experimental feature enabled.
> chore: allow dht to be enabled via cli arg

- package.json
- src/cli/commands/ping.js
- src/core/components/ping.js
- src/http/api/resources/index.js
- src/http/api/resources/ping.js
- src/http/api/routes/index.js
- src/http/api/routes/ping.js
- test/cli/commands.js
- test/cli/ping.js
- test/core/ping.spec.js
- test/http-api/inject/ping.js
Just opening this for visibility, working on finishing the ping endeavour started at #1202.
Also, some relevant notes. Seems like hapijs has compression enabled by default, which means responses  will take into account the `Accept-Encoding` header and will use gzip to compress responses (it seems hapi has no way of disabling compression for a specific route only also). From what I've seen the `go-ipfs` http api doesn't gzip responses by default AFAIK. Anyway, there seems to be an issue when compression is enabled and we're streaming responses - https://github.com/hapijs/hapi/issues/3599 - as it seems the response is actually buffered, compressed and only then it is sent to the client. This results in the actual "streaming" capabilities being lost (the response all at once and only when it …
> feat: ping

- src/cli/bin.js
- src/cli/utils.js
- test/cli/daemon.js
This is an alternative to https://github.com/ipfs/js-ipfs/pull/1336 inlining all the requires in every file for the CLI. This is a great idea but I wanted to see if it could be done with minimal disruption as well as [other reasons](https://github.com/ipfs/js-ipfs/pull/1336#issuecomment-387439256).
I had a look at the good work in #1336 and have taken the best bits that provide us with the biggest gains 🚀 
I've changed `src/cli/bin.js` so that `commandDir` now takes an `include` filter. The idea being to only include the command files for the sub-system the user asked for. i.e. if the user types `jsipfs files add` then we only require `src/cli/commands/files.js`.
I've applied the changes @VictorBjelkholm made to `test/cli/daemon.js` verbatim as this was also really beneficial.
Inlining …
> perf(cli): load only requested sub-system modules and inline require ipfs and ipfs-api

- README.md
- examples/run-in-electron/README.md
- examples/run-in-electron/build.sh
- examples/run-in-electron/package.json
Use electron 2.0 latest version for semver versioning & few updates on Node JS compatibility. 
With Electron 2.0, `npm start` electron console print the messages.
```
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmX8WSZZ3q1f8CCg4kenTvoT84j5rp6jcyhwE4ytkGkPVt
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmX8WSZZ3q1f8CCg4kenTvoT84j5rp6jcyhwE4ytkGkPVt
Swarm listening on /ip4/192.168.25.7/tcp/4002/ipfs/QmX8WSZZ3q1f8CCg4kenTvoT84j5rp6jcyhwE4ytkGkPVt
{ id: 'QmX8WSZZ3q1f8CCg4kenTvoT84j5rp6jcyhwE4ytkGkPVt',
publicKey: 'CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCik4bdmt8Dj9luRgSSi5dejX2Uc3HpUkVmBzXmioEn69Int8fBN7E2OudyhmyE/OBbApWUbMBGBUbqDbmDwjcdXKaJQDBb6LLtNyakU+uwndqONalxaDAcxT7Kfi4+TnQrQe1/F4y7q+y6ntf78f+uqHPjPHM0astfeqUaB9ULIjNewaLezBWuBQ1D87KXoiv4V9xNGnPAU9egK5VRSU1HW+M9yTBJBG …
```
> example(run-in-electron): update to latest electron 2.0, electron-rebuild 1.7.2

- src/cli/commands/object/data.js
- test/cli/object.js
For consistency with go-ipfs we should not add newlines to the output of `ipfs object data`.
go:
```
$ echo 'Hello' | ipfs files write --create /hello.txt
$ ipfs files ls / -l | grep hello.txt
hello.txt	QmcnK4wpoB6ozwZ7Siye8wyVTHYKNNoNvapPMLuCYUrHK2	6
$ ipfs object data QmcnK4wpoB6ozwZ7Siye8wyVTHYKNNoNvapPMLuCYUrHK2 | xxd
00000000: 0802 1806 2006                           .... .
```
js without this PR (with experimental mfs support) - note the extra `0a` at the end:
```
$ echo 'Hello' | JSipfs files write --create /hello.txt
$ jsipfs files ls / -l | grep hello.txt
hello.txt	QmZo8WtosAnHDHXWCvih3xJsiENgdaKBmdx4gKnYmRtSUu	6 
$ jsipfs object data QmZo8WtosAnHDHXWCvih3xJsiENgdaKBmdx4gKnYmRtSUu | xxd
00000000: 0802 1806 2006 0a                        .... ..
```
js with this PR:
```
$ echo …
```
> chore: do not add newlines to object data

- .aegir.js
Big.js just released an update that added esmodule support by adding a "module" field to their package.json. By default, webpack will use this field when requiring a module. Since esmodules aren't fully supported in the browser and we don't do any transpiling this PR configures webpack to not consider the esmodule field.
[Webpack `mainFields` docs](https://webpack.js.org/configuration/resolve/#resolve-mainfields)
[Why `require('big.js')` is broken for us](https://github.com/webpack/webpack/issues/4742)
Fixes https://github.com/ipfs/js-ipfs/issues/1363
Note that this solves the issue for `big.js`, but also for any other modules in the future that decide to define a `module` field in their `package.json` or any that already do and we just haven't realised it yet!
> fix: configure webpack to not use esmodules in dependencies

- package.json
Upgrade `ipfsd-ctl` version for unblocking #1331
> chore: upgrade ipfsd-ctl dependency version

- src/cli/commands/repo/gc.js
- src/core/components/repo.js
- src/http/api/resources/repo.js
Previously calls to repo.gc would hang or fail silently or in the case of the HTTP API cause a 404. This PR responds to calls to repo.gc with an error to inform that this feature will eventually exist (it is spec'd) but is not implemented yet.
> fix(repo): do not hang on calls to repo gc

- CONTRIBUTING.md
Fixes https://github.com/ipfs/js-ipfs/issues/1385.
> fix: broken contributing links

- src/cli/commands/object/data.js
- test/cli/object.js
- test/utils/ipfs-exec.js
Without this change:
```sh
$ jsipfs object data `dd if=/dev/urandom bs=307200 count=1 | jsipfs files write --create /some-file && jsipfs files stat -h /some-file` | unixfs
{"type":"file","blockSizes":[72481833443311,10909182287855]}
```
e.g.
```
00000000: 0802 18ef bfbd efbf bd12 20ef bfbd efbf  .......... .....
00000010: bd10 20ef bfbd efbf bd02                 .. .......
```
With this change:
```sh
$ jsipfs object data `dd if=/dev/urandom bs=307200 count=1 | jsipfs files write --create /some-file && jsipfs files stat -h /some-file` | unixfs
{"type":"file","blockSizes":[262144,45056]}
```
e.g.
```
00000000: 0802 1880 e012 2080 8010 2080 e002       ...... ... ...
```
Stringifying the data changes it's encoding. Been banging my head against this all morning.
> fix: do not stringify output of object data

- package.json
- src/cli/commands/bitswap/stat.js
- src/cli/commands/bitswap/unwant.js
- src/cli/commands/bitswap/wantlist.js
- src/cli/commands/block/get.js
- src/core/components/bitswap.js
- src/http/api/resources/bitswap.js
- src/http/api/resources/block.js
- src/http/api/routes/bitswap.js
- src/http/api/routes/stats.js
- test/cli/bitswap.js
- test/core/bitswap.spec.js
- test/core/interface/bitswap.js
- test/core/interface/interface.spec.js
- test/http-api/index.js
- test/http-api/interface/bitswap.js
Because of the amount of work done in #1306 this PR is built off of that, that PR needs to be merged before this one can be isolated and discussed.
This adds a peerId parameter to bitswap.unwant.
Tests are in https://github.com/ipfs/interface-ipfs-core/pull/267
API changes are in https://github.com/ipfs/js-ipfs-api/pull/761
> feat: bitswap.wantlist peerid

- test/cli/bitswap.js
Sometimes we pick up partners during the test so we can't
reliably assert that part of the output
> fix(tests): loosen assertion for bitswap.stat test

- src/http/index.js
Sets up Hapi's debug logging when DEBUG env var is present.
This will enable developers to see what is happening inside
the daemon when ipfs/js-ipfsd-ctl#270 is merged instead of just
getting error messages like 'Please retrace your steps'.
It lets you do this sort of thing:
```
$ DEBUG=ipfsd-ctl:daemon:* npm test
```
...and see Hapi's request/server logs in the output.
> chore: add debug logging to http server

- ci/Jenkinsfile
I believe these were changed to add Node.js 10 when we were trying to get support for Node.js 10 working. This PR reverts to using the defaults, which are currently the LTS versions 8 and 10.
> chore: use default Node.js versions on CI

- package.json
- src/core/components/pin.js
- src/http/api/resources/block.js
This PR allows the test in https://github.com/ipfs/interface-ipfs-core/pull/308 to pass.
`X-Stream-Output` header is added to the `block.get` reply for parity with go-ipfs.
`block.put` is altered to allow an empty block to be put (again for feature parity with go-ipfs) but only if there is a multipart file part for it. Error responses have also been improved.
depends on https://github.com/ipfs/js-ipfs-api/pull/789
tested by https://github.com/ipfs/interface-ipfs-core/pull/308
> fix: allow put empty block & add X-Stream-Output header on get

- package.json
- src/core/components/dag.js
The [dag.put](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DAG.md#dagput) interface
takes an options object which is required, but should be optional with
decent defaults.
See dedicated test here: https://github.com/ipfs/interface-ipfs-core/pull/316
This commit implements this behaviour.
**Before**:
```js
ipfs.dag.put(obj, options, (err, cid) => {...});
```
^ Prior to this commit, without passing `options`, this call resulted in an error.
**After**:
```js
ipfs.dag.put(obj, (err, cid) => {...});
```
^ This is now perfectly fine.
Fixes #1395
License: MIT
Signed-off-by: Pascal Precht <pascal.precht@gmail.com>
> fix(core/components/dag): make options in `put` API optional

- src/core/components/dag.js
Turns out we've introduced a little bug in https://github.com/ipfs/js-ipfs/commit/d299ed77c288d82ce807af0ec7a5b2605336626f
in which the default hash algorithm has a typo.
This didn't fail on CI because the `options.hashAlg` passed down to `ipld.put()`
is actually not being used at time of this commit.
For more info see: https://github.com/ipld/js-ipld/blob/d3d78e053ebd3f8c85a8b5579715be8812773d4d/src/index.js#L236-L239
License: MIT
Signed-off-by: Pascal Precht <pascal.precht@gmail.com>
> fix(core/components/dag): fix default hash algorithm for put() api

- README.md
- package.json
- src/core/components/libp2p.js
- src/core/config.js
Exposes options for the connection manager (see https://github.com/libp2p/js-libp2p-connection-manager#create-a-connectionmanager) as an optional top level option called `connectionManager`.
> feat: expose libp2p connection manager configuration options

- test/core/interface.spec.js
Over at https://github.com/ipfs/interface-ipfs-core/pull/323 we introduce a
test spec that ensures `dag.put()` honors the `hashAlg` option, which at
the time of this commit is ignored by the underlying `ipld.put()` API
(more info: https://github.com/ipfs/js-ipfs/commit/1a36375fa7c19ba5da11b1a7f84ee79d910742bc).
This commit skips that spec in `js-ipfs` as https://github.com/ipld/js-ipld/pull/133 has to
land first to fulfill the scenario.
License: MIT
Signed-off-by: Pascal Precht <pascal.precht@gmail.com>
> test(dag): skip spec for put API

- test/cli/object.js
> fix: increase timeout for unadulterated data test

- examples/browser-video-streaming/README.md
- examples/browser-video-streaming/index.html
The recent version of hsljs-ipfs-loader works well with no error (#1422)
> fix: update hlsjs-ipfs-loader version (#1422)

- examples/README.md
- examples/browser-mfs/README.md
- examples/browser-mfs/filetree.js
- examples/browser-mfs/forms.js
- examples/browser-mfs/index.html
- examples/browser-mfs/index.js
- examples/browser-mfs/package.json
- examples/browser-mfs/utils.js
- examples/browser-mfs/webpack.config.js
- package.json
Adds an interactive MFS example that runs in the browser!
Also upgrades to the latest js-ipfs-mfs to fix some bugs around handling errors when trying to copy files/directories onto themselves.
> docs: adds mfs browser example

- src/core/components/pin.js
It's legal javascript, but the docs command fails if this function is called pin 😕 
You can test this fix out by running `npx aegir docs` in the project directory.
> fix: aegir docs fails if outer function is called pin

- src/cli/commands/daemon.js
- src/core/boot.js
- src/core/components/init.js
- src/core/components/pre-start.js
- src/core/components/start.js
- src/core/state.js
This is a fix for `preStart` being called twice but also a partial refactor of the boot sequence.
The problem is that `preStart` always needs to be called between `init` and `start` and was actually being called in `boot.js` (via the `IPFS` constructor if repo exists or is newly initialized) as well as in `start.js`.
The following permutations of constructing, initializing and starting show how `preStart` was being called twice:
```js
const ipfs = new IPFS({ init: false, start: false })
ipfs.on('ready', () => {
await ipfs.init()
await ipfs.start()
})
```
`preStart` is called ✅ 
`preStart` is called once from `ipfs.start()` ✅ 
```js
const ipfs = new IPFS({ init: true, start: false })
ipfs.on('ready', () => {
await ipfs.start()
})
```
`preStart` is called ✅ 
`preStart` is called once from …
> fix: double pre start

- OKR.md
**IPFS:**
- [Spreadsheet for IPFS 2018 Q3](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit#gid=274358435)
- [PR for 2018 Q2 for reference](https://github.com/ipfs/js-ipfs/pull/1281)
> docs: 2018 Q3 OKRs

- README.md
I believe you meant to write `npm run test:node` in the instructions on how to run the unit tests. The `npm run test:node:core` line was written twice. Cheers
> [documentation] Fixing incorrect npm run test line

- CHANGELOG.md
- README.md
Closes #1444
License: MIT
Signed-off-by: Pascal Precht <pascal.precht@gmail.com>
> chore(README): Add migration note about upgrading from < 0.30.0

- CHANGELOG.md
- README.md
This reverts commit 48aceb1392ccdf230a764dfb74e2ab4e4f7d06a9.
This issue was fixed upstream. As we use version ranges for dependencies,
it is automatically fixed now. Hence reverting the original commit.
cc @PascalPrecht
> revert: docs: add migration note about upgrading from < 0.30.0 (#1450)

- src/core/boot.js
- test/core/create-node.spec.js
`init` and `start` both emit any error they encounter. `boot` will then receive that error and also emit it! This PR adds an `emitted` property in `boot` to errors that came from `init` or `start` so that later in the code it knows whether to emit it or not!
> fix: emit boot error only once

- src/core/runtime/preload-browser.js
This PR switches to using the fetch API instead.
fixes #1477
> fix: XMLHttpRequest is deprecated and unavailable in service workers

- src/core/components/dht.js
This is to complement: https://github.com/ipfs/interface-ipfs-core/pull/337
Fixes #1322
> fix(dht): allow for options object in `findProvs()` API

- package.json
- test/core/bitswap.spec.js
- test/core/interface.spec.js
> test: enable bitswap tests on windows

- README.md
GitHub appears to understand "JavaScript" after backticks but npm doesn't, so there wasn't syntax highlighting on these two code blocks at https://www.npmjs.com/package/ipfs
> Update JavaScript syntax highlighting

- src/core/components/dag.js
- test/core/pin.js
> fix(dag): check dag.put options for plain object

- README.md
This PR changes the constructor options into headings so that people can link the relevant options. I have needed this multiple times but haven't been able to give people a link to the correct part of the page.
> docs: make constructor options linkable

- README.md
The `start` example was missing the `ready` event. The example
is now more similar to the `stop` example.
> docs: improve start example

- test/core/interface.spec.js
- test/utils/dns-fetch-stub.js
Stubs `self.fetch` to return a static CID for calls to `https://ipfs.io/api/v0/dns?arg=ipfs.io`.
Removes dependency on external service.
> fix: stub out call to fetch for ipfs.dns test in browser

- package.json
- src/cli/commands/object/get.js
- src/http/api/resources/object.js
- test/cli/object.js
This is the js counterpart to ipfs/go-ipfs#5139 and will allow the test in ipfs/interface-ipfs-core#302 to pass.
ipfs/js-ipfs-api#806 needs this to be merged before the interface test linked to above will pass.
> feat: adds data-encoding argument to control data encoding

- README.md
This PR adds separate examples for each of the different methods of starting/stopping a node (promises, callbacks, events) instead of a single confusing example with all the methods in one code snippet.
This makes for easier copy/paste.
Also switches promise method to use async/await syntax.
> docs: better start and stop examples

- README.md
Adds the docs that are in the js-ipfs-api README for pin.
Also removes code blocks from the non-code headings...
> docs: add pin API doc links

- src/cli/commands/files/add.js
- src/core/components/files.js
- src/core/utils.js
- src/http/api/resources/files.js
- test/core/utils.js
This allows the chunking algorithm, and options to be specified when using the adding files.
Specifying chunker and options are identical to go-ipfs and support the following formats:
* `default`
* `size-{size}`
* `rabin`
* `rabin-{avg}`
* `rabin-{min}-{avg}-{max}`
Example usage via command line as follows
```bash
$ ./src/cli/bin.js add --chunker rabin-48-96-192 LICENSE
added QmZH1VRMjDD48A7uqzaEU6qdfk4ddNVKZLnBMN1Lc1iEic LICENSE
$ ./src/cli/bin.js object links QmZH1VRMjDD48A7uqzaEU6qdfk4ddNVKZLnBMN1Lc1iEic
QmamX3HDpMkE6NNun2pvz1UmBubA1nsuEzMEnBqUSVXy5E 180
QmdH3L1zu7hWu7nrpoCe33zfn3hDm6baYpTSENbRitpcFu 140
Qmaw7roFAKSj3V3QxmFUfpqU3dqAEMPMqHynqXxJmhhGhB 64
Qmewm77gB4V7cgnZLsuikXgrG8Q38M1TX8qPRBcKrw4yJ4 90
QmRd6EoLAyp6TXZmSRTByaAgEn5632J8u9NwFSiHfXurLx 95 …
```
> feat: Add option to specify chunking algorithm when adding files

- src/cli/commands/daemon.js
- src/cli/commands/init.js
Command: `ipfs cat QmfM2r8seH2GiRaC4esTjeraXEachRt8ZsSeGaWTPLyMoG`
For talking to the daemon over the HTTP API there should be no need to `require` IPFS core.
I noticed that the CLI `daemon` command required the HTTP API, which requires `Hapi`, and IPFS core itself. Similarly, the `init` command also requires IPFS core itself.
Moving these requires inline avoids this.
Before (> 1200ms total):
After (< 600ms total):
> perf: faster startup

- src/core/components/init-assets.js
`ipfs files cat` does not exist (nor in go-ipfs), change to `ipfs cat`
> fix: get started command

- src/core/boot.js
change _compatability_ to _compatibility_
> fix typo in comment

- README.md
Usage seems to fit the [Merriam-Webster transitive verb (2e)](https://www.merriam-webster.com/dictionary/bear) a bit better.
> docs: bare->bear 🐻

- src/core/ipns/publisher.js
- src/core/ipns/resolver.js
There are two types of IPNS records. IPNS records for being stored locally and IPNS records for being used in the network.
IPNS records for being stored locally are used for understanding which is the most recent record since it is stored by the peer who published it.
IPNS records for being used in the network, are used as a common [libp2p-record](https://github.com/libp2p/js-libp2p-record) and are intended to be used with the DHT and Pubsub.
This way, the `libp2p-record` should have a signature and that signature should be validated on the resolve, in order to guarantee that the record was not changed in the network. 
NOTE: The current implementation guarantees that the `IPNS Record` is not changed, since it has its own signature, but the `libp2p-record` used must be used as a generic …
> fix: libp2p records for ipns should be signed

- src/cli/commands/name/publish.js
`yargs-promise` [adds](https://github.com/eddywashere/yargs-promise/blob/master/index.js#L14) resolve/reject properties to `argv`. 
This way, `resolve` option was being overwritten to a function and, as it was not `false`, it was defined always as true for the `publish` operation.
Publish should use the `r` alias instead, as resolve will always be overwritten to a function.
> fix: ipns publish resolve option overwritten

- test/core/mfs-preload.spec.js
JS makes no guarantees a function you schedule with `setTimeout` will execute before another function you schedule _even_ if the second function is scheduled for execution _after_ the first.
This PR fixes the MFS preload test to wait for the expected CIDs to have been preloaded instead of assuming they would be preloaded after a certain time.
> fix: mfs preload test

- src/core/index.js
The `_pubsub` property was added in [https://github.com/ipfs/js-ipfs/pull/749](https://github.com/ipfs/js-ipfs/pull/749). However, after several refactors it seems that it is not being used anymore.
> chore: remove unused instance property

- src/core/utils.js
- test/core/node.js
@vasco-santos uses `npm run test:node:core` which runs tests in `test/core/**/*.js` and there were some tests failing.
CI runs `npm test` => `npm test:node` => which runs only `mocha test/node.js`.
...which requires only:
```
require('./cli')
require('./http-api')
require('./gateway')
require('./core/node.js')
```
and core/node.js requires only
```
require('./pin')
require('./pin-set')
```
NOT `utils.js` and others!!!
Lets see if they pass.
> fix: enable tests in node that were not being included

- RELEASE.md
Please see #1533 for details.
closes #1533
> docs: add publish release candidate to release checklist

- package.json
`libp2p-crypto` is a direct dependency of `js-ipfs` but it wasn't in the `package.json` deps list.
fixes #1571 
License: MIT
> fix: add libp2p-crypto to deps list

- RELEASE.md
PeerPad no longer uses `peer-pad-core` but instead uses `peer-star-app`.
> chore: update project to test for peerpad

- src/cli/commands/block/rm.js
On the command line `block rm` failed.
Sadly the test can't be enabled yet, as the HTTP API doesn't implement it yet.
> fix: fix `block rm` command

- README.md
- package.json
It was already possible, but now it's documented an a bit simplified.
Thanks @jacobheun for explaining me how the `grep` functionality works.
> Add way to run a subset of the interface tests 

- src/cli/commands/key/gen.js
- src/http/api/resources/key.js
Keychain params are now validated properly and has caused these test to fail https://github.com/libp2p/js-libp2p-keychain/pull/26
> fix: coerce key gen size to number in CLI

- README.md
Preload is confusing because it happens on both add and get, and because it isn't documented anywhere in depth. This clarifies what happens a bit. We should also write out the behavior in more detail like with circuit relay above (possibly in the form of a tutorial for setting up your own preload node)
see also https://github.com/ipfs/js-ipfs/issues/1459#issuecomment-422079307
> Clarify preload behavior

- src/core/components/files.js
- test/core/files.spec.js
- test/http-api/files.js
If you specify `cidVersion: 0`, for go compatibility you will have raw leaf nodes. If your data fits in one dag node, the root node will be a raw node for the same reason, and `ipfs.object.get` will return a buffer.
This PR inspects the returned node to see if it's a buffer, if it is, use the `length` property, otherwise use the DAGNode `size` property.
Fixes #1585
> fix: report correct size for raw dag nodes

- src/core/ipns/publisher.js
- src/core/ipns/resolver.js
The [js-ipfs#1543](https://github.com/ipfs/js-ipfs/pull/1543) broke the interop tests for `IPNS` on [interop#26](https://github.com/ipfs/interop/pull/26).
The [js-ipfs#1543](https://github.com/ipfs/js-ipfs/pull/1543) was added after my analysis for the implementation of `IPNS over Pubsub`, as I wanted to have exactly the same behavior and interface as the DHT, in order to have an easy to plug DHT afterward. Accordingly:
**DHT PUT**:
[js-libp2p-kad-dht/index.js#L166](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/index.js#L166)
[js-libp2p-kad-dht/utils.js#L150](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/utils.js#L150)
So, I wanted to make this logic available to Pubsub / local and it is all good in JS land. However,`go-ipfs` does not do that: …
> fix: revert libp2p records being signed for ipns

- OKR.md
Ref: https://github.com/ipfs/pm/issues/698
- [2018 Q3 Retrospective Document](https://docs.google.com/document/d/1ITVW5yysj0bZiluEKasQ57edpNwOZ-P5GQGgoclwQno/edit#heading=h.906pmio05dzr). Please complete this ASAP.
- [Previous OKR Planning for reference](https://github.com/ipfs/js-ipfs/pull/1409)
- [2018 Q4 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit)
@alanshaw, @hugomrdias, @achingbrain et al, you know the drill :)
> 2018 Q4 OKRs Planning

- README.md
Was pointing to the wrong build
> chore: correct build badge

- examples/browser-add-readable-stream/index.js
- examples/browser-browserify/public/index.html
- examples/browser-browserify/src/index.js
I've changed a few things to make the code a bit more consistent.
> Enhance code style in examples

- src/http/gateway/resources/gateway.js
- src/http/gateway/routes/gateway.js
- test/gateway/index.js
This PR makes js-ipfs Gateway return the same headers as HTTP Gateway exposed by go-ipfs, namely:
- `X-Ipfs-Path`: requested IPFS Path of returned resource
- `Etag`: multihash of returned payload
- `Cache-Control`: disable cache for directory listings and errors,
enable heavy caching for immutable assets from /ipfs/ namespace
- `Suborigin`: use root CID in base32 and literal prefix to conform
to current suborigin spec (https://github.com/ipfs/in-web-browsers/issues/66)
cc https://github.com/ipfs/js-ipfs-http-response/issues/10
> feat(gateway): X-Ipfs-Path, Etag, Cache-Control, Suborigin

- src/core/components/ping.js
- test/core/ping.spec.js
Without this PR:
```console
$ npm test
...*snip*
Uncaught TypeError: Cannot read property 'push' of null
at /Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/pull-stream/sinks/collect.js:7:9
at /Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/pull-stream/sinks/reduce.js:8:11
at /Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/pull-stream/sinks/drain.js:24:37
at callback (/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/pull-pushable/index.js:84:5)
at Function.push (/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/pull-pushable/index.js:44:7)
at libp2pNode.ping (src/core/components/ping-pull-stream.js:79:18)
at _getPeerInfo (/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/libp2p/src/index.js:339:7)
at setImmediate …
```
> fix: make ipfs.ping() options optional

- test/core/key-exchange.js
Observed to fail repeatedly on macOS
> chore: increase timeout for key exchange import test

- package.json
- src/cli/commands/daemon.js
- src/http/index.js
- make it easier for people to discover the Web UI
- tidy up inconsistencies across the log lines
- add IPFS to the first line. confirm to new users they started what they expected to.
fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/815
**Before**
```console
$ jsipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmPmrqh4ybdUJwGchEecuj2GBXCxKL5iapW9qmk8pwgCGs
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmPmrqh4ybdUJwGchEecuj2GBXCxKL5iapW9qmk8pwgCGs
Swarm listening on /ip4/192.168.1.244/tcp/4002/ipfs/QmPmrqh4ybdUJwGchEecuj2GBXCxKL5iapW9qmk8pwgCGs
API is listening on: /ip4/127.0.0.1/tcp/5002
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9090
Daemon is ready
```
**After**
```console
$ node src/cli/bin.js daemon
Initializing IPFS …
```
> feat: show Web UI url in daemon output

- src/http/api/routes/files.js
- test/http-api/inject/files.js
- test/http-api/inject/pin.js
Weirdly we're not seeing this when using Node.js - it only happens in the browser.
My _guess_ is that [`maxBytes`](https://github.com/hapijs/hapi/blob/1c9a4f3d7c8cd583650292f4284c87ac5b935107/API.md#-routeoptionspayloadmaxbytes) is actually the max bytes allowed for a given chunk and that in Node.js the underlying stream implementation chunks up the chunks you pass to it even if you only write a single huge chunk. In the browser we know that `stream-http` buffers up all the data and sends it in one go so perhaps that is what is happening.
Anyway, the test in the PR using `inject` proves that with a single buffer we can get a `413` (payload too large) for any request over 1024 * 1024 bytes.
This is feature compatible with go-ipfs which has no such limit.
fixes #1638
refs …
> refactor: remove maxBytes restriction

- examples/browser-webpack/src/components/app.js
The webpack example printed out the contents of the file in hex
(`1041011081081113211911111410810032102114111109321191019811297991071011003273807083`)
instead of a properly formated string (`hello world from webpacked IPFS`).
> fix: correct output in webpack example

- package.json
This PR removes unused deps.
When this https://github.com/ipfs/js-ipfs/pull/1663 is merged, we will be able to use `npm run dep-check -- --extra` to check for unused packages
> fix: remove unused deps

- package.json
- src/core/ipns/publisher.js
- src/core/ipns/republisher.js
As `instance of` fails using different versions of a module, it was changed to use `class-is`.
Needs:
Fixes #1615
> fix: use class is function on ipns

- package.json
- src/core/ipns/publisher.js
The `libp2p-record` module was updated to interop with `go-libp2p-record`.  As a result, the author and signature were removed, as well as all the logic inherent to the signature.
More info [js-libp2p-record#8](https://github.com/libp2p/js-libp2p-record/pull/8)
> chore: upgrade libp2p record version

- package.json
- src/core/index.js
- test/core/init.spec.js
Prior to this caange the `ipld-dag-cbor` and `ipld-dag-pb` modules
are re-exported so that can be accessed within the Browser bundle.
Those modules normally don't need to be used directly, they are
kind of implementation details of IPLD. Hence remove them.
Now `ipld-dag-cbor` isn't a direct dependency of `jsipfs` anymore.
BREAKING CHANGE: remove `types.dagCBOR` and `dag.dagPB` from public API
> chore: remove ipld formats re-export

- src/cli/commands/init.js
- src/core/components/init.js
This PR adds support to pass node config in the init cmd. The main purpose for this is to improve the speed of ipfsd-ctl and all the tests that use ctl.
example: `ipfs init '{"Addresses":{"Swarm":["/ip4/0.0.0.0/tcp/4003"]}}'`
This merges the input config with the default config, just like the node api already does.
Check ipfsd-ctl PR related to this one for speed improvements https://github.com/ipfs/js-ipfsd-ctl/pull/303
Right now we need to spawn 4 child_processes to start a node in ctl
- ipfs init
- ipfs config show
- ipfs config replace
- ipfs daemon
With this PR we would only need 2
- ipfs init <condig>
- ipfs daemon
And with further changes we could do `ipfs daemon --init --config "{}"`
Right now i think we have a couple of problems with this
- go ipfs init needs the config to be in …
> feat: add support to pass config in the init cmd

- test/core/dht.spec.js
- test/core/ping.spec.js
With Ping buffering on the HTTP API, the expectation on this test needs to change for (now).
On a related note, this Core test is spawning daemons, while it should use be using the in proc node directly
> Missed Ping with DHT test

- test/core/interface.spec.js
Enables the tests we can run! \o/
> test: enable some of the core interface DHT tests

- src/core/components/dag.js
- src/core/components/files.js
- src/core/components/object.js
- src/core/components/pin.js
- test/core/preload.spec.js
- test/utils/mock-preload-node.js
TLDR; Preload was sending preload requests for EVERY dag node of an added file. This is unnecessary as the preload request will recursively slurp down the entire graph. This PR fixes that behaviour.
---
Adding file(s) causes the preload module to preload any **root** nodes for the added content. It sends a HTTP request to preload for each root CID because the API on the preload nodes will fetch any children automatically. This greatly reduces the number of HTTP requests we have make when adding large files that are chunked into multiple nodes.
However, the issue was that the tests were checking that a CID had been requested for preload, not that it had been requested only once.
I was inspecting the debug output for preload because of the recent [CORS issues we've been …
> fix: over eager preload

- test/cli/name.js
- test/core/block.spec.js
- test/core/dag.spec.js
- test/core/dht.spec.js
- test/core/files.spec.js
- test/core/interface.spec.js
- test/core/name.js
- test/core/object.spec.js
- test/core/pin.spec.js
- test/core/stats.spec.js
- test/core/swarm.spec.js
- test/http-api/block.js
- test/http-api/bootstrap.js
- test/http-api/dns.js
- test/http-api/files.js
- test/http-api/id.js
- test/http-api/interface.js
- test/http-api/object.js
- test/http-api/version.js
- test/utils/interface-common-factory.js
- test/utils/on-and-off.js
This removes bootstrap nodes from all tests that don't need them. This should also help improve test determinism by preventing outside node influence. This also has the pleasant side effect of not having test nodes connect to our production bootstrap nodes.
A nice **future** update would be to set up specific bootstrap nodes when we do need to test bootstrapping so we're not hitting production at all.
> test: dont bootstrap unless it's needed

- RELEASE.md
js-ipfs has amazing release issues. Let's copy the release notes highlights to the github release description for posterity. 
Web UI now links to the release url for a given version of js-ipfs, so it's be great to put those notes there.
I've taken the liberty of copying it over for 0.33.0 https://github.com/ipfs/js-ipfs/releases/tag/v0.33.0
> chore: "copy release notes to github release" step

- test/core/init.spec.js
- test/core/interface.spec.js
- test/http-api/interface.js
The test for types also exists in interface-ipfs-core, which is the
central test repository for both js-ipfs and js-http-api tests.
Pulling in the test once from there is enough.
> refactor: use types test from interface-ipfs-core

- README.md
I stumbled upon this when working on https://github.com/ipfs-shipyard/ipfs-redux-bundle/pull/18.
The documentation stated that `ipfs.files.get` was an alias to `ipfs.get`. In the CLI and HTTP API it's the other way around: `ipfs.get` is an alias to `ipfs.files.get`, as you can see [here](https://github.com/ipfs/js-ipfs-api/blob/348a1443bd1069c86a4199670a454d2bfc1e8965/src/get.js#L8).
But on the Core API those alias don't exist, so we may as well remove them from the docs.
> docs: remove unexistent alias

- test/core/circuit-relay.js
The circuit relay test wasn't actually testing circuit relay, what fun! `ipfsd-ctl` still uses the experimental form of relay options, so it never gets turned on. I've switched relay over to be set via the libp2p options. I've also fixed the references to the nodes, they were wrong, which gave us the false sense of circuity-ness. 
Also, I moved the connect to `before` so  if the connect fails, we wont wait 80 seconds for the transfer to fail.
> test: make circuit relay test actually test circuit relay

- src/cli/commands/pin/add.js
- src/cli/commands/pin/ls.js
- src/cli/commands/pin/rm.js
`yargs-parser` adds inferred alias when using camelCase notation to command options. As a result of this, `pin` command was failing with `Unknown argument: ipfs-path`
I opened an issue [yargs/yargs-parser#151](https://github.com/yargs/yargs-parser/issues/151), as if it inferres other alias, it should be transparent to the users. This is a temporary fix for this issue, while it is not solved.
> fix: add dash case to pin cli

- package.json
- src/core/components/init.js
- src/core/components/name.js
- src/core/components/pre-start.js
- src/core/components/start.js
- src/core/index.js
- src/core/ipns/index.js
- src/core/ipns/path.js
- src/core/ipns/publisher.js
- src/core/ipns/republisher.js
- src/core/ipns/resolver.js
- src/core/ipns/routing/offline-datastore.js
- src/core/ipns/routing/utils.js
- test/cli/name.js
- test/core/name.js
- test/core/node.js
Currently, the `ipns` routing logic is inside the `publish`/ `resolve` logic.
Aiming to allow easily pluggable routings to `ipns`, I created this PR where the routing logic was moved from the `ipns.publish` / `ipns.resolve` to the instantiation of `ipns`. 
With this, we can add a `TieredDatastore` to `ipns` with an array of datastores. This array can have the node repo's datastore, the DHT, the [ipfs/js-datastore-pubsub](https://github.com/ipfs/js-datastore-pubsub), among others in the future. As a result, inside `ipns` logic, we will have `routing.put` and `routing.get` abstracted to all the enabled datastores.
The routing received by `ipns` will differ according to the node state. In the `init` and `pre-start` step, it will only receive the `OfflineDatastore` aka Repo's datastore. This …
> refactor: ipns routing logic moved to instantiation

- src/core/components/pubsub.js
- test/core/pubsub.spec.js
If pubsub is disabled there's no `pubsub` property on the libp2p node and we get the error "Cannot read property 'subscribe' of undefined". This is really confusing. This PR detects disabled pubsub and throws an error with a better message.
> fix: better error message when pubsub is not enabled

- README.md
- package.json
We need to start setting this so that users are ready for the breaking change coming with https://github.com/libp2p/js-libp2p-crypto/issues/130
This follows https://github.com/ipfs/community/pull/350
> chore: make it explicit that users should/must use node 10

- src/core/ipns/routing/utils.js
When the `base32` lib was changed, the new one uses `lowercase`, which brokes the interop with `go-ipfs` for the `IPNS working locally`
> fix: ipns datastore key

- README.md
- src/cli/bin.js
- src/cli/utils.js
- src/core/components/libp2p.js
- src/core/index.js
- src/http/index.js
- test/cli/daemon.js
- test/core/create-node.spec.js
- test/core/libp2p.spec.js
This PR resolves https://github.com/ipfs/js-ipfs/issues/1683. This PR is not merge-ready and I wanted to highlight some of the issues I've currently ran into.
`node src/cli/bin daemon --silent` does not disable printing "Swarming listening on..." and I'm not sure exactly why this option is not picked up by the core library. 
Also, when I use `print` as a property the peer address is printed on a new line. Not sure how to remedy this behavior but I did try using `process.stdout.write()`. https://stackoverflow.com/questions/6157497/node-js-printing-to-console-without-a-trailing-newline
However when I implemented `process.stdout.write()` the address came before the print statement `process.stdout.write()`
```
Initializing IPFS daemon... …
```
> feat: add slient option

- src/core/components/files-regular.js
- src/http/api/resources/files-regular.js
`/api/v0/cat` calls `ipfs.cat`, but `ipfs.cat` returns a buffer of file output. This changes `/api/v0/cat` to actually stream output by calling `ipfs.catPullStream` instead.
It uses `pull-pushable` in order to catch an initial error in the stream before it starts flowing and instead return a plain JSON response with an appropriate HTTP status.
This isn't ideal as it means there's no backpressure - if the consumer doesn't consume fast enough then data will start to get buffered into memory. However this is significantly better than buffering _everything_ into memory before replying.
This reduces memory usage and time to first byte significantly. e.g.
```sh
$ jsipfs object stat QmTtBrkubV9M914kgYrjTDCWTkN4TjnwYDJYb3dwK7ErXR
NumLinks: 22
BlockSize: 1110
LinksSize: 992
DataSize: 118 …
```
> fix: streaming cat over http api

- package.json
- src/core/components/files-regular/add-from-stream.js
- src/core/components/files-regular/add-from-url.js
- src/core/components/files-regular/index.js
- src/core/runtime/fetch-browser.js
- src/core/runtime/fetch-nodejs.js
- test/core/interface.spec.js
~~depends on https://github.com/ipfs/js-ipfs/pull/1772~~
> feat: add from url/stream

- package.json
- src/http/api/resources/files-regular.js
> test: tests and fixes for CID version agnostic read and write

- src/cli/commands/init.js
Prevents passing "" as the config option which then is validated and fails.
> fix: sharness tests

- src/http/api/routes/webui.js
Update to [Web UI v2.3.1](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.1) to pull in ipfs-geoip update and make geolocating peers work again.
License: MIT
> chore: update webui to v2.3.1

- package.json
- src/core/runtime/libp2p-browser.js
- src/core/runtime/libp2p-nodejs.js
This replaces ws-star with ws-star-multi transparently
resolves #1619
> feat: use ws-star-multi instead of ws-star

- examples/browser-video-streaming/README.md
- examples/browser-video-streaming/index.html
https://github.com/moshisushi/hlsjs-ipfs-loader/pull/7 was merged and released so this can now be fixed.
> docs: fix browser video streaming example

- src/core/components/dht.js
- src/core/components/is-online.js
- src/core/components/libp2p.js
- src/core/components/ping-pull-stream.js
- src/core/components/pubsub.js
- src/core/components/start.js
- src/core/components/stats.js
- src/core/components/stop.js
- src/core/components/swarm.js
- src/core/index.js
- test/core/libp2p.spec.js
This is an attempt on #1664–see discussion there. It may not be complete as I had trouble running unit tests (at master). I am posting this by way of abandoning it and welcome someone taking it over to finish it off.
I'm not sure this is 100% the right approach; in particular the `this.libp2p = undefined` in `core/index.js` is different to surrounding code. I don't know the project well enough to suggest an improvement here.
resolves https://github.com/ipfs/js-ipfs/issues/1664
> feat: make ipfs.libp2p the libp2p node rather than component

- src/core/runtime/dns-nodejs.js
- test/cli/dns.js
Closes #1842
This includes resolution of `_dnslink` subdomains outward and inward. If the supplied domain is `_dnslink.domain.com` and resolution fails then `domain.com` will be checked (inward checking). If the supplied domain is `domain.com` and the resolution fails then `_dnslink.domain.com` will be checked (outward checking).
Inward checking is not specified in the dnslink spec, but seems like it may be useful.
I added a test case for `_dnslink.ipfs.io` to ensure that inward resolution works. It probably makes sense to create a dns entry on the `ipfs.io` domain like `_dnslink.dnslink_test.ipfs.io` so a test can be added for `jsipfs dns dnslink_test.ipfs.io`.
The referenced issue contains commands with an example domain config for testing. I checked the go-ipfs test suite for guidance …
> feat: support _dnslink subdomain specified dnslinks

- src/cli/commands/cid.js
In the edge case where IPFS is a dependency of a project and the user attempts to use the IPFS CLI, the `cid-tool` will not be installed at `proj/node_modules/ipfs/node_modules/cid-tool` but will instead be flattened by npm and installed at `proj/node_modules/cid-tool`. i.e. next to `ipfs` in the dependency tree instead of a child of.
This PR fixes this situation by using `require.resolve` to get the path to the `cid-tool` instead of assuming where it is installed.
FYI I found this bug while using the `ipfs cid base32` command with a JS IPFS installed with [`iim`](https://github.com/alanshaw/iim). I was getting the error:
```
$ ipfs cid base32 QmRgXEDv6DL8uchf7h9j8hAGG8Fq5r1UZ6Jy3TQAPxEb76
ENOENT: no such file or directory, scandir …
```
> fix: path to cid-tool commands

- package.json
- src/http/index.js
Fixes #1853
(easy enough to do it as a drive-by, let me know if I should rebase this after #1844  is merged)
Before:
```
API listening on /ip4//tcp/
Gateway (read only) listening on /ip4//tcp/
Web UI available at http://::1:5002/webui
```
After:
```
API listening on /ip6/::1/tcp/5002/http
Gateway (read only) listening on /ip6/::1/tcp/9090/http
Web UI available at http://[::1]:5002/webui
```
> fix: print valid ipv6 multiaddrs in terminal

- README.md
Just a little thing I noticed when poking around in the docs
> docs: fix link to DHT spec

- .travis.yml
Until windows builds speed up, we can't use the cache because they fail when restoring the cache because "No output has been received in the last 10m0s".
This PR disables the Travis cache until windows perf improves on Travis.
> chore: disable travis cache temporarily

- README.md
> docs: note about required build tools for node-gyp

- package.json
- src/core/components/libp2p.js
- test/core/dht.spec.js
The `libp2p` defaults were not allowing the browser config to disable the `dht` for browser nodes. This PR fixes that issue
> fix: dht browser disabled

- package.json
- src/core/components/libp2p.js
Currently `js-ipfs` was having a bad time with CPU usage. 
In this context, we decided to go with a temporary change on `dht.put`, as well as disabling the `random-walk` discovery. We will benefit from discovery through the queries that we will be running for now. 
With this, we will get `js-ipfs` stable again, as well as have the DHT available and have time to implement a proper solution to solve this issue.
More details about the problem and discussion of the solution:
- [libp2p/js-libp2p-kad-dht#86](https://github.com/libp2p/js-libp2p-kad-dht/issues/86)
> chore: disable dht discovery

- test/core/pin.js
Pinning operations performed in parallel cause windows a bunch of problems documented in #1890
> fix: make clear pins function in tests serial

- README.md
- examples/browser-add-readable-stream/index.js
- examples/browser-readablestream/utils.js
- src/core/index.js
- test/core/exports.spec.js
- test/core/init.spec.js
- test/core/interface.spec.js
- test/http-api/interface.js
Allows users to access these additional types and utilities without having to create an instance first.
BREAKING CHANGE: `ipfs.util.isIPFS` and `ipfs.util.crypto` have moved to static exports and should be accessed via `const { isIPFS, crypto } = require('ipfs')`.
The modules available under `ipfs.types.*` have also become static exports.
refs https://github.com/ipfs/js-ipfs-http-client/issues/902
refs https://github.com/ipfs/js-ipfs-http-client/pull/951
> refactor: export types and utilities statically

- src/http/index.js
- test/cli/daemon.js
- test/gateway/index.js
- test/http-api/inject/bitswap.js
- test/http-api/inject/block.js
- test/http-api/inject/bootstrap.js
- test/http-api/inject/config.js
- test/http-api/inject/dht.js
- test/http-api/inject/dns.js
- test/http-api/inject/files.js
- test/http-api/inject/id.js
- test/http-api/inject/name.js
- test/http-api/inject/object.js
- test/http-api/inject/pin.js
- test/http-api/inject/ping.js
- test/http-api/inject/pubsub.js
- test/http-api/inject/resolve.js
- test/http-api/inject/version.js
resolves #1852
License: MIT
Signed-off-by: Grant Herman grantlouisherman041@gmail.com
> feat(issue-1852): now supports multiple api and gateways

- examples/running-multiple-nodes/README.md
Some simple instructions on how to run multiple JS IPFS nodes on the same computer via the CLI or programmatically.
resolves #1858
> docs: add docs on running multiple IPFS nodes

- src/cli/commands/daemon.js
- test/cli/daemon.js
Similar to what go-ipfs is now doing this prints the js-ipfs version, system arch/platform and Node.js version when a daemon is started. This should help with debugging.
Repo version is not yet included (but also unnecessary right now as we don't have repo migrations yet).
> feat: display version info when starting daemon

- src/core/components/libp2p.js
> fix: only dial to unconnected peers

- package.json
- src/core/components/files-regular/cat-pull-stream.js
The exporter was exporting the file, but the filter was filtering it out because the exported path includes only `file.txt` but the filter was expecting `path/file.txt`.
So when you cat `/ipfs/QmHash/file.txt` it worked, but when you cat `/ipfs/QmHash/path/file.txt` it did not because the exported file had path `file.txt` but the filter was looking for `path/file.txt`.
Depends on:
> fix: cat deeply nested file

- src/core/runtime/config-browser.js
- src/core/runtime/config-nodejs.js
I've observed that over ~600 peers the node becomes less stable, this lowers the default limits until we can address performance issues in libp2p.
> perf: lower connection manager limits

- src/http/api/routes/webui.js
2.4.1 left debug logging enabled. 2.4.3 fixes that.
https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.3
License: MIT
> chore: update webui to 2.4.3

- src/core/runtime/dns-nodejs.js
- test/cli/dns.js
resolves #1932 
`dns.requireTxt` throws 'ENODATA' if no txt records are found, so I included a condition to check for that error and check the `_dnslink.<domain>` so that subdomain is resolved correctly. 
Also added a few tests for checking if subdomain resolves correctly.
> fix: handle subdomains for ipfs.dns

- README.md
Following up on https://github.com/ipfs/js-ipfs/issues/1826#issuecomment-471920430
> docs: add DHT config documentation

- package.json
Pending resolution of https://github.com/pull-stream/stream-to-pull-stream/pull/16. The extra `destroy` function causes babel to throw after https://github.com/babel/babel/pull/9493 was merged and released.
> chore: update stream-to-pull-stream dependency

- README.md
- package.json
- src/core/components/libp2p.js
- test/cli/name.js
This updates to the latest libp2p version.
* DHT needed to be disabled by default in libp2p since libp2p doesn't actually come with the dht bundled, so it's turned on here by default.
* Relay should be enabled by default as it allows us to dial other relays. HOP is not turned on, so we don't act as a relay.
* ~~The IPNS test is added back in, which needs to be resolved for the 0.35 release~~
> chore: update libp2p

- src/cli/commands/daemon.js
- src/cli/commands/name/resolve.js
- test/cli/name.js
Boolean args were not being parsed as booleans.
> fix: name resolve arg parsing

- examples/browser-script-tag/index.html
It was using node.types.Buffer, this changes it to use `const { Buffer } = Ipfs`
Needed for 0.35 release: https://github.com/ipfs/js-ipfs/issues/1826
> Update browser script tag example

- src/core/index.js
It seems that browserify does not load the Buffer module unless we explicity assign it to a variable
> Force browserify to load Buffer module

- examples/exchange-files-in-browser/public/app.js
- examples/exchange-files-in-browser/public/index.html
As mentioned in issue #1632, currently, it is impossible to guess that there is the room feature on the exchange files example.
So, I added a textbox and a button which can be used for subscribing to a different room. Here's a small preview of the feature: 
closes #1632
> Show room feature in Exchange Files Example

- src/http/index.js
If any logger is turned on via `DEBUG`, such as `DEBUG=libp2p:switch` the api errors get logged to console, which makes viewing the actual logs I want rather annoying. 
Rather than checking the `DEBUG` value for http logging, this change has it check the status of the debug logger itself. Rather than defaulting to `error` level, it now defaults to `fatal`.
If you use `DEBUG=ipfs:http-api` or `DEBUG=ipfs:http-api:error`, you will still get the appropriate log level.
> fix: avoid logging http errors when its logger is not on

- README.md
- examples/custom-libp2p/index.js
- examples/custom-libp2p/package.json
- package.json
- src/core/components/libp2p.js
- src/core/runtime/libp2p-browser.js
- src/core/runtime/libp2p-nodejs.js
- test/core/libp2p.spec.js
Moves all peer discovery dialing logic to libp2p, which prevents dialing discovered nodes when we have enough peers.
> fix: use libp2p auto dial

- README.md
- package.json
- src/core/components/libp2p.js
- src/core/runtime/libp2p-browser.js
- src/core/runtime/libp2p-nodejs.js
- test/cli/daemon.js
- test/core/libp2p.spec.js
> fix: flakey windows test

- package.json
- src/core/runtime/libp2p-browser.js
- src/core/runtime/libp2p-nodejs.js
fix: update configurations for libp2p-switch
Libp2p 0.25 is out! This updates the dependency and adds configuration for libp2p switch to better help with connection creation and management.
> chore: update libp2p version

- .gitignore
- src/cli/commands/daemon.js
- src/cli/daemon.js
- src/cli/standalone-daemon.js
- src/http/index.js
- test/gateway/index.js
- test/http-api/inject/bitswap.js
- test/http-api/inject/block.js
- test/http-api/inject/bootstrap.js
- test/http-api/inject/config.js
- test/http-api/inject/dag.js
- test/http-api/inject/dht.js
- test/http-api/inject/dns.js
- test/http-api/inject/files.js
- test/http-api/inject/id.js
- test/http-api/inject/name.js
- test/http-api/inject/object.js
- test/http-api/inject/pin.js
- test/http-api/inject/ping.js
- test/http-api/inject/pubsub.js
- test/http-api/inject/resolve.js
- test/http-api/inject/version.js
- test/http-api/routes.js
> Part of an effort to run embedded js-ipfs in Brave :lion: https://github.com/ipfs-shipyard/ipfs-companion/issues/664  
This PR decouples HTTP servers from code `jsipfs daemon`.
Apart from cleanup, we need this to enable HTTP server in browser context with [`chrome.sockets`](https://github.com/ipfs-shipyard/ipfs-companion/issues/664).
**There are no functional changes.** I just moved non-HTTP code  to `src/cli/standalone-daemon.js`
In the past API was exposed via HTTP Server only when jsipfs daemon was run from the commandline, so src/http/index.js was also responsible for orchestration that is not related to HTTP itself. The coupling was quite bad: `HttpApi` basically decided on libp2p configuration: it enabled WebRTC if available, TCP transport, MulticastDNS etc.
This refactor moves …
> Decouple HTTP Servers from cli/commands/daemon

- CHANGELOG.md
- src/core/components/libp2p.js
- test/cli/dht.js
- test/core/dht.spec.js
- test/core/interface.spec.js
- test/core/name.js
- test/core/ping.spec.js
- test/http-api/inject/dht.js
- test/http-api/interface.js
> fix: really disable DHT

- package.json
- test/core/name-pubsub.js
- test/core/node.js
`name-pubsub` core tests were only running on `npm run test:node:core`. Moreover, this suite of tests was currently failing because the `publish` was happening before the subscription message was propagated to the other peer.
> chore: enable name-pubsub core test

- package.json
In the context of [libp2p/js-libp2p-webrtc-star#172](https://github.com/libp2p/js-libp2p-webrtc-star/issues/172) and #2008 `libp2p-webrtc-star` was updated with the newest version of hapi for security and performance reasons.
> chore: update webrtc star

- src/core/config.js
- test/core/create-node.spec.js
- test/core/init.spec.js
> add ipld to validation config of options

- src/cli/commands/name/publish.js
- src/core/components/name.js
In the context of [ipfs/js-ipfs#2046](https://github.com/ipfs/js-ipfs/issues/2046), the docs were updated to reflect the current state of the implementation.
> docs: ipns publish key

- README.md
> docs: remove the waffle graph and link

- examples/browser-mfs/package.json
- examples/browser-mfs/webpack.config.js
Switch to a different plugin which correctly compiles modern JS
> fix: browser-mfs example

- src/core/mfs-preload.js
Sometimes you don't want to preload everything, if your code is an example or a demo.  In that case you'd turn off preloading but `setImmediate` is [not a thing in browsers-other-than-IE](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) so pull in `async/set-immediate` instead
> fix: fix error when preloding is disabled in the browser

- src/http/api/resources/files-regular.js
- test/http-api/inject/files.js
At the moment this doesn't work in daemon mode..
Depends on ipfs/js-ipfs-http-client#1015
> fix: use trickle builder in daemon mode too

- src/cli/commands/swarm/addrs.js
- test/cli/swarm.js
Dont fail if decapsulation of ipfs fails. Go node addresses typically wont contain their peerid
Fixes https://github.com/ipfs/js-ipfs/issues/1575
> fix(cli): make swarm addrs more resilient

- package.json
- src/core/components/files-regular/add-pull-stream.js
> fix: file support when added as object

- src/core/ipns/routing/config.js
The ipns initialization is checking the wrong path to the libp2p's dht config flag, and as result it always boots in the offline state.
The following code should print the enabled routers:
```javascript
const config = {EXPERIMENTAL:{dht:true}, libp2p:{config:{dht:{enabled:true}}}}
const ipfs = new Ipfs(config)
ipfs.on('ready', () => console.log(ipfs._ipns.routing.stores))
```
With the patch the `ipfs.libp2p.dht` datastore is used.
> update ipns reference to libp2p dht config

- src/core/ipns/publisher.js
Printing raw buffers can end up outputting characters into the terminal that mess up the encoding for all subsequent lines, which is a pain when debugging things.
This change just encodes the buffer before printing to stop that from happening.
> chore: encode buffers before printing

- test/core/name.spec.js
A previous commit broke a test, as the `dht` was not properly enabled and the test is failing in master branch
> fix: failing test on config

- examples/exchange-files-in-browser/README.md
Fixes https://github.com/ipfs/js-ipfs/issues/2153
This example doesn't work except the case in localhost ( related to https://github.com/ipfs/js-ipfs/issues/2153)
This is known because of a restriction with WebCrypto (https://github.com/libp2p/js-libp2p-crypto/issues/105)
I add a explanation of a example's restriction to run
> docs: add a explanation of a example's restriction

- src/http/gateway/resources/gateway.js
- test/gateway/index.js
This cosmetic PR enables pretty URLs for directories with `index.html`
It follows what go-ipfs does: return implicit `index.html` without changing URL
**TL;DR:**
- BEFORE: http://127.0.0.1:9090/ipns/docs.ipfs.io → http://127.0.0.1:9090/ipns/docs.ipfs.io/index.html
- AFTER: http://127.0.0.1:9090/ipns/docs.ipfs.io → http://127.0.0.1:9090/ipns/docs.ipfs.io/ :ok_hand: 
It also makes logs more useful by showing both requested HTTP path and resolved IPFS one:
```
ipfs:http-gateway HTTP path  /ipns/tr.wikipedia-on-ipfs.org/ +0ms
ipfs:http-gateway IPFS path  /ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/index.html +0ms
```
> fix(gateway): keep pretty URL and return implicit index.html

- test/http-api/routes.js
- test/utils/clean.js
- test/utils/create-repo-nodejs.js
- test/utils/on-and-off.js
`rimraf.sync` does not retry when it encounters errors on windows. The async version retries a number of times before failing.
See https://github.com/isaacs/rimraf/issues/72 for context on why rimraf on windows might error.
Attempting to fix this error seeing quite often in CI now:
> fix: clean repo func on windows

- src/http/gateway/resources/gateway.js
- src/http/index.js
This PR supersedes https://github.com/ipfs/js-ipfs/pull/2227  as a fix for "random" daemon crashes with `NodeError: Cannot call write after a stream was destroyed` (details in https://github.com/libp2p/js-libp2p/issues/374).
**Steps to reproduce:** https://github.com/libp2p/js-libp2p/issues/374#issuecomment-508786129
@alanshaw confirmed the underlying error was not specific to `buffer-peek-stream`, but caused by the way Hapi handles pipelines with multiple PassThrough/Transform/pipe calls. We had two Transforms: one for content-type sniffing, and one for streaming compression.
Turns out go-ipfs does not compress anything by default, so we can remove PassThrough responsible for streaming of compressed payload and fix the issue while keeping optimization introduced by `buffer-peek-stream` …
> fix(gateway): disable compression

- examples/browser-video-streaming/index.html
This was waiting on an upstream PR https://github.com/moshisushi/hlsjs-ipfs-loader/pull/9
resolves https://github.com/ipfs/js-ipfs/issues/2255
> fix: browser video streaming example

- src/core/config.js
- test/core/config.spec.js
This PR adds `Addresses.Delegates` (added in  https://github.com/ipfs/js-ipfs/pull/2195) as an optional array to the schema used for config validation. 
It fixes the error below:
ps. I tested it in Brave (embedded js-ipfs + preload nodes) and delegated DHT queries produce expected responses :ok_hand: 
> ![2019-07-12--21-27-35](https://user-images.githubusercontent.com/157609/61153580-eeab8a00-a4eb-11e9-9152-0dcb51e2a67d.png)
> ![2019-07-12--21-27-52](https://user-images.githubusercontent.com/157609/61153579-eeab8a00-a4eb-11e9-8478-71f68d3330d4.png)
> fix: allow setting Addresses.Delegates

- src/core/config.js
- test/core/config.spec.js
Fixes validation for `config.Addresses.API` and `config.Addresses.Gateway` to allow array of multiaddr and adds missing `config.Swarm.ConnMgr` validation.
> fix: passed config validation

- README.md
- package.json
- src/core/index.js
- test/core/create-node.spec.js
This PR is rebased and extended from https://github.com/ipfs/js-ipfs/pull/1878. I've added tests for `node.ready` and `IPFS.create`, and updated the documentation.
**REVIEWERS**: Please be sure to review the README.md changes (github is not rendering the diff by default).
resolves https://github.com/ipfs/js-ipfs/issues/1762
closes #1878 
---
This change is **completely backwards compatible** with existing methods of creating a ready IPFS node. It does two things:
1. Adds functionalty for promised node creation and ready state
2. Alters documentation to recommend usage of promise based APIs over callback APIs
Now is the right time to add this functionality. This will get _existing_ users thinking about switching to promise based APIs and will onboard _new_ users to using the Promise based …
> feat: ready promise

- src/http/index.js
- test/gateway/index.js
This allows JSON content served from the gateway to be consumed without a CORS error.
I just tried upgrading from 0.34 to 0.36 and found this issue... adding this extra config seemed to fix it.
> Add CORS headers to gateway responses

- examples/README.md
Adding relevant ProtoSchool tutorials to this list so they'll be surfaced when people click "Tutorials" in the nav on js.ipfs.io.
> Add js-ipfs ProtoSchool tutorials

- README.md
I was having a look through the README and found several links pointing to the deprecated `http-api-spec` repo. Updated that to the docs website in the http api page
> docs: point to http api docs

- README.md
Currently setup as aliases for the preload nodes. Allows us to not break application code when these get moved to their own nodes.
> docs: update delegate node addrs

- README.md
The readme is incorrect for the EXPERIMENTAL config reference, this fixes it.
> docs: fix experimental readme config reference

- src/http/api/routes/pubsub.js
By default, node sockets automatically timeout after 2 minutes. This instructs Hapi to disable the timeout.
> fix: disable socket timeout for pubsub subscriptions

- test/cli/daemon.js
Observed to frequently fail on windows in CI due to hard coded ports in use.
> fix: use ephemeral ports in API/Gateway bind test

- README.md
To be consistent in naming (JS IPFS vs IPFS.js) and with the JS IPFS website https://js.ipfs.io
resolves https://github.com/ipfs/js-ipfs/issues/2321
> refactor: update logo on README

- package.json
- src/core/components/swarm.js
- test/core/interface.spec.js
- test/http-api/interface.js
go-ipfs returns "n/a" when latency is unknown. This change restores compatibility.
Depends on:
> fix: value when latency unknown

- test/cli/dht.js
- test/core/dht.spec.js
- test/core/interface.spec.js
- test/core/name.spec.js
- test/core/ping.spec.js
- test/http-api/inject/dht.js
- test/http-api/interface.js
To find all of those comments run:
```console
$ grep DHT test -R |grep TODO
test/cli/dht.js:// TODO: unskip when DHT is enabled: https://github.com/ipfs/js-ipfs/pull/1994
test/core/ping.spec.js:  // TODO: unskip when DHT is enabled: https://github.com/ipfs/js-ipfs/pull/1994
test/core/interface.spec.js:      reason: 'TODO: unskip when DHT is enabled: https://github.com/ipfs/js-ipfs/pull/1994'
test/core/dht.spec.js:// TODO: unskip when DHT is enabled: https://github.com/ipfs/js-ipfs/pull/1994
test/core/name.spec.js:  // TODO: unskip when DHT is enabled: https://github.com/ipfs/js-ipfs/pull/1994
test/http-api/inject/dht.js:  // TODO: unskip when DHT is enabled: https://github.com/ipfs/js-ipfs/pull/1994
test/http-api/interface.js:      reason: 'TODO: unskip when DHT is enabled: …
```
> chore: update comment about skipping the DHT test

- package.json
- src/core/preload.js
This PR switches to latest `multiaddr-to-uri` and removes code that is no longer needed.
Closes #2333 as a side-effect :ok_hand: 
Note: `multiaddr-to-uri` assumes http by default now, which should make it easier and more robust to configure: https://github.com/multiformats/js-multiaddr-to-uri/pull/7
> fix: preload addreses with trailing slash (new multiaddr-to-uri)

- src/core/components/dns.js
- test/http-api/inject/dns.js
> This is js-ipfs version of a change that already landed in go-ipfs: https://github.com/ipfs/go-ipfs/pull/6448
The `.eth` TLD is not recognised by mainstream DNS,
however ENS provides DNS compatibility service at `.eth.link`
This change enables resolution of ENS names ending with `.eth`
on systems that  have regular DNS set up:
```console
$ jsipfs dns ipfs.enstest.eth
/ipfs/QmRAQB6YaCyidP37UdDnjFY5vQuiBrcqdyoW1CuDgwxkD4
$ jsipfs name resolve /ipns/ipfs.enstest.eth.link
/ipfs/QmRAQB6YaCyidP37UdDnjFY5vQuiBrcqdyoW1CuDgwxkD4
```
cc @mcdee, @parkan
> feat: resolution of .eth names via .eth.link

- .aegir.js
- .travis.yml
- package.json
- src/core/components/dag.js
- src/core/components/pin.js
Given a `CID`, the `dag. _getRecursive` method returns a list of all descendents of the node with the passed `CID`.  This can cause enormous memory usage when importing large datasets.
Where this method is invoked the results are either a) disgarded or b) used to calculate the `CID`s of the nodes which is then bad for memory *and* CPU usage.
This PR removes the buffering and `CID` recalculating for a nice speedup when adding large datasets.
In my (non-representative, may need all the other unfinished async/iterator stuff) testing, importing folder of 4MB files totalling about 5GB files with content from `/dev/urandom` into a fresh repo with a daemon running in the background is now:
```
go-ipfs
real	3m43.741s
user	0m31.955s
sys	0m31.959s
```
```
js-ipfs
real	3m40.725s
user	0m7.352s
sys …
```
> fix: Do not load all of a DAG into memory when pinning

- test/utils/interface-common-factory.js
Previously the spawnOptions defaults were not being included
if a test specified them. This would result in some tests dialing
out to the Bootstrap nodes, or using mdns when not desired. This
resolves that by using 'merge-options' to include defaults.
> test: merge util factory spawn options

- src/core/components/files-mfs.js
- src/core/preload.js
- test/core/preload.spec.js
~~@achingbrain please could you verify these are the methods that accept IPFS paths? Also, do they accept CID instances or CID strings or "cid paths" as I've allowed here or is it _only_ IPFS paths?~~ Verified myself - it is IPFS paths (Strings) and CID _instances_.
TODO:
fixes https://github.com/ipfs/js-ipfs/issues/2335
> fix: enable preload on MFS commands that accept IPFS paths

- src/cli/bin.js
`origin` can be `undefined` as well as [`uncaughtException` or `unhandledRejection`](https://nodejs.org/api/process.html#process_event_uncaughtexception)
It'd be nice to see the stack traces when that's the case.
This can happen when you've done silly stuff like tried to `require` something that doesn't exist, etc.
> chore: show stack traces on uncaught errors

- test/http-api/inject/dns.js
From IRC:
> lidel: Moving it to permanent infrastructure, thats why its down atm.
Lets skip this (on failure) until service level improves.
> chore: skip ENS test if failing

- .travis.yml
- src/cli/commands/add.js
- src/http/api/resources/files-regular.js
Pulled out from #2379
Depends on:
> feat: allow controlling preload behaviour from cli

- src/cli/commands/add.js
- test/cli/files.js
Pulled out of #2379.
We used to buffer all hashes of added files and sort them before outputting to the terminal, I think this might be because the `glob` module does not return stable results.  This gives a poor user experience as you see nothing then everything, compared to `go-ipfs` which prints out the hashes as they become available.  The tradeoff is the order might be slightly different between invocations, though the hashes are always the same as we sort DAGNode links before serializing so it doesn't matter what order you import them in.
Bleugh.
Anyway - this will be addressed as part of #2379 so the changes to the files test should only be temporary.
> fix: make progress bar work again when adding files

- test/core/interface.spec.js
Due to an issue with the gateways, dns tests were failing and were skipped on [ipfs/js-ipfs#2298](https://github.com/ipfs/js-ipfs/pull/2298).
This PR intends to unskip them once the gateways are working as expected
closes #2416
> chore: unskip dns tests

- test/cli/files.js
- test/cli/object.js
- test/core/bitswap.spec.js
- test/http-api/files.js
- test/http-api/inject/dag.js
This PR:
- replaces Math.random() with [hat()](https://www.npmjs.com/package/hat)
- increases timeout of bitswap tests that fail often
CI often fails in tests that use Math.random.
I suspect Math.random is not random enough on some platforms.
Let's see if this PR pass without a problem
> fix(tests): remove Math.random from  tests

- .aegir.js
- .travis.yml
- npm-shrinkwrap.json
- package.json
- src/core/components/libp2p.js
- yarn.lock
Runs interop tests on release branch.  Sort of like a sneak preview of #2440 
The interop build passes, but for some reason Windows is stalling after the build passes causing the whole thing to be killed.  Gah.
> V0.38.x run interop

- doc/RELEASE_ISSUE_TEMPLATE.md
Documents aegir commands to create and update release candidates.
Added to aegir in ipfs/aegir#419 and ipfs/aegir#421
> doc: add aegir commands to release template

- .aegir.js
- .travis.yml
- package.json
- src/core/components/libp2p.js
This will need updating to only run on master & add `npx aegir update-last-successful-build` from https://github.com/ipfs/aegir/pull/419 as a post-build step
> chore: run interop tests as part of the build

- package.json
Adds fix for `ky` not consuming body of large requests.
> chore: upgrade ipfs http client to fix orbit-db tests

- doc/RELEASE_ISSUE_TEMPLATE.md
* Do the doc update before cutting a release branch otherwise it's just another RC release to test against at the end of the process
* Run tests against popular third party repos as well as our own
* Documents commands for updating lockfiles (should be run on CI, ideally)
* Documents commands for performing release with verified dependencies and reintegrating release branch to master
> docs: update RELEASE_TEMPLATE.md

- .travis.yml
Currently Travis is set to build PRs and all branches. We need to build PRs to test code from forked repos and we also want CI to run on changes to master & `release/*` branches.
However if we push a branch to ipfs/js-ipfs and create a PR it gets built twice - once for the PR and once for the branch, as you can see in the checks section of PRs:
If I've read [the docs](https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches) correctly, the change in this PR should only run the build on master and release branches - it should still run on PRs.
> chore: only run build on PRs, master and releases

- src/cli/bin.js
Sometimes you've done something silly like required a module that isn't installed or called a method that isn't a property of an object in which case `argv` won't have a value, causing an unrelated error to appear.
This PR just makes sure `argv` has a value before trying to access `argv.getIpfs`
> fix: only try to get ipfs if argv is present

- src/core/components/files-regular/refs-pull-stream.js
- src/core/components/pin/gc.js
- src/core/components/pin/pin-manager.js
- src/core/ipns/publisher.js
- src/core/ipns/resolver.js
- test/core/gc.spec.js
- test/core/name.spec.js
This PR replaces hardcoded strings with actual error codes from `interface-datastore` (such as `Errors.notFoundError`) making it much safer going forward.
@hugomrdias the new datastore for browser should return code from `interface-datastore` too, eg:
```js
const {  Errors } = require('interface-datastore')
if (!value) {
return Errors.notFoundError()
}
```
> refactor: reuse error codes from interface-datastore

- test/utils/on-and-off.js
Set locale to en_US.UTF-8 during CLI testing to stop tests from failing
in non English locales.
License: MIT
Signed-off-by: Vincent Martin <vince@finalatomicbuster.net>
> fix(cli): change locale to en_US.UTF-8 during CLI testing

- package.json
- src/cli/commands/block/rm.js
- src/core/components/block.js
- src/http/api/resources/block.js
- src/http/api/routes/block.js
- src/http/utils/stream-response.js
- test/cli/block.js
- test/core/interface.spec.js
- test/http-api/interface.js
Also, validate that a block is not pinned before removing it.
Might, uh, might want to do that.
> feat: support block.rm over http api

- src/cli/commands/add.js
- src/core/components/files-regular/add-async-iterator.js
- src/http/api/resources/files-regular.js
The interface spec says you should pass a `trickle` boolean to `ipfs.add` to get a trickle DAG, this PR makes us actually do that instead of passing `strategy: 'whatever'`.
> fix: choose import strategy in ipfs.add

- test/http-api/inject/files.js
I think this can be enabled now.
> test: enable skipped base64 encoding test

- README.md
- docs/config.md
- src/cli/commands/daemon.js
- src/cli/daemon.js
- src/core/components/config.js
- src/core/config.js
- test/cli/daemon.js
- test/core/config.spec.js
- test/core/init.spec.js
Add profiles docs just like https://raw.githubusercontent.com/ipfs/go-ipfs/master/docs/config.md, support in the init options validation and tests.
Add support for ipfs daemon --init-profile (ignore the commit message)
> fix: add profiles docs, support in validation and tests

- src/cli/commands/init.js
Change emptyRepo and privateKey to kebab-case, while still supporting camelCase.
This make the cli output look like go-ipfs to avoid confusion.
> fix: make init options look like go-ipfs

- package.json
- src/cli/commands/dag/put.js
- src/cli/commands/dag/resolve.js
- src/core/components/dag.js
- test/cli/commands.js
- test/cli/daemon.js
- test/cli/dag.js
- test/cli/files.js
- test/cli/name-pubsub.js
- test/cli/swarm.js
- test/utils/ipfs-exec.js
Also allows passing input to `ipfs-exec` to simulate piping in cli tests.
> feat: add mssing `dag put` and `dag resolve` cli commands

- package.json
These are not used and get put into the `docs` directory which is no longer ignored so we end up with a dirty repo on release.
refs https://github.com/ipfs/js-ipfs/pull/2502#issuecomment-542711961
> chore: do not generate aegir docs on release

- README.md
We are missing documentation for the `offline` option, as discussed in [ipfs/go-ipfs#3860#issuecomment-547094569](https://github.com/ipfs/go-ipfs/issues/3860#issuecomment-547094569)
> docs: offline option

- package.json
- src/core/components/name.js
- src/core/ipns/resolver.js
- test/core/name.spec.js
- test/http-api/inject/name.js
We want root identifiers of content paths to be usable in case-insensitive contexts such as [subdomains](https://github.com/ipfs/in-web-browsers/issues/89). 
While we can use [CIDv1 encoded in Base32](https://github.com/ipfs/ipfs/issues/337) in `/ipfs/` namespace, Identifiers in `/ipns/` are still hardcoded to Base58btc,
Libp2p approved [RFC 0001: Text Peer Ids as CIDs](https://github.com/libp2p/specs/blob/master/RFC/0001-text-peerid-cid.md) recently, and we need to implement it in js-ipfs.
This PR implements `Stage 1: Parse CIDs as peer ID` from https://github.com/libp2p/specs/issues/216. It makes `/ipns/{cidv1}` work without waiting for `PeerId.createFromCID` from  https://github.com/libp2p/js-peer-id/pull/105, which means we can merge this before async refactor is done. 
**This PR does …
> feat: js-ipfs support of CIDs in /ipns/ content paths

- package.json
- src/core/components/dht.js
Solving https://github.com/ipfs/js-ipfs/issues/2573
ipfs.dht.provide() now accepts strings as well as CID objects, and attempts to convert them to the latter.
> dht.provide() should accept string keys (#2573)

- .travis.yml
- examples/browser-browserify/package.json
- examples/circuit-relaying/package.json
- examples/circuit-relaying/test.js
- examples/custom-ipfs-repo/index.js
- examples/custom-ipfs-repo/package.json
- examples/custom-ipfs-repo/test.js
- examples/custom-libp2p/package.json
- examples/custom-libp2p/test.js
- examples/exchange-files-in-browser/package.json
- examples/exchange-files-in-browser/test.js
- examples/explore-ethereum-blockchain/test.js
- examples/package.json
- examples/run-in-electron/main.js
- examples/running-multiple-nodes/test.js
- examples/test-all.js
- examples/test.js
- examples/traverse-ipld-graphs/test.js
- examples/utils.js
We run automated tests of IPFS examples & external repos on our release branches, but there's no good reason not to run them on every PR instead to give people early warning of breakages.
This PR changes the `.travis.yml` file to run all tests on every submitted PR.
> test: run examples/externals on PRs too

- src/core/components/libp2p.js
- src/core/runtime/libp2p-browser.js
- src/core/runtime/libp2p-nodejs.js
- test/core/libp2p.spec.js
This allows bundle creation by merging/overriding option defaults instead of creating them in their entirety from scratch. This is for convenience.
The `libp2pOptions` passed to the bundle function include any options defined in the required runtime files (for Node.js/browser config).
To allow this, there is a slight change to `runtime/libp2p-nodejs.js` and `runtime/libp2p-browser.js` to return their options instead of a libp2p instance. This actually removes some repeated boilerplate.
e.g.
```js
const ipfs = await IPFS.create({
libp2p: ({ libp2pOptions, peerInfo, ...rest }) => {
// Merge, extend, override etc. etc.
libp2pOptions.transports.push(...)
return new Libp2p(libp2pOptions)
}
})
```
resolves #2579
> feat: pass libp2pOptions to the bundle function

- README.md
Users will be primarily interested in knowing the state of the master branch rather than the "last run from a PR". Keeping that badge green will give a lot of confidence to new users when opening the repo and seeing that we don't break master.
> chore: travis ci badge point to master branch

- .travis.yml
> Please note that as of July 2019, npm is cached by default on Travis CI
https://docs.travis-ci.com/user/caching/#npm-cache
> chore: try caching on all environments again

- src/http/api/resources/repo.js
Should be `Error` not `Err`. https://docs.ipfs.io/reference/api/http/#api-v0-repo-gc
> fix: repo gc error key name

- package.json
- src/cli/commands/bitswap/stat.js
- test/cli/bitswap.js
This PR adds `--human` flag to `bitswap stat` command.
**Usage:** 
```sh
> jsipfs bitswap stat --human
```
**Output:**
```sh
bitswap status
provides buffer: 0
blocks received: 0
blocks sent: 0
data received: 0 B
data sent: 0 B
dup blocks received: 0
dup data received: 0 B
wantlist [2 keys]
partners [0]
```
This PR supersedes https://github.com/ipfs/js-ipfs/pull/2608.
> feat: add bitswap stat cli human option

- COPYRIGHT
- LICENSE-APACHE
- LICENSE-MIT
- package.json
Updated the license as mentioned in issue #2552. This closes #2552
> License update to dual MIT and Apache 2

- src/core/components/bootstrap.js
- test/cli/bootstrap.js
- test/http-api/inject/bootstrap.js
This PR fixes the return value of `bootstrap.rm()` when `all` option is set.
i.e.:
```ipfs.bootstrap.rm({ all: true })``` was returning `{ Peers: [] }`
But it should return `{ Peers: [address1, address2, ...] }` instead.
> fix: bootstrap rm return value when all option is set

- package.json
- src/cli/commands/repo/stat.js
- src/core/components/repo.js
- src/http/api/resources/repo.js
- test/cli/repo.js
This PR adds `--human` flag to `repo stat` command.
**Usage:** 
```sh
> jsipfs repo stat --human
```
**Output:**
```sh
NumObjects: 16
RepoSize: 30.1 KB
StorageMax: 9.01 PB
RepoPath: /var/folders/l1/(...)
Version: 7
```
This PR supersedes https://github.com/ipfs/js-ipfs/pull/2592. 
Reason: https://github.com/ipfs/js-ipfs-repo/pull/213#issuecomment-555488344.
⚠️This PR needs the following PR merged and released before this one can be:
> feat: add human flag to repo stat cli command

- package.json
- src/cli/commands/dag/put.js
- test/cli/dag.js
https://github.com/ipld/js-ipld-dag-cbor/issues/84#issuecomment-558140717
Depends on:
> fix: support legacy links in cbor data

- package.json
Fixes #2629 and restores access to pre-0.39.0 repos though any repos created with 0.39.0 will not be accessible by default.
Should be released in a patch release to `v0.39.0`.
> fix: requires the ipfs-repo version with a fix for #2629 at a minimum

- package.json
Was causing 2 versions of node-forge to be included in the bundle.
> chore: update libp2p-keychain dependency

- .aegir.js
- package.json
- src/core/components/bootstrap.js
- test/cli/bootstrap.js
- test/core/interface.spec.js
- test/http-api/inject/bootstrap.js
- test/http-api/interface.js
- test/utils/interface-common-factory.js
This PR allows `interface-core` tests to create and spawn nodes asynchronously.
Related to:
https://github.com/ipfs/interface-js-ipfs-core/pull/562
> chore: change interface tests to async node creation

- .aegir.js
- src/cli/commands/add.js
- test/cli/files.js
- test/fixtures/test-data/recursive-get-dir/.hidden.txt
This PR adds `--hidden` flag to CLI's `add` command.
Closes #1917.
> feat: add --hidden flag to cli add command

- test/http-api/interface.js
This PR unskips `should respect timeout option` test of `object.stat()` over http-api as timeout is currently implemented as you can see [here](https://github.com/ipfs/js-ipfs-http-client/blob/master/src/object/stat.js#L22-L27). There's no need to be skipped.
> fix: skipped object.stat test

- test/core/interface.spec.js
`bitswap.wantlist()` doesn't need to be skipped anymore in the browser. The problem was solved on https://github.com/ipfs/interface-js-ipfs-core/pull/564 by [this commit](https://github.com/ipfs/interface-js-ipfs-core/pull/564/commits/6881e7274fb8c0e91eceeeaf862d7de3dffc4281).
> fix: unskip bitswap.wantlist test

- src/core/components/id.js
- src/core/components/index.js
- src/core/components/init.js
- src/core/components/start.js
- src/core/components/stop.js
⚠️ Note: this will be merged into https://github.com/ipfs/js-ipfs/pull/2547
> refactor: convert id API to async/await

- src/http/api/routes/webui.js
Ref: [#2697 ]
This PR fixes the issue of being redirected to `http://undefined:9090/ipfs/...` after hitting webui URL.
License: MIT
Signed-off-by: ggarri <gabriel@lightstreams.io>
> fix: correct redirect when it loads webui #2697

- .travis.yml
- src/http/gateway/resources/gateway.js
- test/gateway/index.js
This PR introduces hardening proposed in https://github.com/ipfs/go-ipfs/issues/4025#issuecomment-342250616
go-ipfs version: https://github.com/ipfs/go-ipfs/pull/6801
> fix: limit SW registration to content root

- .travis.yml
We need to publish an rc for people to use to refactor their code to use the new API.
The `aegir` release commands require the `last-successful` build to have run in order to update the last known good build branch.
That build will not run until the external builds pass but we can't make them pass until they can be refactored to use the new API for which we need an rc.
The change to the `.travis.yml` in this PR allows the overall build to pass even though the external module builds are faiilng.
Depends on:
> chore: allow externals to fail

- src/core/components/id.js
- src/core/components/start.js
- test/core/id.spec.js
The user may start the node with no swarm addresses to speed up startup times - if they then use libp2p to listen on new transports we should return the addresses currently being listened on instead of those configured at startup.
refs #2508
> fix: report correct swarm addresses after listening on new addrs

- README.md
[`libp2p-websocket-star`](https://github.com/libp2p/js-libp2p-websocket-star/issues/57) has a security vulnerability and was not converted in the refactor. This PR removes the `libp2p-websocket-star` information until https://github.com/libp2p/js-libp2p-stardust/pull/14 lands and we can recommend using it instead.
refs https://github.com/ipfs/js-ipfs/pull/2600
> docs: remove websocket-star docs

- package.json
- src/core/components/block/put.js
resolves https://github.com/ipfs/js-ipfs/issues/2751
Conform to [documented block.put API](https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/BLOCK.md#blockput).
Depends on:
> fix: block put with CID as string

- package.json
Fixes a problem where `--preserve-mtime` was not working.
> chore(package): update ipfs-utils to version 0.7.2

- .travis.yml
- docs/RELEASE_ISSUE_TEMPLATE.md
It does not depend on IPFS or the HTTP client.
https://github.com/ipfs-shipyard/ipfs-pubsub-room
Looks like this was a recent change https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/73
> chore: remove ipfs-pubsub-room from CI

- README.md
Adds a temporary note at the top of the README to point people at the release notes and migration guide for the 0.41 release.
> docs: add temporary upgrade note

- test/core/bitswap.spec.js
- test/core/name.spec.js
These are async methods and can result in unhandledPromiseRejection events :(
> fix: await on things that need awaiting on

- examples/custom-libp2p/index.js
- src/core/components/start.js
Since https://github.com/libp2p/js-libp2p/pull/558 js-libp2p now requires peer ids to be part of dialled multiaddrs.
Previously a user was able to copy/paste swarm addresses printed as part of the daemon starting up but now they can't because the peer id is not included in the console output.
This PR prints the node's peer id as part of the swarm address to let people continue doing this and fixes the custom-libp2p example.
> fix: print peer id in swarm addresses on startup

- .travis.yml
> Parent: https://github.com/ipfs-shipyard/ipfs-webui/issues/1164
> go-ipfs counterpart: https://github.com/ipfs/go-ipfs/pull/6825
This PR adds TravisCI config for running ipfs-webui's end to end tests against js-ipfs from  this repo.
It does not increase CI time, as its runs in parallel to other tests, and those take much longer:
> ![time](https://user-images.githubusercontent.com/157609/72625409-09eacc80-3949-11ea-978c-ccf05a5371cc.png)
**Note:** It uses `aegir test-external` which runs tests twice: first time against release version of js-ipfs, and if that is green, then against version from this repo. If not, we exit without error. That way we avoid breaking the js-ipfs build if upstream ipfs-webui is not green. 
- ipfs-webui switched  to [ipfsd-ctl …
> test: E2E tests against ipfs-webui HEAD

- README.md
We should get this and https://github.com/ipfs/aegir/pull/518 out in a patch release ASAP.
> fix: remove events and callbacks info from the README

- .travis.yml
- package.json
I've generalised the aegir test-externals command so it's not js-ipfs specific any more and can be used by our other projects, hopefully by aegir itself too to catch breakage.  This change updates our invocation of the command.
> chore: update testing externals

- packages/ipfs-http-client/README.md
This PR:
- Adds download counts
- Recommend jsdelivr (faster CDN) and gives us the download counts
Follows the one in js-ipfs https://github.com/ipfs/js-ipfs/pull/2826
> docs: add download counts to http-api-client. recommend jsdelivr

- examples/browser-browserify/README.md
- examples/browser-mfs/README.md
- examples/browser-parceljs/README.md
- examples/browser-readablestream/README.md
- examples/browser-vue/README.md
- examples/browser-webpack/README.md
- examples/circuit-relaying/README.md
- examples/custom-ipfs-repo/README.md
- examples/custom-libp2p/README.md
- examples/exchange-files-in-browser/README.md
- examples/run-in-electron/README.md
With the project structure updated to lerna, the `examples` do not need to be installed, as the dependencies get installed when the main project is installed.
This PR removed the `npm install` instruction from all the example `README` files that had it.
> docs: examples do not need to be installed

- examples/browser-script-tag/README.md
- examples/browser-video-streaming/README.md
- examples/browser-video-streaming/index.html
- packages/ipfs-http-client/README.md
- packages/ipfs/CHANGELOG.md
- packages/ipfs/README.md
This PR:
- Adds download counts
- Recommend jsdelivr (faster CDN) and gives us the download counts
> docs: recommend jsdelivr to users and add download counts to the README

- examples/exchange-files-in-browser/package.json
- examples/exchange-files-in-browser/public/app.js
- examples/exchange-files-in-browser/test.js
The test for this example did not go as far as downloading the file and asserting the contents are correct - that part had not been refactored to be async/await happy so wasn't working.
I've expanded the test to perform the download too.
> fix: fix exchange in files example

- examples/browser-video-streaming/index.html
Otherwise the test times out. We have to specify the dist file in the url too, otherwise the test times out, not 100% sure why.
Follows on from #2826
> fix: reinstate hlsjs-ipfs-loader dep for video streaming example

- .travis.yml
Should make PR builds much faster. Might have to be a bit smarter about coverage reports over time though.
> chore: only run jobs in packages that have changed since master

- packages/ipfs/src/cli/index.js
- packages/ipfs/test/cli/daemon.js
Since yargs v14, using `.parse(command)` with an unknown command causes an [error to be thrown](https://github.com/yargs/yargs/issues/1419) instead of the help text being printed.
One solution is to use `.argv` instead of `.parse(command)` but we use the `.parse(command)` variant to enable testing as the passed command is evaluated rather than `process.argv`, which is what happens when you call `.argv`.
Instead if we detect a error caused by an unknown command, use the parser to show help instead of version of yargs that had `.parse(command)` called on it.
> fix: error when command is unknown

- packages/interface-ipfs-core/SPEC/FILES.md
https://github.com/ipfs/js-ipfs/issues/2933
> fix: avoid throw error when use readme code

- packages/interface-ipfs-core/SPEC/FILES.md
fixes a small typo in the example here:  https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/SPEC/FILES.md#importing-a-file-from-a-url
Closes https://github.com/ipfs/js-ipfs/issues/2941
> docs: fix urlSource example typo

- packages/interface-ipfs-core/README.md
found some bad links while browsing the ipfs-core-interface documentation.
all are part of the api section of the readme here:
https://github.com/ipfs/js-ipfs/tree/master/packages/interface-ipfs-core#api
pr changes:
- links are changed to relative links `'/' -> './'`
- add file extension to repo api doc `'REPO' -> 'REPO.md'`
- fix typo for bootstrap api doc `'BOOSTRAP' -> 'BOOTSTRAP'`
> docs: fix links to core api spec/documentation

- packages/ipfs/src/cli/commands/add.js
- packages/ipfs/test/cli/files-regular.js
Converts the stdin stream to a async iterator of one file and tags that file with the mtime and
mode.
fixes #2763
> fix: tag stdin with mtime and mode when piping to cli 'add'

- packages/ipfs-http-client/src/lib/to-url-search-params.js
- packages/ipfs/src/cli/commands/add.js
- packages/ipfs/test/cli/files-regular.js
So we don't send invalid args over http.  Also removes `nonatomic` option, not sure how that got in there.
> fix: add default args for ipfs.add

- packages/ipfs/src/http/index.js
When the `IPFS_MONITORING` env var is set, we use prometheus to collect resource usage stats.  We only need to set it up in one place though.
Fixes #2019
> fix: only start prometheus metrics in one place

- packages/ipfs/src/core/components/start.js
When we add the own peer id to a multiaddr, we should verify if it already has it, or if it is an address of `circuit-relay` / `stardust`. Otherwise, we might end up with multiaddrs like:  `/ip4/127.0.0.1/tcp/5892/ws/p2p/PEER_ID/p2p/PEER_ID`
> fix: multiaddr validation to add peer id for listening

- packages/ipfs/src/cli/commands/add.js
- packages/ipfs/src/cli/commands/files/mkdir.js
- packages/ipfs/src/cli/commands/files/touch.js
- packages/ipfs/src/cli/commands/files/write.js
- packages/ipfs/src/cli/utils.js
- packages/ipfs/test/cli/files/mkdir.js
- packages/ipfs/test/cli/files/touch.js
- packages/ipfs/test/cli/files/write.js
These are supported in the core and the http interface but got missed off the cli.
Fixes #2803
> feat: support mtime-nsecs in mfs cli

- packages/ipfs/src/cli/daemon.js
> fix: use correct name for webrtc transport config

- examples/ipfs-101/README.md
Old example was printing an AsyncGenerator object to the console
Updated code comes straight from https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#cat
> docs: fix ipfs.cat example

- packages/ipfs-http-client/src/dht/find-peer.js
It doesn't appear to be [documented](https://docs.ipfs.io/reference/api/http/#response-30), but `POST /api/v0/dht/findpeer` can return multiple results, so treat it as `ndjson`.
Otherwise we see these sorts of test failures:
```
1) DelegatedPeerRouting
findPeers
should be able to find peers via the delegate with a peer id string:
FetchError: invalid json response body at http://127.0.0.1:42421/api/v0/dht/findpeer?search-params=%5Bobject+Object%5D&arg=QmcvRwsBkiEfLFPC6NAXmbpt1f9oKDT9dmmgAcEsGd9ZuW reason: Unexpected token { in JSON at position 93
```
> fix: dht.findPeer API endpoint returns ndjson

- packages/ipfs/src/core/components/index.js
- packages/ipfs/src/core/components/libp2p.js
- packages/ipfs/src/core/components/start.js
- packages/ipfs/test/core/dht.spec.js
When the API Manager code came in, the DHT component seem to have been missed from the `start` component, this PR re-adds it.
> fix: regression that dht could not be enabled through conf

- packages/interface-ipfs-core/src/refs.js
Minor changes to refs to stop using `ipfs.add` and `ipfs.object.put` in favor of `ipfs.block.put` with test-local formatting. Tested against `go-ipfs-0.4.23` the CIDs do not change. This is result of discussions at https://github.com/ipfs-rust/rust-ipfs/issues/92#issuecomment-602686606 and at least another PR for `refs-local.js` should be coming later.
Sorry for the semicolons, I don't know the semicolon insertion rules by heart :)
> Refactor refs tests

- packages/interface-ipfs-core/src/block/rm.js
This PR removes the `expect(localRefsAfterRemove).to.have.property('length').that.is.greaterThan(0)` from line 42. The rationale here is that the `rs-ipfs` nodes start with a completely empty blockstore. Once only block added is removed, then it drops back to one again.
This was imo the least obtrusive move I could make with the tests, the alternative could be to seed a cid2 within the test to ensure it was always `greaterThanZero`
> chore: remove second greaterThanZero check from block.rm test

- packages/ipfs/src/core/ipns/routing/config.js
- packages/ipfs/test/core/name.spec.js
interface was updated here https://github.com/libp2p/js-libp2p/pull/480
> fix: correct dht reference in ipns routing

- packages/ipfs-http-client/src/dht/find-peer.js
- packages/ipfs-http-client/src/dht/find-provs.js
- packages/ipfs-http-client/src/dht/get.js
- packages/ipfs-http-client/src/dht/provide.js
- packages/ipfs-http-client/src/dht/put.js
- packages/ipfs-http-client/src/dht/query.js
- packages/ipfs-http-client/src/dht/response-types.js
Response streams from DHT operations contain lots of message types, one of which is 'Error', but they are emitted for all sorts of reasons, failing to dial peers, etc and valid responses can arrive after several errors.
The change here is to ignore error messages sent by the remote node as they do not indicate that the request has failed.
Fixes #2991
> fix: do not abort dht operation on error responses

- examples/browser-create-react-app/src/hooks/use-ipfs-factory.js
use-ipfs-factory useEffect was been execute in a loop because in did had the dependencies set to empty
closes #2978
> fix: fix react example

- README.md
- packages/ipfs/README.md
I've been effectively not contributing as Tech Lead for a several months now, so not worth having my name there and mislead folks.
I see this is a natural transition, specially after all the great work from @alanshaw and @achingbrain as the [Lead Maintainers](https://github.com/ipfs/team-mgmt/blob/master/LEAD_MAINTAINER_PROTOCOL.md). You've made the project so much better, thank you for taking really great care of it, as you can imagine, it means a lot to me ❤️
> docs: remove Tech Lead section

- examples/browser-webpack/package.json
It's needed for webpack now apparently. Without it, the user will get a message like this on first `npm run build`:
```txt
$ npm run build                                                                      
> example-browser-webpack@ build /path/to/browser-webpack                 
> webpack                                                                           
One CLI for webpack must be installed. These are recommended choices, delivered as s
eparate packages:                                                                   
- webpack-cli (https://github.com/webpack/webpack-cli)                             
The original webpack full-featured CLI.                                          
We will use "npm" to install the CLI via "npm install -D".                          
Do you …
```
> add webpack-cli as dev dependency

- packages/interface-ipfs-core/src/dag/get.js
- packages/ipfs-http-client/src/dag/get.js
Passing `options` without a `path` to dag.get will throw an error.
```
ipfs.dag.get(cidPath, { timeout: 2000 })
TypeError: Cannot read property 'timeout' of null
```
Cause by the lovely JS issue of `typeof null === 'object'`.
Co-authored-by: Kia Rahimian <kia@tintmail.com>
> fix: typeof bug when passing timeout to dag.get

- examples/browser-add-readable-stream/index.html
- examples/browser-add-readable-stream/package.json
- examples/browser-browserify/package.json
- examples/browser-create-react-app/package.json
- examples/browser-mfs/package.json
- examples/browser-parceljs/package.json
- examples/browser-readablestream/package.json
- examples/browser-script-tag/index.html
- examples/browser-script-tag/package.json
- examples/browser-video-streaming/index.html
- examples/browser-video-streaming/package.json
- examples/browser-vue/package.json
- examples/browser-webpack/package.json
- examples/circuit-relaying/package.json
- examples/custom-ipfs-repo/package.json
- examples/custom-libp2p/package.json
- examples/exchange-files-in-browser/package.json
- examples/explore-ethereum-blockchain/package.json
- examples/ipfs-101/package.json
- examples/run-in-electron/package.json
- examples/running-multiple-nodes/package.json
- examples/test-ipfs-example/utils.js
- examples/traverse-ipld-graphs/package.json
- packages/interface-ipfs-core/src/dht/find-peer.js
- packages/ipfs-http-client/README.md
- packages/ipfs/README.md
Updates example syntax to new api, also removes references to `dist/index.js` in favour of `dist/index.min.js`.
fixes #3027
> fix: fixes browser script tag example

- docs/core-api/FILES.md
Previously, before globSource, all options were passed in to ipfs.addFromFs together as one options object. With globSource, `recursive` and `hidden` are now separated out from the options that are traditionally passed into IPFS and are now passed in specifically to globSource.
This PR updates the example for adding files with ipfs.add and globSource to reflect that there should be two separate options objects when using globSource to add from the fileSystem and also wanting to pass in additional options to IPFS.
> Updated globSource example with options

- packages/ipfs/src/cli/bin.js
We publish release candidates under the `next` tag and releases under the `current` tag - if we're running an rc, the update notifier can prompt the user to upgrade, even though they are actually running more recent code.
The change here is to only run the update notifier if the string `'-rc'` is not present in the version number..
> chore: only prompt user to upgrade if not running an rc

- examples/test-ipfs-example/package.json
CI is running a later version of chrome so a new chromedriver is needed.
> chore: update chromedriver

- README.md
- packages/ipfs-http-client/README.md
- packages/ipfs/README.md
The legacy IPFS Docs site has been deprecated, so links to `docs-beta.ipfs.io` will auto-redirect to `docs.ipfs.io`. This PR doesn't change much from the user's perspective, but it makes things a bit tidier.
> docs: updates docs link to non-beta site

- packages/ipfs/src/core/components/config.js
Tactical fix to get the release out while we solve this properly in https://github.com/ipfs/js-ipfs/pull/3067
> fix: handle optional key to config.get

- packages/interface-ipfs-core/src/refs.js
Proposing here a change which will make the `refs.js` tests dag node iteration order independent by sorting the expected and actual refs list. In the soon-to-be polished rust-ipfs refs implementation the refs are iterated breadth-first. Looking at the js-ipfs implementation I am not 100% sure but looks like the implementation is recursive depth-first (I could be wrong).
The iteration orders differ on almost half of the tests, but only big difference is with the test modified on the second commit: recursive+unique test with formatting `<linkname>` where a document has two names and breadth-first and depth-first offer the different names as a result.
The proposed changes are similar to what is already done for the dag-cbor nodes (sorted).
> test: make refs tests iteration order independent

- examples/circuit-relaying/README.md
- examples/circuit-relaying/index.html
- examples/circuit-relaying/package.json
- examples/circuit-relaying/src/app.js
- examples/circuit-relaying/src/helpers.js
- examples/circuit-relaying/test.js
- packages/ipfs/test/core/libp2p.spec.js
Since the `v0.28.1` patch release, libp2p requires a connection encryption module to be passed in config, otherwise it throws.
See: https://github.com/libp2p/js-libp2p/pull/665
> fix: libp2p now requires encryption module

- docs/core-api/CONFIG.md
- packages/interface-ipfs-core/src/config/get.js
- packages/interface-ipfs-core/src/config/profiles/apply.js
- packages/interface-ipfs-core/src/config/replace.js
- packages/ipfs-http-client/src/config/getAll.js
- packages/ipfs-http-client/src/config/index.js
- packages/ipfs/src/cli/commands/config/show.js
- packages/ipfs/src/core/components/bootstrap/add.js
- packages/ipfs/src/core/components/bootstrap/rm.js
- packages/ipfs/src/core/components/config.js
- packages/ipfs/src/core/components/init.js
- packages/ipfs/src/core/components/start.js
- packages/ipfs/src/http/api/resources/config.js
- packages/ipfs/src/http/index.js
- packages/ipfs/test/cli/config.js
- packages/ipfs/test/core/create-node.spec.js
- packages/ipfs/test/core/init.spec.js
- packages/ipfs/test/http-api/inject/config.js
This PR adds `ipfs.config.getAll(options?: Object)` and makes `key` in `ipfs.config.get(key: string, options?: object)` required.
> feat: add config.getAll

- .travis.yml
Version numbers taken from https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
> chore: support current and active LTS node

- docs/core-api/BLOCK.md
Discovered some inconsistency between docs and an implementation of `ipfs.block` API
> fix: examples to match current implementation

- packages/ipfs/src/core/components/start.js
- packages/ipfs/test/core/create-node.spec.js
On `js-ipfs@0.41`, we removed the `websocket-star` module from the libp2p default configuration for browser nodes in `js-ipfs`. We removed it because this module was not refactored during https://github.com/ipfs/js-ipfs/issues/1670, since the libp2p goal is to [sunset the star protocols](https://github.com/libp2p/js-libp2p/issues/385) and we preferred to use the time refactoring `websocket-star` into improving the browser support.
In the refactor, the `webrtc-star` module was refactored so that browser users could discover other peers in the network. In addition, `circuit-relay` may be used for establishing connections between browser nodes using `websockets`.
However, this migration has not been smooth for `js-ipfs` users. Users previously using `websocket-star` swarm addresses, did not …
> chore: throw error no swarm on multiaddrs using websocket-star

- packages/ipfs-http-client/package.json
- packages/ipfs-http-client/src/dag/get.js
- packages/ipfs/package.json
Resolve now throws if the path is not '/'.
> chore: upgrade ipld-raw

- packages/ipfs-http-client/test/dag.spec.js
- packages/ipfs/src/core/runtime/ipld-nodejs.js
- packages/ipfs/test/core/ipld.spec.js
If we specify a `formats` array as part of the ipld options in in-proc nodes, it replaces the default list of dag-pb, dag-cbor and raw.
This change allows the `loadFormat` function to still resolve those formats even if the user has passed a `format` array that does not contain them.
Fixes #3129
> fix: still load dag-pb, dag-cbor and raw when specifying custom formats

- examples/exchange-files-in-browser/README.md
- examples/exchange-files-in-browser/public/app.js
- examples/exchange-files-in-browser/test.js
Per #2779 , this PR adds the public webrtc servers to the browser example.
This allows users to run easily the example, but also provides information for how users should use a signaling server for production.
> chore: update example with public webrtc servers

- docs/core-api/MISCELLANEOUS.md
- packages/interface-ipfs-core/src/miscellaneous/version.js
- packages/ipfs-http-client/test/interface.spec.js
- packages/ipfs/src/cli/commands/version.js
- packages/ipfs/src/core/components/version.js
- packages/ipfs/src/http/api/resources/version.js
Adds `interface-ipfs-core` and `ipfs-http-client` versions to the output of the `ipfs version` command, also the git commit id if it's available.
Closes #2878
> feat: add interface and http client versions to version output

- docs/core-api/BLOCK.md
@achingbrain was unsure if its ok to commit such tiny change to `master`, so opened a PR, but let me know if you prefer silent fixes of things like that in the future.
> docs(core-api): fix default value column

- packages/ipfs/src/cli/commands/repo/stat.js
- packages/ipfs/src/cli/commands/stats/repo.js
- packages/ipfs/test/cli/repo.js
Makes `stats repo` an alias for `repo stat` to make formatting the same across commmands in line with go-ipfs.
Also adds `-s` flag to both commands to print just the size info.
> feat: add size-only flag to cli repo stat command

- packages/ipfs/src/core/ipns/publisher.js
When this method is async (without any actual async work) the 'should fail to publish if does not receive private key' test experiences an UnhandledPromiseRejection in electron, though the test still passes.
> fix: unhandledpromiserejection in electron tests

- packages/ipfs/src/core/runtime/preload-browser.js
- packages/ipfs/src/core/runtime/preload-nodejs.js
As we don't accept get requests via the http api any more
> fix: use post for preloading

- packages/ipfs/src/cli/commands/files/chmod.js
- packages/ipfs/src/core/utils.js
- packages/ipfs/src/http/api/resources/files-regular.js
- packages/ipfs/src/http/api/resources/files/chmod.js
- packages/ipfs/test/cli/files/chmod.js
- packages/ipfs/test/http-api/inject/files.js
- packages/ipfs/test/http-api/inject/mfs/chmod.js
`ipfs ls QMfoo` was listing raw nodes as directories when present in a DAG.
Also does not try to parse chmod strings as octals to allow `+x` etc on the command line the same as the programmatic API
> fix: do not list raw nodes in a dag as directories

- packages/ipfs/src/core/components/config.js
- packages/ipfs/src/core/runtime/config-browser.js
- packages/ipfs/src/core/runtime/config-nodejs.js
To help find content and peers on the network, turn on delegate nodes by default.
Disables delegate nodes while using the `test` config profile.
> feat: turn on delegate nodes by default

- docs/RELEASE_ISSUE_TEMPLATE.md
- docs/core-api/DAG.md
- docs/core-api/FILES.md
- docs/core-api/OBJECT.md
- packages/ipfs-core-utils/README.md
- packages/ipfs-http-client/README.md
- packages/ipfs/docs/CLI.md
- packages/ipfs/docs/DAEMON.md
- packages/ipfs/docs/DEVELOPMENT.md
VSCode seems to insert this weird whitespace character that isn't a space but looks like a space and then messes up all the formatting in markdown files.
> docs: fix weird whitespace character

- packages/ipfs-http-client/.aegir.js
- packages/ipfs-http-client/package.json
- packages/ipfs-http-client/test/utils/factory.js
- packages/ipfs/.aegir.js
- packages/ipfs/package.json
> chore: swap go-ipfs-dep for go-ipfs

- packages/ipfs/docs/FAQ.md
They were out of date and cause confusing errors to be thrown.
> fix(docs): update webrtc instructions for node in faq

- packages/ipfs/src/core/runtime/libp2p-browser.js
- packages/ipfs/src/core/runtime/libp2p-nodejs.js
- packages/ipfs/test/core/libp2p.spec.js
This PR removes the websocketStar discovery configuration, since it is not used anymore.
In addition, I have changed the discovery keys to use the modules tag from the module. This has created some confusion to libp2p users, and we would like people to use the tag instead of magic keys that might also be changed in the future: https://github.com/libp2p/js-libp2p/issues/664#issuecomment-642249349
> chore: update libp2p runtime config

- examples/traverse-ipld-graphs/package.json
- packages/interface-ipfs-core/package.json
- packages/interface-ipfs-core/src/object/links.js
- packages/ipfs-http-client/package.json
- packages/ipfs/package.json
This is an attempt to asses if changes from https://github.com/ipld/js-ipld-dag-pb/pull/184 can be integrated into js-ipfs without breaking things, which in turn would address some problems I've run into https://github.com/ipfs/js-ipfs/issues/3022#issuecomment-638008545
> chore: update dag-pb dep

- packages/ipfs/src/cli/commands/key.js
- packages/ipfs/src/cli/commands/pin.js
Without specifying that we require a sub-sub command, these commands
exit with a non-zero code and no output when you just run the subcommand
E.g:
```console
$ jsipfs key
$ echo $?
0
```
Now becomes
```console
$ jsipfs key
....help text appears here
$ echo $?
1
```
> fix: require command for key and pin subcommands

- examples/browser-sharing-node-across-tabs/package.json
- examples/browser-sharing-node-across-tabs/src/main.js
- examples/browser-sharing-node-across-tabs/webpack.config.js
Shared worker example stopped working, and we have not noticed because for some reason CI doesn't seem to run it. There were several problems:
1. I'm guessing ipfs was bumped to 0.48 while things were in the review. And demo was getting older version with older `ipfs.add` API.
2. When I incorporated `add` / `addAll`, I have regressed the example https://github.com/ipfs/js-ipfs/pull/3081/commits/2302b2fcbac64b351d19d201259578ac008d7a39#diff-48144c5d1809a34109f2559846446f22R21.  Have not noticed that, because CI doesn't seem to run it.
3. When I first wrote a example I used `CopyWebpackPlugin` which then I thought was unnecessary and removed. However `index.html` was placed in `dist` from prior runs so after change tests were still passing (and CI never seemed to have run this example). …
> fix: shared node demo

- examples/browser-sharing-node-across-tabs/package.json
The name needs to be correct otherwise the tests don't run as part of CI.
> fix: correct typo in module name

- packages/ipfs-http-client/src/name/resolve.js
`stream: true` was being set after the options were decapsulated. This makes it impossible to override streaming in the http api.
> fix(http-client): allow stream option to be overridden

- packages/ipfs/src/core/runtime/libp2p-browser.js
- packages/ipfs/src/core/runtime/libp2p-nodejs.js
This would be good to land in 0.49 as we're planning to remove support for SECIO in 0.50. 
- When dialing js-ipfs >=0.47, or go-ipfs >=0.5 nodes, there will be no latency hit as we can start Noise immediately.
- Incoming dials for ipfs <0.49 and >0=0.47, will take a round trip hit when connecting as they'll fail to negotiate Secio and fallback to Noise
> feat: prioritize noise over secio

- examples/browser-browserify/README.md
This is an improvement to a previous PR (#3084 ). It is ment to avoid building all the project just to run an example. Following the old instructions, after the cloning is finished, it took me 20 minutes before I can run the example. With this modification, I can run the example just 2 minutes after the cloning is finished.
> docs: ready to test in less time

- docs/README.md
> docs: fix link to ipfs-http-client

- packages/interface-ipfs-core/package.json
- packages/ipfs-core-utils/package.json
- packages/ipfs-http-client/package.json
- packages/ipfs/package.json
- packages/ipfs/src/core/ipns/resolver.js
- packages/ipfs/test/core/name-pubsub.js
- packages/ipfs/test/core/name.spec.js
The IPNS resolver was unnecessarily (and inaccurately) trying to fetch public keys from the network if they weren't embedded in the record. Embedding has been around for some time so we don't need this anymore.
This also fixes a problem where record validation wouldn't happen for inlined public keys. When PeerId's with inlined keys create ipns records, the public key is not embedded because this is duplicative. (this is the behavior of both Go and JS).
This was caught in interop testing of the latest go-ipfs updates to move to ed25519 keys by default. The failing job for this is https://app.circleci.com/pipelines/github/ipfs/go-ipfs/3329/workflows/33457111-bec0-46a9-80ef-f13fc7844231/jobs/38550.
related https://github.com/ipfs/go-ipfs/pull/7579
> fix: validate ipns records with inline public keys

- docs/core-api/MISCELLANEOUS.md
- packages/interface-ipfs-core/src/miscellaneous/id.js
- packages/ipfs-http-client/test/interface.spec.js
- packages/ipfs/src/cli/commands/id.js
- packages/ipfs/src/core/components/id.js
- packages/ipfs/src/http/api/resources/id.js
addresses issue https://github.com/ipfs/js-ipfs/issues/3219
> feat: add protocol list to ipfs id

- packages/interface-ipfs-core/src/add.js
- packages/interface-ipfs-core/src/utils/index.js
- packages/ipfs-http-client/src/add-all.js
When a file is empty the progress event will have a `Bytes` property that is `0` so test if the property is not undefined rather than if it is truthy.
Fixes #3255
> fix: handle progress for empty files

- .travis.yml
- packages/interface-ipfs-core/README.md
Can't run the renderer on linux until go-ipfs accepts requests from the renderer user agent.
> chore: run electron main CI on linux

- packages/ipfs-http-client/package.json
- packages/ipfs/package.json
Downgrades merge-options because v3 removed node 12 support.
Fixes: https://github.com/ipfs/js-ipfs/issues/3270
Refs: https://github.com/schnittstabil/merge-options/issues/23
> chore: downgrade merge-options

- docs/CONFIG.md
- packages/ipfs-http-client/README.md
- packages/ipfs/src/http/api/routes/index.js
- packages/ipfs/src/http/error-handler.js
- packages/ipfs/src/http/index.js
- packages/ipfs/test/http-api/cors.js
- packages/ipfs/test/http-api/index.js
- packages/ipfs/test/utils/http.js
- packages/ipfs/test/utils/test-http-method.js
Brings js-ipfs into line with go-ipfs by not having CORS on by default, instead requiring the user to explicitly configure it.
BREAKING CHANGE:
- CORS origins will need to be [configured manually](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/README.md#cors) before use with ipfs-http-client
> fix: disable cors by default

- packages/ipfs-cli/src/commands/pin/add.js
- packages/ipfs-cli/src/commands/pin/rm.js
- packages/ipfs-cli/test/pin.js
Error `Invalid version, must be a number equal to 1 or 0` triggered when using CLI pin add/rm. 
The return value of `ipfs.pin.addAll` or `ipfs.pin.rmAll` is just [`AsyncIterable` of `CID`s](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/PIN.md#returns-1)
> fix: error invalid version triggered in cli pin add/rm

- examples/browser-ipns-publish/package.json
- examples/http-client-browser-pubsub/package.json
- examples/http-client-name-api/package.json
- examples/http-client-name-api/test.js
- packages/interface-ipfs-core/src/name/publish.js
- packages/ipfs-http-client/package.json
- packages/ipfs/package.json
Tests against the latest go-ipfs release.
> chore: upgrade to go-ipfs 0.7.0

- packages/ipfs-http-server/src/api/routes/webui.js
<del>https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.3</del>
https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.4
<del>Sadly #2580 broke E2E tests: we don't see if changing this hash broke anything until we release  `ipfs-http-server` and bump it in `ipfs` </del>
- we test `ipfs@next` against webui master already ([.travis.yml#L260-L265](https://github.com/ipfs/js-ipfs/blob/8e44e52e9860bc7d0270ae7d0710d9692d82df8b/.travis.yml#L260-L265))
> feat: webui v2.11.4

- .github/workflows/typecheck.yml
This pull request adds a github action to #3281, which runs type check and reports any missmateches in the pull request diff view. Screenshots below are from #3328 which reverted two changes from #3281 back to how they were on master which pass all tests, but fail type checker:
Since this adds a separate action, it allows us to have more relaxed policies in regards to changes that fail checks. Also I hope that messages in the pull request may encourage contributors to resolve reported issues and sometimes (unfortunately not always) they are clear enough to require no TS knowledge at all.
> Typecheck github action

- packages/ipfs-message-port-client/src/core.js
- packages/ipfs-message-port-client/test/interface-message-port-client.js
- packages/ipfs-message-port-server/src/core.js
- packages/ipfs-message-port-server/src/ipfs.ts
This implements `ipfs.ls` for the `ipfs-message-port-*` libraries as per https://github.com/ipfs/js-ipfs/issues/3252
> fix: implement message-port ipfs.ls

- package.json
We need to build types for ipfs-core during the release process.
> chore: build ipfs-core before ipfs during release

- .travis.yml
https://github.com/nodejs/node/issues/35722 has been released so re-enable testing on node 15
> chore: re-enable node 15

- examples/ipfs-101/README.md
> docs: fixes "interface-ipfs-core" link

- packages/ipfs-core/src/index.js
Everything is Uint8Arrays now so there's no need to export node's
Buffer module any more.
Fixes #3312
BREAKING CHANGE: `Buffer` is no longer exported from core
> fix: remove buffer export from ipfs-core

- docs/core-api/FILES.md
This should minimize the number of people who pass `mtime` and `mode` to `ipfs.add` when they don't really need them.
Ref. https://discuss.ipfs.io/t/why-has-same-sub-cids-but-not-same-root-cid/8810/6?u=lidel
> docs: clarify that mtime and mode are optional

- packages/ipfs-http-client/src/lib/core.js
- packages/ipfs-http-client/test/constructor.spec.js
No need to do this twice.
Fixes #3331
> fix: do not double normalise input url

- examples/browser-mfs/filetree.js
- packages/interface-ipfs-core/src/files/ls.js
- packages/ipfs-core/src/components/files/ls.js
- packages/ipfs-core/src/utils.js
- packages/ipfs-http-client/src/files/ls.js
- packages/ipfs-http-server/src/api/resources/files/ls.js
- packages/ipfs-http-server/test/inject/mfs/ls.js
Supersedes #3345 #2939
Fixes #3330 #2948
BREAKING CHANGE: types returned by `ipfs.files.ls` are now strings, in line with the docs but different to previous behaviour
> fix: files ls should return string

- packages/ipfs-cli/package.json
- packages/ipfs-cli/src/parser.js
This was prompted by #3353. I am guessing that something end up pulling old version of `@types/yargs` that was unaware of `onFinishCommand`. This pull explicitly adds latest `@types/yargs` into `ipfs-cli` dev dependencies which:
1. Seems to be aware of `onFinishCommand`.
2. Makes ipfs-cli aware of yargs interface, which without this just appears as `any`.
> chore: add @types/yargs for better inference

- packages/ipfs/src/index.js
For some reason you need to add `/src` after `ipfs-core` otherwise the import in the generated `index.d.ts` has the wrong path.
Must fix properly before the next release.
> fix: types path for ipfs-core

- packages/ipfs-core/test/ipld.spec.js
Since https://github.com/ipld/js-ipld/pull/293 was merged IPLD now validates existing formats correctly so use a non-bundled one in the test otherwise it throws when we try to re-add the `dag-pb` format.
> chore: add non-bundled format in test

- packages/ipfs-core/src/preload.js
- packages/ipfs-core/test/preload.spec.js
We 'preload' most CIDs we interact with on the network. In some cases
this can mean preloading the same CID over and over again which is not
necessary.
This PR adds a LRU cache to the preloader with a default size of 1000.
The cache is used to avoid re-preloading the same CID over and over again
until it drops out of the cache.  We use a cache that will evict CIDs
over time to have some sort of upper bound on memory usage.
Fixes #3307
> fix: cache preloaded CIDs

- packages/ipfs-core/.aegir.js
- packages/ipfs-core/package.json
- packages/ipfs-core/src/runtime/config-browser.js
- packages/ipfs-core/test/config.spec.js
This PR adds the new `dnsaddr` multiaddrs for browser bootstrapping peers per https://github.com/libp2p/js-libp2p/pull/772 and https://github.com/libp2p/js-libp2p/pull/782 
cc @mburns
> chore: use dnsaddr for bootstrap nodes

- packages/ipfs-cli/package.json
Remove electron-webrtc dep - as it was only being used by daemon startup which doesn't typically run under electron.
If your application requires webrtc, see [the FAQ](https://github.com/ipfs/js-ipfs/blob/master/docs/FAQ.md#is-there-webrtc-support-for-js-ipfs-with-nodejs) for more information.
Fixes #3376
> fix: remove electron-webrtc dependency

- packages/interface-ipfs-core/package.json
- packages/ipfs-core/package.json
- packages/ipfs-core/src/components/add-all/index.js
Restores changes to defaults removed from the importer to ensure CID compatibility with go-IPFS.
> chore: upgrade unixfs-importer

- docs/core-api/FILES.md
- packages/interface-ipfs-core/src/add-all.js
- packages/ipfs-core/src/components/add-all/index.js
- packages/ipfs-core/src/components/add.js
Fixes a bug where due to parallel file imports, the reported size of
ingested bytes was getting mixed up.
We now tally imported bytes against the reported file name instead of
assuming a sequential import, taking care to not let the tally grow
until memory is exhausted.
> fix: ensure correct progress is reported

- docs/core-api/FILES.md
- packages/interface-ipfs-core/src/add-all.js
- packages/ipfs-core/src/components/add-all/index.js
- packages/ipfs-core/src/components/add.js
- packages/ipfs-http-server/src/api/resources/files-regular.js
Aligns behaviour between js and go when no path is present during an import
- we now pass an empty string instead of `'unknown'`.
> fix: align behaviour between go and js for content without paths

- packages/ipfs-message-port-client/package.json
- packages/ipfs-message-port-server/package.json
Fix message-port-client/server packages by declaring message-port-protocol as dependency that it is, instead of devDependency.
> fix: make message-port-protocol non dev dependency

- packages/ipfs-cli/src/commands/add.js
- packages/ipfs-cli/test/add.js
If raw-leaves is unset, default to true if cid version is > 0.
This is in line with go-IPFS and is what the importer used to do internally.
> fix: correct raw leaves setting

- examples/browser-browserify/package.json
- examples/browser-create-react-app/package.json
- examples/browser-exchange-files/package.json
- examples/browser-http-client-upload-file/package.json
- examples/browser-mfs/package.json
- examples/browser-parceljs/package.json
- examples/browser-readablestream/package.json
- examples/browser-sharing-node-across-tabs/package.json
- examples/browser-vue/package.json
- examples/browser-webpack/package.json
- examples/circuit-relaying/package.json
- examples/http-client-bundle-webpack/package.json
- examples/http-client-name-api/package.json
- package.json
- packages/interface-ipfs-core/package.json
- packages/ipfs-cli/package.json
- packages/ipfs-core-utils/package.json
- packages/ipfs-core/package.json
- packages/ipfs-http-client/package.json
- packages/ipfs-http-gateway/package.json
- packages/ipfs-http-server/package.json
- packages/ipfs-message-port-client/package.json
- packages/ipfs-message-port-protocol/package.json
- packages/ipfs-message-port-server/package.json
- packages/ipfs/package.json
`rm -rf` isn't a thing on windows - use the cross-platform `rimraf` module instead.
> chore: windows compat

- examples/types-use-ipfs-from-ts/package.json
- examples/types-use-ipfs-from-typed-js/package.json
- packages/ipfs-cli/package.json
- packages/ipfs-core-utils/package.json
- packages/ipfs-core/package.json
- packages/ipfs-http-client/package.json
- packages/ipfs-http-gateway/package.json
- packages/ipfs-http-server/package.json
- packages/ipfs-message-port-client/package.json
- packages/ipfs-message-port-protocol/package.json
- packages/ipfs-message-port-server/package.json
- packages/ipfs/package.json
The TypeScript project [release breaking changes as minor versions](https://github.com/microsoft/TypeScript/issues/41563#issuecomment-730704643) so pin to `4.0.x` until we can do the refactoring needed to upgrade to `4.1.x`.
> chore: pin ts version

- docs/CONFIG.md
- packages/ipfs-core/src/components/libp2p.js
- packages/ipfs-core/src/runtime/config-browser.js
- packages/ipfs-core/src/runtime/config-nodejs.js
- packages/ipfs-core/test/libp2p.spec.js
This PR adds the ability to add announces addresses via the config file and create options.
This is really useful for browser contexts, so that other peers can announce their public addresses, like dns addresses.
Ref: https://github.com/ipfs/js-ipfs/issues/3400
> feat: announce addresses via config

- packages/ipfs-cli/src/commands/get.js
- packages/ipfs-cli/test/get.js
Adds a check to prevent overwriting files not under the output
directory, which you can override with a `--force` option.
> fix: do not write to prefix outside of output directory

- packages/ipfs-core-utils/src/index.js
- packages/ipfs-core-utils/src/with-timeout-option.js
https://github.com/ipfs/js-ipfs/pull/3407/ has introduced regression in type inference for `withTimeoutOptions` function which end up referring to `Fn<Args, R>` type which was declared in other file https://github.com/ipfs/js-ipfs/pull/3407/files#diff-722621abc3ed4edc6ab202fdf684f1607c261394b95da6b3ec79748711056f20
I think TS has this strange WTF where when it can't figure out when JS file is a module it will treat it as if everything is loaded in the same scope. I think that caused `withTimeoutOptions` not to report errors but silently fail and infer return function as `any`.
This change fixes that by removes `Fn` type all together, as it seemed like unnecessary complexity. 
Unfortunately nothing seemed to have caught this regression because we set …
> fix: types for withTimeoutOptions

- packages/ipfs-cli/package.json
- packages/ipfs-cli/src/commands/daemon.js
- packages/ipfs-core/package.json
- packages/ipfs-daemon/.eslintrc
- packages/ipfs-daemon/CODE_OF_CONDUCT.md
- packages/ipfs-daemon/CONTRIBUTING.md
- packages/ipfs-daemon/COPYRIGHT
- packages/ipfs-daemon/LICENSE-APACHE
- packages/ipfs-daemon/LICENSE-MIT
- packages/ipfs-daemon/README.md
- packages/ipfs-daemon/package.json
- packages/ipfs-daemon/src/index.js
- packages/ipfs-daemon/test/index.spec.js
- packages/ipfs-daemon/tsconfig.json
- packages/ipfs-http-gateway/package.json
- packages/ipfs-http-server/package.json
- tsconfig.json
The daemon is a way of exposing IPFS functionality that's used by the
CLI, in the same way that IPFS itself is used by the CLI so split it
out into it's own module for better separation of concerns.
> chore: split daemon out into module

- docs/core-api/FILES.md
- packages/interface-ipfs-core/src/get.js
Also adds a test for deeply nested directories
> docs: document type field in ipfs.get output

- .github/workflows/bundlesize.yml
- packages/ipfs-message-port-client/README.md
- packages/ipfs-message-port-client/src/client/transport.js
- packages/ipfs-message-port-protocol/src/core.js
- packages/ipfs-message-port-server/package.json
- packages/ipfs-message-port-server/src/server.js
- packages/ipfs-message-port-server/test/transfer.spec.js
Fixes #3402
The `transfer` list, ie. the second argument to `postMessage`, should always contain unique values, multiple of the same pointers cause errors. This PR fixes that, see linked issue above for more info. My solution was to just make everything in the list unique by converting the array to a set and back. Let me know if this works, or if another solution is preferred.
> fix: make port transferables unique

- packages/interface-ipfs-core/src/ls.js
- packages/ipfs-core/src/components/ls.js
- packages/ipfs-http-client/src/ls.js
- packages/ipfs-http-server/src/api/resources/files-regular.js
- packages/ipfs-http-server/test/inject/files.js
- packages/ipfs/test/interface-http-go.js
This fixes a typo where `ipfs.ls()` returns instead of yielding from a generator.
The result is that ipfs.ls() does not work when the path is a file. I think this should fix it, with `ls` returning a generator with a single file result.
(Note: I wanted to add a test but could not find where this command is being tested).
> Fix ipfs.ls() for a single file object

- examples/types-use-ipfs-from-ts/package.json
- examples/types-use-ipfs-from-ts/src/main.ts
- examples/types-use-ipfs-from-typed-js/package.json
- examples/types-use-ipfs-from-typed-js/src/main.js
- packages/ipfs-core/src/index.js
- packages/ipfs/src/index.js
This is an attempt to illustrate a different approach for exporting IPFS type than one proposed in #3439.
Here instead of using `default export` for type `IPFS` type is just exported with it's name so that user in ts can write `import { IPFS, create } from "ipfs"` and equivalent in js as well.
Pull also updates two examples we have in place to both illustrate & test this.
> fix: export IPFS type

- docs/BROWSERS.md
It's been long time deprecated, no need for it to be on the list.
> docs(browsers):  remove websocket-star

- .travis.yml
- packages/ipfs-daemon/package.json
- packages/ipfs-daemon/src/index.js
- packages/ipfs-daemon/test/index.spec.js
- packages/ipfs-http-client/README.md
- packages/ipfs-http-client/package.json
- packages/ipfs-http-client/src/lib/core.js
- packages/ipfs-http-client/test/node.js
- packages/ipfs-http-client/test/node/agent.js
Right now no `http.Agent` is used for requests made using the http client in node, which means each request opens a new connection which can end up hitting process resource limits which means connections get dropped.
The change here sets a default `http.Agent` with a `keepAlive: true` and `maxSockets` of 6 which is consistent with [browsers](https://tools.ietf.org/html/rfc2616#section-8.1.4) and [native apps](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1407597-httpmaximumconnectionsperhost?language=objc).
The user can override the agent passed to the `ipfs-http-client` constructor to restore the previous functionality:
```js
const http = require('http')
const createClient = require('ipfs-http-client')
const client = createClient({
url: …
```
> feat: allow passing a http.Agent to ipfs-http-client in node

- packages/ipfs-http-client/README.md
Documents the existing constructor arguments as I don't think they're written down anywhere right now.
> docs: document the ipfs http client constructor arguments

- .travis.yml
Node 15.6.x was released with the fix for https://github.com/hapijs/hapi/issues/4208 so re-enable testing in CI.
> chore: re-enable testing on node 15

- packages/ipfs-grpc-client/src/grpc/transport.node.js
- packages/ipfs-grpc-client/src/index.js
- packages/ipfs-grpc-client/src/utils/bidi-to-duplex.js
- packages/ipfs-grpc-client/src/utils/client-stream-to-promise.js
- packages/ipfs-grpc-client/src/utils/server-stream-to-iterator.js
- packages/ipfs-grpc-client/src/utils/unary-to-promise.js
- packages/ipfs-http-client/package.json
- packages/ipfs-http-client/src/lib/core.js
Fixes regression introduced in #3474 - if we make https requests, use a https agent.
> fix: use https agent for https requests

- packages/ipfs-client/package.json
- packages/ipfs-client/src/index.js
- packages/ipfs-client/tsconfig.json
- packages/ipfs-core-types/src/index.ts
- packages/ipfs-grpc-client/package.json
- packages/ipfs-grpc-client/src/index.js
- tsconfig.json
Fixes #3494
It appears that `react-scripts` swaps `isolateModules` which [causes problems in webui](https://github.com/ipfs-shipyard/ipfs-webui/pull/1655#issuecomment-763846124) because according to TS:
> Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.  TS1205
Changes here address that problem as follows:
- `export type {...}` is used as per TS error.
- `isolateModules` flag is set to `true` so that such issues can be caught locally.
- Setting flags seems to have triggered problems in `ipfs-client`, so I had to add some type annotations to fix that.
- Added `references` in `ipfs-client/tsconfig.json`, otherwise it does not pick up changes in the dependencies unless they are manually rebuild.
> fix: issue with isolateModules flag

- package.json
- scripts/update-example-deps.js
Due to not wanting to publish versions of examples on GH or npm we
don't include the examples in our lerna workspace during publishing.
Consequently the `package.json` of examples doesn't get updated with
new `ipfs` etc modules during the publish process, which means they
depend on old versions and can break, so we need to update the versions
manually which is tiresome and error prone.
I've added a script to do it at the end of the publish process.
> chore: automate updating example dependencies

- lerna.json
Lerna doesn't work with npm automation tokens out of the box, need
to disable auth verification for the time being.
Refs: https://github.com/lerna/lerna/issues/2788
> chore: fix rc publishing

- docs/BROWSERS.md
- docs/FAQ.md
This PR 
- fixes a broken link in docs
- replaces deprecated webrtc-star used for demo purposes with two redundant ones
> docs: fix webrtc-star link

- docs/core-api/OBJECT.md
AFAIK it is `Data` and `Links`, not `data`
> docs: ipfs.object.get typo fix

- packages/interface-ipfs-core/src/swarm/peers.js
- packages/ipfs-core/package.json
- packages/ipfs-daemon/package.json
- packages/ipfs/package.json
Error in CI: https://travis-ci.com/github/ipfs/js-ipfs/jobs/500525900
In the past webrtc did not proper support multiple listeners. This basically mean that if trying to listen on multiple addresses the webrtc sdp offers could end up with wrong signal server address throwing random errors in CI.
https://github.com/libp2p/js-libp2p-webrtc-star/pull/330 fixed this and now a libp2p node allows multiple listeners. When a peer with multiple webrtc-star listeners attempts to dial another peer via a star signalling server, the signal server of the target peers is identified among the listeners and used for starting the dial.
In the test changed in this PR (note that ports might change):
```
nodeA: ['/ip4/127.0.0.1/tcp/53466/ws/p2p-webrtcstar/p2p/QmPqSo3Kqf9XtWG6g3WKVrx2PZ2q3BoFZssVjixaweABNW'] …
```
> fix: interface core test swarm peers with webrtc does not dial the correct address

- packages/ipfs-grpc-server/src/utils/web-socket-server.js
The data type was wrong so use the version from the `ws` module
> fix: update data type for ws message event handler

- packages/ipfs-core/src/ipns/republisher.js
- packages/ipfs-core/test/name.spec.js
IPNS Republish was republishing self private key twice, first as part of the root IPNS Record published when creating the IPFS Repo and then as part of keychain keys.
This was specially problematic when doing a flow such as:
```sh
node packages/ipfs/src/cli.js init
DEBUG=ipfs:i* node packages/ipfs/src/cli.js daemon --pass 12345678901234567890
```
As we provided a keychain password for the daemon, this password was going to be used for creating the keychain dek. However, self was created as part of the PeerId in the init command (without password).
> fix: do not republish self key twice

- Dockerfile.latest
- Dockerfile.next
The python package has gone, we need to use python3 instead.
There's a futher problem with npm not setting the $PATH properly so
it fails as it can't find pbjs, but this is only necessary with gh
dep versions which should go away with the next libp2p-kad-dht/libp2p-gossipsub
releases.
> chore: fix docker images

- packages/ipfs-grpc-client/src/utils/load-services.js
- packages/ipfs-grpc-server/src/utils/load-services.js
The json generated by protobufjs is now not compatible with the types on protobufjs's `fromJSON` method.
> fix: ignore the ts error caused by the recent protobufjs type change

- examples/custom-ipfs-repo/package.json
- packages/ipfs-cli/package.json
- packages/ipfs-core-types/src/config/index.d.ts
- packages/ipfs-core/package.json
- packages/ipfs-core/src/components/libp2p.js
- packages/ipfs-core/src/components/network.js
- packages/ipfs-core/src/runtime/config-browser.js
- packages/ipfs-core/src/runtime/config-nodejs.js
- packages/ipfs-core/src/types.d.ts
Some of the types need a little correcting.
Fixes #3640
> fix: update types after feedback from ceramic

- packages/ipfs-http-server/package.json
- packages/ipfs-http-server/src/api/resources/dag.js
- packages/ipfs-http-server/src/index.js
- packages/ipfs-http-server/src/types.d.ts
- packages/ipfs-http-server/test/inject/dag.js
We needed to reach into ipld in order to get at the formats so we can deserialize the data.
Instead, put the data as a block and then read it out using ipfs.dag.get.
Slightly inefficient but better to use the public API.
Fixes #3639
> fix: only use public api in http api server

- packages/ipfs-http-client/src/types.d.ts
> fix: add missing type import

- examples/browser-ipns-publish/package.json
- examples/custom-ipfs-repo/package.json
- packages/interface-ipfs-core/package.json
- packages/ipfs-cli/package.json
- packages/ipfs-core-types/src/config/index.d.ts
- packages/ipfs-core-utils/package.json
- packages/ipfs-core/package.json
- packages/ipfs-core/src/components/cat.js
- packages/ipfs-core/src/components/get.js
- packages/ipfs-core/src/components/ipld.js
- packages/ipfs-core/src/components/ls.js
- packages/ipfs-core/src/preload.js
- packages/ipfs-core/src/runtime/ipld.js
- packages/ipfs-core/src/types.d.ts
- packages/ipfs-daemon/package.json
- packages/ipfs-http-client/package.json
- packages/ipfs-http-client/src/lib/core.js
- packages/ipfs/package.json
Otherwise the user has to specify a blockstore etc.
We make the options object whole before instantiating ipld.
> fix: mark ipld options as partial

- .travis.yml
sidetree removed the direct dependency on js-ipfs in https://github.com/decentralized-identity/sidetree/commit/be481c002c8643d65e7203097338ddc94eca6cd6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
License: MIT
> chore: remove sidetree test

- examples/custom-ipfs-repo/package.json
- examples/running-multiple-nodes/README.md
- examples/running-multiple-nodes/test.js
- packages/ipfs-cli/package.json
- packages/ipfs-core-types/src/config/index.d.ts
- packages/ipfs-core/package.json
> fix: update ipfs repo

- packages/ipfs-core-types/src/bitswap/index.d.ts
- packages/ipfs-core-types/src/dht/index.d.ts
- packages/ipfs-core-types/src/root.d.ts
- packages/ipfs-core-types/src/stats/index.d.ts
- packages/ipfs-core-types/src/swarm/index.d.ts
- packages/ipfs-http-client/src/dht/find-peer.js
Accept peer ids as strings or multiaddrs as Multiaddrs.
Also removes accepting peerIDs as CIDs for consistency as I don't think we actually return peerIDs as CIDs from the api anywhere (from `ipfs.swarm.peers`, for example), only ever as strings.
Fixes #3638
> fix: loosen input type for swarm.connect and swarm.disconnect

- packages/ipfs-http-server/src/index.js
- packages/ipfs-http-server/test/cors.js
If CORS origin list is empty, Hapi throws an error as it considers
that to be invalid configuration.
We want to reject requests that send and origin or a referer when
no allowed origins have been configured, so when these headers are
sent, reject the request if no allowed origins are present in the
config.
> fix: reject requests when cors origin list is empty

- examples/traverse-ipld-graphs/eth.js
- examples/traverse-ipld-graphs/get-path.js
- examples/traverse-ipld-graphs/git.js
- packages/interface-ipfs-core/src/dag/get.js
- packages/ipfs-core/src/components/dag/get.js
- packages/ipfs/test/interface-http-go.js
If you have a path within the DAG to resolve, pass it as `path` in the options object.
Makes the API conform to the documentation.
Fixes #3637
> fix: only accept cid for ipfs.dag.get

- packages/ipfs-grpc-client/src/utils/load-services.js
- packages/ipfs-grpc-server/src/utils/load-services.js
- packages/ipfs-http-server/src/index.js
- packages/ipfs-http-server/test/cors.js
If CORS origin list is empty, Hapi throws an error as it considers
that to be invalid configuration.
We want to reject requests that send and origin or a referer when
no allowed origins have been configured, so when these headers are
sent, reject the request if no allowed origins are present in the
config.
Co-authored-by: Vasco Santos <vasco.santos@moxy.studio>
Co-authored-by: Marcin Rataj <lidel@lidel.org>
> fix: reject requests when cors origin list is empty (#3674)

- packages/ipfs-core-types/src/root.d.ts
- packages/ipfs-core-types/src/utils.d.ts
- packages/ipfs-core-utils/src/files/normalise-input/index.browser.js
- packages/ipfs-core-utils/src/files/normalise-input/index.js
- packages/ipfs-core-utils/src/files/normalise-input/normalise-input.js
- packages/ipfs-core-utils/src/files/normalise-input/utils.js
- packages/ipfs-grpc-client/src/core-api/add-all.js
- packages/ipfs-http-client/src/lib/multipart-request.browser.js
- packages/ipfs-http-client/src/lib/multipart-request.node.js
- packages/ipfs-http-server/src/api/resources/files-regular.js
- packages/ipfs-message-port-client/src/core.js
- packages/ipfs-message-port-server/src/core.js
Use `ImportCandidate` and `ImportCandidateStream` instead of `ToEntry` and `ImportSource` as they are a bit more descriptive. Plus we already have `BrowserImportCandidate` for `Blob`s so it's more consistent too.
> chore: rename import types

- packages/ipfs-http-client/test/node/agent.js
Because the requests are initiated with `Promise.all`, there's no
guarantee which order they arrive at the server in so when we check
the responses, just make sure the length and contents are correct
instead of the order.
> chore: fix flaky test

- .github/workflows/bundlesize.yml
Sometimes it's because there's a duplicate dep version that needs to
be fixed.
Usually it's because some transitive dep increases it's bundle size
by a kilobyte or two and has nothing to do with the current PR, so all
we do is increase the `bundlesizeMax` value to make it pass.
Let's just make the check informational instead.
> chore: allow bundlesize gh action to fail

- packages/ipfs-core/src/components/add-all/index.js
Optional chaining is supported in node and in browsers but tools that
transpile code to run in older browsers doesn't understand the syntax.
Specifically the version of acorn that at least vue uses via a dependency
on webpack 4 does not support this.
It'll be fixed by them upgrading to webpack 5 but the timescale on that
is unclear, which is why we're using a prerelease version in our examples.
The short term fix is to just remove optional chaining from where we
are using it in code that will be transpiled for browser use.
> fix: remove optional chaining from code that will be transpiled

- .github/workflows/bundlesize.yml
- .travis.yml
- Dockerfile.latest
- Dockerfile.next
- packages/ipfs-daemon/package.json
npm7 has started installing peer deps by default, which means if you
are running a future tech node.js version you may end up compiling
native addons that may fail.  These addons should be opt-in so move
them to optional deps which means if they fail to install, the whole
installation does not fail.
Also adds `@mapbox/node-pre-gyp` as a dependency so we can attempt to 
compile modules that have native addons where no prebuilt binary is
available instead of requiring users to install it globally which is
required due to a misconfiguration in the `webrtc` module.
> fix: move wrtc to optional deps

- packages/ipfs-core-types/src/pubsub/index.d.ts
- packages/ipfs-http-client/package.json
- packages/ipfs-http-client/test/commands.spec.js
- packages/ipfs-http-client/test/node/agent.js
- packages/ipfs-http-client/test/pubsub.spec.js
- packages/ipfs-http-client/test/utils/factory.js
- packages/ipfs-http-client/tsconfig.json
This was missed in #3468.  Also runs the type checker on the pubsub http client tests to ensure typing is correct.
> fix: add onError to pubsub.subscribe types

- packages/ipfs-core/.aegir.js
- packages/ipfs-core/package.json
- packages/ipfs/.aegir.js
With https://github.com/NodeFactoryIo/js-libp2p-noise/pull/100 in, we can now have a smaller bundle size. Also fixes node build
`libp2p-noise`: ~27% decrease on its bundle size, from 191.5kb to 141.2kb (minified+gzipped)
`ipfs`: ~10% decrease on its bundle size.
Closes https://github.com/ipfs/js-ipfs/issues/3704
> chore: update libp2p noise

- examples/browser-ipns-publish/package.json
- packages/interface-ipfs-core/package.json
- packages/ipfs-core/package.json
- packages/ipfs-core/src/ipns/publisher.js
Upgrades `ipns` to support v2 sigs. Should be a backwards-compatible change.
Depends on:
> feat: support v2 ipns signatures

- docs/MODULE.md
A link didn't work, because it was assuming the wrong local directory.
> Fixed relative link to CONFIG.md

- packages/ipfs-core-types/package.json
I linked from the npm package listing and was suprised to end up at the interface-ipfs-core package.
> chore: fix pkg.homepage for ipfs-core-types

- packages/ipfs-core-utils/package.json
- packages/ipfs-core-utils/src/files/normalise-input/utils.js
- packages/ipfs-core-utils/test/files/normalise-input.spec.js
Related to https://github.com/web3-storage/ipfs-car/issues/62
> fix: support @web-std/file in normalize input

- packages/interface-ipfs-core/src/pubsub/unsubscribe.js
In the http client, when we subscribe to a topic we open a HTTP connection which we keep open for the duration of the subscription.
When we unsubscribe we abort the connection but it can remain open for a little while after the abort, even if we try to wait on the `fetch` command ending before continuting, which leads to the topic still being present in the subs list, so retry asserting that the subs list is empty in the tests within a certain time window.
Fixes this sort of error:
```
ipfs:   1) interface-ipfs-core over ipfs-http-client tests against go-ipfs
ipfs:        .pubsub.unsubscribe
ipfs:          should subscribe 5 handlers and unsubscribe once with no reference to the handlers:
ipfs:       AssertionError: expected [ Array(1) ] to deeply equal []
ipfs:       + expected - actual …
```
> fix: fix flaky pubsub test

- packages/interface-ipfs-core/src/dag/get.js
- packages/ipfs-message-port-client/test/util/worker.js
If we run a node in offline mode only, it'll never go to the network to fetch a CID it doesn't have, so we can't really test timeouts properly.
> fix: flaky timeout test

- packages/ipfs-core-types/src/index.d.ts
- packages/ipfs-http-client/src/index.js
- packages/ipfs-http-client/src/types.d.ts
Bubbles the `OptionExtension` up to the root type for use by the HTTP client and exports an interface for use by consuming modules.
Supersedes #3749 and #3736
> fix: export ipfs http client type and use option extension for client

- examples/traverse-ipld-graphs/README.md
- examples/traverse-ipld-graphs/eth.js
- examples/traverse-ipld-graphs/git.js
- examples/traverse-ipld-graphs/package.json
- examples/traverse-ipld-graphs/test.js
These were removed during the multiformats upgrade but they are quite useful as a demo of how to configure extra multiformat blockcodecs/hashers
> chore: restore git and eth graph traversal examples

- .travis.yml
No need to run example tests if we've just changed docs etc.
> chore: only run example tests if code has changed

- examples/traverse-ipld-graphs/eth.js
- examples/traverse-ipld-graphs/package.json
Use the `@multiformats/sha3` module instead of rolling our own
> chore: use multiformats sha3 impl

- docs/IPLD.md
Improve docs around how to configure custom block codecs/multibase codecs, etc.
> docs: update ipld/multiformats docs

- packages/ipfs-core/package.json
- packages/ipfs-core/src/runtime/repo-browser.js
Restores level-js options from https://github.com/ipfs/js-ipfs-repo/blob/b82938fcef0f949517fbd6f63700c2c0178ef117/src/default-options-browser.js
The ones that are valid anyway.
> fix: restore default level-js options

- packages/ipfs-core-types/src/bitswap/index.d.ts
- packages/ipfs-core-types/src/block/index.d.ts
- packages/ipfs-core-types/src/dht/index.d.ts
- packages/ipfs-core-types/src/name/index.d.ts
- packages/ipfs-core-types/src/object/index.d.ts
- packages/ipfs-core-types/src/object/patch/index.d.ts
- packages/ipfs-core-types/src/pin/index.d.ts
- packages/ipfs-core-types/src/pin/remote/index.d.ts
- packages/ipfs-core-types/src/repo/index.d.ts
- packages/ipfs-core-types/src/utils.d.ts
- packages/ipfs-core/src/components/dht.js
- packages/ipfs-http-server/src/api/resources/object.js
Fixes: https://github.com/ipfs/js-ipfs/issues/3776
It'd be nice to have some kind of tests that caught this, but that might mean adding typescript examples that use this which is probably a fair bit of work. @achingbrain thoughts?
> fix: typo in 'multiformats' type defs

- packages/ipfs-core-types/src/index.d.ts
Generic types were missed off the refs api and added to multihashers.
> fix: typescript errors

- packages/ipfs-core-types/src/files/index.d.ts
The argumuent type for multiple files was wrong.
Closes #3794
> docs: update files.rm example

- packages/ipfs-core/package.json
- packages/ipfs-http-client/package.json
- packages/ipfs/package.json
Reverts ipfs/js-ipfs#3765 - for some reason Travis CI didn't run on that PR and the build is failing.
> chore: revert "chore(deps-dev): bump go-ipfs from 0.8.0 to 0.9.1"

- docs/core-api/STATS.md
- packages/interface-ipfs-core/src/stats/utils.js
- packages/ipfs-core-types/src/stats/index.d.ts
- packages/ipfs-core/src/components/stats/bw.js
- packages/ipfs-http-client/src/stats/bw.js
- packages/ipfs-http-server/src/api/resources/stats.js
The return type for `rateIn`/`rateOut` should be a number and not an integer.
go-IPFS returns a `float64` which isn't representable in js, but we are not interested in that level of accuracy for this value so just return it as a regular `number` which can be a `float`.
Fixes #3782
BREAKING CHANGE: rateIn/rateOut are returned as numbers
> fix: return rate in/out as number

- examples/browser-exchange-files/test.js
- examples/circuit-relaying/test.js
Relax test to just look for `/ws/p2p/` string
> fix: detect ed25519 keys in ws test

- docs/CONFIG.md
> docs: add rpc addr docs

- packages/interface-ipfs-core/package.json
- packages/interface-ipfs-core/src/pubsub/peers.js
- packages/interface-ipfs-core/src/pubsub/subscribe.js
- packages/ipfs-grpc-client/package.json
- packages/ipfs-grpc-client/src/core-api/pubsub/subscribe.js
- packages/ipfs-grpc-client/src/core-api/pubsub/subscriptions.js
- packages/ipfs-grpc-client/src/core-api/pubsub/unsubscribe.js
- packages/ipfs-grpc-client/src/index.js
- packages/ipfs-grpc-protocol/src/pubsub.proto
- packages/ipfs-grpc-server/package.json
- packages/ipfs-grpc-server/src/endpoints/pubsub/subscribe.js
- packages/ipfs-grpc-server/src/endpoints/pubsub/subscriptions.js
- packages/ipfs-grpc-server/src/endpoints/pubsub/unsubscribe.js
- packages/ipfs-grpc-server/src/index.js
- packages/ipfs/test/interface-client.js
- packages/ipfs/test/interface-core.js
- packages/ipfs/test/interface-http-go.js
- packages/ipfs/test/interface-http-js.js
Browsers can only have six concurrently open connections to a host name.
Pubsub works over HTTP by holding a connection open per subscription, which means you can only subscribe six times before things start to hang.
gRPC runs over websockets so doesn't have this limitation.  This PR adds pubsub support to the gRPC server and `ipfs-client` module so you can subscribe to lots and lots of channels concurrently, working around the browser connection limitation.
Refs: #3741
> feat: pubsub over gRPC

- packages/interface-ipfs-core/src/add.js
- packages/interface-ipfs-core/src/pubsub/publish.js
- packages/ipfs-core-utils/src/files/normalise-input/normalise-input.js
Throws an error with a more descriptive error message.
The error messages over http are not descriptive due to https://github.com/node-fetch/node-fetch/issues/753
Fixes #3788
> fix: throw error on missing input to add/addAll

- packages/ipfs-core/src/components/files/utils/update-mfs-root.js
- packages/ipfs-core/src/components/files/utils/with-mfs-root.js
- packages/ipfs-core/src/runtime/repo-nodejs.js
- keys is a fs datastore
- mfs uses the root datastore though it should really use the datastore datastore
- will need a repo migration to fix this
> fix: use correct datastores

- docs/core-api/FILES.md
There seems to be a typo in [FILES.md](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md) file
On line 207,
`const result = await ipfs.add(content)`
This should be `const result = await ipfs.add(file)`
This PR fixes #3740
> Fixed a typo in FILES.md file

- .github/workflows/test.yml
- packages/ipfs-core-types/package.json
- packages/ipfs-core/package.json
- packages/ipfs-core/src/ipns/publisher.js
Using `instanceOf` is not reliable since instances of classes can cross the CLS/ESM boundary and/or come from different browser bundles.
Instead see if we can treat what we've been handed as a `Key` by using the `Key.asKey` method.
Fixes #3852
> fix: use Key.asKey instead of instanceOf

- docs/CONFIG.md
A typo exists in the [CONFIG.md](https://github.com/ipfs/js-ipfs/blob/master/docs/CONFIG.md#webrtcstar) file.
line 207:  `WebRTCStar is a discovery mechanism prvided by a signalling-star`
should be: `WebRTCStar is a discovery mechanism provided by a signalling-star`
> docs: fixed a typo in CONFIG.md file

- docs/core-api/PUBSUB.md
last code wasn't working on line 56. Instead of converting Uint8array to String it was converting the array to string. So instead of text as output , it shows array but with type string. Fixed now with TextDecoder. Working perfectly.
> docs: update PUBSUB.md

- packages/ipfs-core/package.json
- packages/ipfs-core/src/components/block/rm.js
It's got some problems when bundling:
```
resolve 'process/browser' in '/Users/alex/Documents/Workspaces/ipfs-examples/js-ipfs-examples/node_modules/streaming-iterables/dist'
Parsed request is a module
using description file: /Users/alex/Documents/Workspaces/ipfs-examples/js-ipfs-examples/node_modules/streaming-iterables/package.json (relative path: ./dist)
Field 'browser' doesn't contain a valid alias configuration
...
```
> chore: remove streaming iterables

- packages/ipfs-core-utils/src/files/normalise-content.js
- packages/ipfs-core-utils/src/files/normalise.js
- packages/ipfs-core-utils/test/files/normalise-input.spec.js
- packages/ipfs-core-utils/test/fixtures/file.txt
- packages/ipfs-grpc-client/src/core-api/files/write.js
Readable streams returned from `fs.createReadStream` have a `.path` property which was throwing off the content normalisation.
Fixes #3882
> fix: handle node readable streams properly

- packages/ipfs-core/package.json
This should be `9.x.x` like everywhere else.
> chore: update ipfs-utils

- .github/workflows/test.yml
- packages/ipfs-http-response/package.json
Re-enables testing all examples except nextjs which needs a new release before the fix to enhanced-resolve will be pulled in.
> chore: re-enable testing examples

- docs/DEVELOPMENT.md
> docs: Update DEVELOPMENT.md

- packages/ipfs-http-client/README.md
- packages/ipfs/README.md
I am from the issue #3928 and I did it and here it is.
> docs: added examples working link

- .github/workflows/test.yml
- packages/interface-ipfs-core/src/files/write.js
- packages/interface-ipfs-core/src/utils/dump-shard.js
- packages/ipfs-core/src/components/files/utils/add-link.js
- packages/ipfs-core/src/components/files/utils/hamt-utils.js
- packages/ipfs-core/src/components/files/write.js
When writing a file into a hamt shard we hash the filename to figure out where in the
shard to place the file.
If the hash means that we end up adding the file into an existing subshard that also
contains another subshard, we should populate the other subshard's children otherwise
they will not be there when we calculate the new CID for the subshard and they will
be lost.
Fixes #3921
> fix: do not lose files when writing files into subshards that contain other subshards

- packages/ipfs-core/package.json
- packages/ipfs-core/src/components/index.js
- packages/ipfs-core/src/components/network.js
- packages/ipfs-core/src/components/start.js
To allow loading esoteric hashing algorithms encountered in CID prefixes found in bitswap messages, pass the configurable hasher loader to bitswap.
> fix: pass hasher loader to bitswap

- docs/BROWSERS.md
Per https://github.com/ipfs/js-ipfs/issues/3939#issuecomment-972606106, fixing the `examples` link to point to https://github.com/ipfs-examples.
> Update BROWSERS.md - fixing a broken link.

- README.md
Fixes #3597.
I assumed that the request is to have a link near the top for the CORS configuration. If the idea is to rework where those docs are placed and also make it easier to find through the docs directory, let me know.
> docs: add CORS to getting started

- packages/interface-ipfs-core/src/block/rm.js
- packages/interface-ipfs-core/src/dag/get.js
- packages/ipfs-core/src/utils.js
- packages/ipfs-http-client/src/lib/resolve.js
If we're traversing thorough and object and the thing at the end of the path is a CID, load that thing and return it as the final value, unless `localResolve` is true, in which case return the CID.
Fixes #3957
> fix: return nested value from dag.get

- packages/ipfs-cli/src/commands/add.js
- packages/ipfs-cli/test/add.spec.js
Fixes bug where importing files directly was broken
> fix: ensure directory is passed

- packages/ipfs-core-config/package.json
- packages/ipfs-core-config/src/libp2p.browser.js
- packages/ipfs-core-config/src/libp2p.js
- packages/ipfs-core/package.json
- packages/ipfs-core/test/libp2p.spec.js
`@chainsafe/libp2p-noise@5.x.x` has shipped so remove the temporary fork we were using.
> chore: remove noise fork

- .github/workflows/test.yml
- packages/ipfs-http-server/src/api/routes/debug.js
- packages/ipfs-http-server/src/index.js
Allow GET requests for prom stats and return correct response type
> chore: fix monitoring

- packages/ipfs-core/src/components/id.js
Instead of using all the various books, just get the peer from the libp2p peer store, trying to fetch the public key from the dht if it's missing.
> fix: use peer store for id

- packages/interface-ipfs-core/package.json
- packages/ipfs-cli/package.json
- packages/ipfs-core/package.json
- packages/ipfs-http-client/package.json
Coerce undefined to null on decode.
> chore: Bump @ipld/dag-cbor to v7

- packages/ipfs-core-config/package.json
- packages/ipfs-core/package.json
- packages/ipfs-daemon/package.json
- packages/ipfs-http-server/src/api/routes/debug.js
Exposes the per-component metrics from https://github.com/libp2p/js-libp2p/pull/1061 in the prometheus end point.
Also allows changing the `debug` logging level dynamically.
> feat: improve collected metrics

- packages/ipfs-core/src/components/dag/export.js
When `traverseWrite` throws (abort signal for example), the writer is never closed and the iterator never ends.
> fix: always close writer so iterator throws on error

- packages/ipfs-http-client/README.md
This PR clarifies that  ipfs-http-client is for rpc api at  `/api/v0/`
Folks often mention it took them a moment to realize   "HTTP Client" is for RPC API at `/api/v0/` and not HTTP Gateway or something else, this PR and https://github.com/ipfs/ipfs-docs/pull/959 should make things "click" bit faster and reduce confusion.
> docs: clarify ipfs-http-client is for rpc

- docs/core-api/BLOCK.md
Docs seem to be out of date:
https://github.com/ipfs/js-ipfs/blob/45d9baa7576a0ac924f3d01d49371bf1a4cf654c/packages/ipfs-core-types/src/block/index.ts#L14
> docs: core-api/block

- packages/ipfs-core-types/src/utils.ts
solves `Type alias 'ToJSON' circularly references itself.`
solves https://github.com/ipfs/js-ipfs/issues/4029
> fix: remove ToJSON type

- .github/workflows/examples.yml
All examples have been updated to use the latest js-ipfs so they should start being testable again.
> chore: re-enable examples

- README.md
- docs/BROWSERS.md
- docs/DELEGATE_ROUTERS.md
Closes #4002
Closes #3994
Closes #3991
> chore: fix broken links and help text

- .github/workflows/examples.yml
- packages/interface-ipfs-core/src/add-all.js
- packages/interface-ipfs-core/src/add.js
- packages/ipfs-core/src/components/add-all/index.js
- packages/ipfs-core/src/components/index.js
- packages/ipfs-core/src/components/root.js
Looks like this got missed during the multiformats migration.
Fixes #3952
> fix: override hashing algorithm when importing files

- packages/interface-ipfs-core/package.json
- packages/ipfs-core-types/package.json
When using `copyfiles` globstars need to be quoted on a Mac otherwise they don't work
See the README at https://www.npmjs.com/package/copyfiles
Fixes #3976
> fix: missing files on publish

- packages/ipfs-core-types/package.json
> fix: add deps used in ipfs-core-types

- docs/core-api/OBJECT.md
- packages/ipfs-core/src/components/object/patch/rm-link.js
Resolves #3815 
The test provided for `rmlink` has the object structured as: 
https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/object/patch/rm-link.js#L49-L55
```js
const childAsDAGLink = {
Name: 'my-link',
Tsize: childBuf.length,
Hash: CID.createV0(await sha256.digest(childBuf))
}
```
While the documentation has it defined as:
```js
const cid = await ipfs.object.patch.rmLink(node, {
name: 'some-link',
size: 10,
cid: CID.parse('QmPTkMuuL6PD8L2SwTwbcs1NPg14U8mRzerB1ZrrBrkSDD')
})
```
Method has been updated to match the variable names in the documentation and the example has been altered to match the example in the test case.
> fix(rmlink): fix rmlink to match docs

- packages/interface-ipfs-core/package.json
- packages/ipfs-core/package.json
4.x adds basic CARv2 read support, so you could `ipfs dag import` a CARv2 with this; also with https://explore.ipld.io/ getting CAR support, this would allow importing and inspection of a CARv2 there.
The breakage was in the return type definition of `CarReader#header()` which I don't believe is touched in js-ipfs, which only cares about `getRoots()` in the header which remains the same.
> fix: update car dependency for CARv2 read support

- packages/interface-ipfs-core/package.json
- packages/ipfs-cli/package.json
- packages/ipfs-core-config/package.json
- packages/ipfs-core-utils/package.json
- packages/ipfs-core/package.json
- packages/ipfs-daemon/package.json
- packages/ipfs-http-client/package.json
- packages/ipfs/package.json
Motivation:
* fix https://github.com/ipfs/js-ipfs/issues/4080
* I'm not sure what the best way is to fully release this in a way that ipfs-core@latest on npm works (which needs to bundle in ipfs-utils @ 9.0.6 not 9.0.2). Happy to try another strategy if you point me in a better direction
> fix: upgrade dep of ipfs-utils ^9.0.2->^9.0.6

- docs/MODULE.md
- docs/core-api/BITSWAP.md
- docs/core-api/BLOCK.md
- docs/core-api/DAG.md
- docs/core-api/DHT.md
- docs/core-api/FILES.md
- docs/core-api/KEY.md
- docs/core-api/MISCELLANEOUS.md
- docs/core-api/NAME.md
- docs/core-api/PIN.md
- docs/core-api/REFS.md
- docs/core-api/REPO.md
- docs/core-api/STATS.md
- docs/core-api/SWARM.md
- docs/upgrading/v0.62-v0.63.md
- lerna.json
Adds upgrade guide and updates core-api docs with API changes
> docs: add upgrade guide for ESM release

- packages/ipfs-http-client/src/index.js
With the addition of an export-map the `src/types.ts` file is no longer importable so make sure we can import the various ipfs-http-client type defs from the root.
> fix: export ipfs-http-client types

- docs/core-api/DHT.md
Perhaps this is outdated? findProvs (as mentioned on lines 87-89) is expecting a CID, not a string
> Updates findProvs example

- docs/core-api/BLOCK.md
- packages/ipfs-core-types/src/block/index.ts
Closes #3913.
I have some inline notes and questions.
> docs: update block api documentation

- packages/ipfs/CHANGELOG.md
Fixes #4119
Moved 0.61.0 to proper order
Linked to the upgard guide for v0.63.0
> chore: cleanup changelog

- docs/core-api/README.md
Depends on https://github.com/ipfs/ipfs-docs/pull/1185
Context: https://github.com/ipfs/ipfs/issues/487
> chore: update docs/core-api/README

- packages/ipfs-http-client/README.md
> docs: Update README.md

- packages/interface-ipfs-core/package.json
- packages/ipfs-cli/package.json
- packages/ipfs-core-types/package.json
- packages/ipfs-core-utils/package.json
- packages/ipfs-core/package.json
- packages/ipfs-grpc-client/package.json
- packages/ipfs-grpc-server/package.json
- packages/ipfs-http-client/package.json
- packages/ipfs-http-server/package.json
Shipping fix from https://github.com/multiformats/js-multiaddr/pull/253 is required to fix https://github.com/libp2p/go-libp2p-relay-daemon/issues/18 and unblock @thediscordian to update https://docs.ipfs.tech/how-to/create-simple-chat-app/ tutorial 
Filling this PR to see if it is an easy bump that can be shipped as a patch, or more work needs to happen.
> deps: upgrade @multiformats/multiaddr to 10.4.0

- packages/ipfs-core/package.json
- packages/ipfs-core/src/components/network.js
- packages/ipfs-core/src/components/storage.js
- packages/ipfs-daemon/package.json
The update removes the need to load the keychain manually.
> deps: update libp2p to 0.39.0

- packages/ipfs-http-server/src/api/routes/debug.js
The default prometheus memory stats are clunky and hard to interpret without additional tools like graphana because you get separate measurements for different types of memory usage.
Add a single `nodejs_memory_usage` metric that is the output of `process.memoryUsage()`.
> fix: add node memory stats to prometheus output

- docs/core-api/OBJECT.md
- docs/core-api/README.md
Context: https://github.com/ipfs/go-ipfs/issues/7936
> docs:  Object API deprecation

- packages/ipfs/package.json
The interop suite has been updated with the ESM ipfs and libp2p so the branch no longer exists.
> deps(dev): update interop suite

- .github/workflows/test.yml
This should affect how the release issue is generated, might need some additional lerna config to make sure the github release is created in the same way.
> chore: update changelog types to add docs and deps

- docs/upgrading/v0.62-v0.63.md
- docs/upgrading/v0.63-v0.64.md
- docs/upgrading/v0.64-v0.65.md
Add guides for the last few releases.
> docs: add missing upgrade guides

- docs/CONFIG.md
> docs: fixed a mistake

- packages/interface-ipfs-core/package.json
- packages/interface-ipfs-core/src/files/stat.js
- packages/ipfs-core/package.json
- packages/ipfs-core/src/components/files/utils/to-async-iterator.js
Turn the `Blob`/`File` object into a `ReadableStream` then turn that into an `AsyncIterator<Uint8Array>` the same as the other input types.
Fixes #3601
Fixes #3576
> fix: mfs blob import for files larger than 262144b

- lerna.json
- package.json
Lerna is required for monorepo prereleases
> fix: restore lerna for preleases

- packages/ipfs-core-config/package.json
- packages/ipfs-core/package.json
Updates to latest version with new multiformats dependency
> deps: update @chainsafe/libp2p-gossipsub to 6.0.0

- packages/interface-ipfs-core/package.json
- packages/ipfs-cli/package.json
- packages/ipfs-core-config/package.json
- packages/ipfs-core-utils/package.json
- packages/ipfs-daemon/package.json
- packages/ipfs-http-client/package.json
- packages/ipfs/package.json
Recent node versions ship with a global fetch which requires the duplex option to be set when sending readble streams as the request body so ensure we have the latest ipfs-utils that sets that option.
> deps: update ipfs-utils for node 18 compatibility

- packages/interface-ipfs-core/src/name-pubsub/pubsub.js
- packages/interface-ipfs-core/src/pubsub/publish.js
- packages/ipfs-core-config/src/libp2p-pubsub-routers.browser.js
- packages/ipfs-core-config/src/libp2p-pubsub-routers.js
Use the default gossipsub behaviour of not allowing publishing message to zero peers.
If a user publishes a message they may be suprised to find it's not been recieved by anyone, so instead an error should be thrown when there are no peers that will receive a message.
> fix: disallow publishing pubsub messages to zero peers

- packages/ipfs-http-client/README.md
This clarifies the difference between the two packages.
https://github.com/ipfs/kubo/issues/9125#issuecomment-1381810630
> docs: update-ipfs-http-client

- README.md
- packages/interface-ipfs-core/README.md
- packages/ipfs-cli/README.md
- packages/ipfs-client/README.md
- packages/ipfs-core-config/README.md
- packages/ipfs-core-types/README.md
- packages/ipfs-core-utils/README.md
- packages/ipfs-core/README.md
- packages/ipfs-daemon/README.md
- packages/ipfs-grpc-client/README.md
- packages/ipfs-grpc-protocol/README.md
- packages/ipfs-grpc-server/README.md
- packages/ipfs-http-client/README.md
- packages/ipfs-http-gateway/README.md
- packages/ipfs-http-response/README.md
- packages/ipfs-http-server/README.md
- packages/ipfs-message-port-client/README.md
- packages/ipfs-message-port-protocol/README.md
- packages/ipfs-message-port-server/README.md
- packages/ipfs/README.md
Build file is `test.yml` not `js-test-and-release.yml`
> chore: fix link to ci results

- .github/dependabot.yml
FYI: js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can learn more about this deprecation and the corresponding migration guide [here](https://github.com/ipfs/js-ipfs/issues/4336).
> chore: disable dependabot.yml
