ipfs/js-ipfs

README.md

@diasdavid How does this look?

Cleaned readme, added discussion links

---

README.md

Added new repos of things I've been working on for the Swarm revisit https://github.com/diasdavid/node-ipfs-swarm/issues/8

Add new repos to the ROADMAP thing

---

karma.conf.js
package.json

Add json loader

---

package.json
src/core/index.js
src/core/init.js
src/core/utils.js

Needs https://github.com/ipfs/js-ipfs-repo/pull/59

fix(core): consistent repo.exists checks

---

README.md

Made Standard Readme Compliant

---

.aegir.js
package.json
test/core/both/test-bitswap.js

fix: upgrade aegir and ensure glob is mocked

---

ROADMAP.md

Here is the q4 roadmap stub. Let's go through each of these milestones in the next Monday call and complete them with the tasks that need to be performed.
//cc @jbenet @flyingzumwalt @em-ly

update the q4 roadmap

---

ROADMAP.md

can be merged once https://github.com/ipfs/js-ipfs/pull/607 is merged

docs: update the roadmap

---

test/sharness/t0020-init.sh

This adds 5 go-ipfs tests that pass.

sharness: add t0020-init.sh

---

package.json

Done by updating the peer-info package. Please merge this quickly and make a new release to fix the problem that I have.

Fix the error encounter when running node

---

RELEASE.md

@dignifiedquire @VictorBjelkholm @haadcode @RichardLitt what else should we include in the release check list?

docs: add first release checklist

---

ci/Dockerfile
ci/jenkins
package.json

Integration with Jenkins, basically just runs the node unit tests for now.

Jenkins integration

---

examples/browser-script-tag/index.html

I was trying out the examples and noticed a few typo.

fixed minor typo in the example

---

src/core/index.js

It seems new IPFS() isn't working at the moment, see this PR https://github.com/ipfs/js-ipfs/pull/811/files
cc https://github.com/ipfs/js-ipfs/pull/811

provide a default for options

---

package.json

for https://github.com/ipfs/js-ipfs/issues/844

fixed race condition on floodsub

---

src/cli/commands/daemon.js
test/cli/daemon.js

not masking error message when starting daemon

---

src/core/components/id.js

fix: setImmediate polyfilled in node.id()

---

README.md

Updated the link to the Awesome Endeavour: Relay which was moved from issue to a PR instead

Update link to Relay AE

---

circle.yml

This fix is for Circle-CI builds , Thanks to @mkg20001 solution [here](https://github.com/libp2p/js-libp2p/pull/122/commits/56675b96a7f096593415f7f91cba64f8ed3308b5)

Fix: circle chrome build, Thanks to mkg20001

---

src/core/components/swarm.js
test/cli/files.js

@alanshaw this tests fails for me and I believe it is because https://github.com/ipfs/js-ipfs/pull/1005 is missing.

wip - incomplete feature

---

RELEASE.md

Update the Release template

---

examples/browser-browserify/package.json
examples/browser-browserify/src/index.js
examples/exchange-files-in-browser/package.json
examples/exchange-files-in-browser/public/js/app.js
examples/ipfs-101/1.js
examples/ipfs-101/package.json

fixes https://github.com/ipfs/js-ipfs/issues/1110

Update and fix examples

---

src/http/api/routes/index.js
src/http/api/routes/webui.js

Add WebUI Path

---

RELEASE.md

Adding these to defaults, hope you like it @pgte @haadcode :)

docs: add test suites used in the last release as defaults

---

src/cli/commands/files/add.js
src/cli/commands/files/get.js

Path separator issue on Windows.  This should make #1103 pass.

cli files on Windows

---

src/core/runtime/config-nodejs.json
test/cli/bootstrap.js
test/core/bootstrap.spec.js
test/fixtures/go-ipfs-repo/config

Closes #706
License: MIT
Signed-off-by: Paulo Rodrigues <me@paulogr.com>

feat: Add /ip6 addresses to bootstrap

---

README.md

Should help for questions like #1207

docs: ref ipfsd-ctl

---

package.json
src/core/components/bootstrap.js
test/core/bootstrap.spec.js
test/core/interface/bootstrap.js
test/core/interface/interface.spec.js
test/http-api/interface/bootstrap.js

- Comply with Bootstrap API spec
- Run the tests in `interface-ipfs-core`. See https://github.com/ipfs/interface-ipfs-core/issues/97
- Requires https://github.com/ipfs/interface-ipfs-core/pull/220

Comply with Bootstrap API spec

---

package.json
src/core/components/dag.js
src/core/components/files.js
src/core/components/init-assets.js
src/core/components/object.js
src/core/index.js
src/http/api/resources/file.js

The "ipld-resolver" has been renamed to just "ipld".

fix: use "ipld" instead of "ipld-resolver"

---

README.md

readme - fix port number

---

examples/README.md

adding circuit relay tutorial link

docs: adding circuit relay link to tutorials index

---

package.json

chore: update libp2p-secio version

---

RELEASE.md

Adds a section where we can document any API changes that went into a release.
@mitra42 what do you think?
resolves https://github.com/ipfs/interface-ipfs-core/issues/184

docs: add api changes to release template

---

src/core/components/repo.js

See this comment for background - https://github.com/ipfs/js-ipfsd-ctl/issues/242#issuecomment-393371387

fix: dont fail on uninitialized repo

---

examples/exchange-files-in-browser/package.json

chore: update fe example dep

---

.npmignore

refs https://github.com/ipfs/js-ipfs/issues/1510

fix: npm publishes examples folder

---

README.md
src/cli/commands/init.js
src/core/components/init.js
test/core/init.spec.js

Needed for https://github.com/ipfs/js-ipfsd-ctl/pull/284

feat: Allow pregenerated ids

---

README.md

Many tweaks and fixes to the README.

fix: API docs

---

src/http/api/routes/webui.js

🎉 
This isn't the official 2.0 release, but it _is_ the current master. Updating it here so we can release an RC today and we'll upgrade when the official release is available.

feat: update to Web UI 2.0

---

src/http/api/routes/webui.js

License: MIT
Signed-off-by: Alan Shaw <alan.shaw@protocol.ai>

chore: update WebUI CID

---

src/http/api/routes/webui.js

Allows the Web UI to detect and connect to origin without the user having to configure the API multiaddr.

chore: update webui with fix for connect to origin

---

src/cli/utils.js
src/core/index.js
test/core/init.spec.js

Something went wrong when rebasing https://github.com/ipfs/js-ipfs/pull/1668
and some code was introduced which shouldn't be there. This commit
removes that code again.

fix: remove accidentally committed code

---

examples/ipfs-cli-fun/README.md

Mikeal and I are in the process of figuring out the next steps for js-ipfs documentation. 
For the short-term, I don't think this is the best place to put basic js-ipfs commands due to lack of visibility. In the interim, we can put basic js-ipfs cli commands in the README in order to ensure that new users can get started using the cli API quickly.

Deleted ipfs cli fun folder

---

src/http/api/routes/webui.js

Now with quic support, responsive navbar, and a language selector.
See: https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.2.0
License: MIT

feat: Web UI updated to v2.2.0

---

package.json

update ipfs-repo but still pinned to be safe

chore: update ipfs-repo

---

test/cli/name.js
test/core/name-pubsub.js
test/core/name.js

Taking into account the failures in CI for `js-ipfs`: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/master/78/pipeline/257
Needs:

test: increase tests timeouts

---

RELEASE.md

I believe this would be a valuable add, watcha think?

docs: add https://discuss.ipfs.io/c/announcements to release checklist

---

src/http/api/routes/webui.js

Check [release v2.3.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.0) to see the latest changes.

feat: update Web UI to v2.3.0

---

src/http/api/routes/webui.js

Check [release v2.3.2](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.2) to see latest changes.

feat: update to Web UI v2.3.2

---

src/cli/commands/add.js
test/cli/files.js
test/utils/ipfs-exec.js

Allows `echo "hello" | jsipfs add`
resolves https://github.com/ipfs/js-ipfs/issues/1829

feat: pipe to add

---

README.md

docs: remove --save flag

---

test/core/interface.spec.js

No idea why or how these became commented out.

test: re-enable MFS tests

---

src/cli/commands/daemon.js
src/core/preload.js

feat: add `--enable-preload` to enable/disable preloading for daemons

---

README.md

I thought it'd be helpful to add information on how to run individual tests in the README.md file. 
License: MIT
Signed-off by: Nitin Patel <nitinpatel278@gmail.com>

docs: add info on running individual tests

---

src/http/api/routes/webui.js

Analytics are now **opt-in**. Check the [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.1)!

chore: update to Web UI v2.4.1

---

examples/browser-create-react-app/public/manifest.json
examples/browser-create-react-app/src/App.js
examples/browser-create-react-app/src/App.test.js
examples/browser-create-react-app/src/hooks/use-ipfs-factory.js

License: MIT
Signed-off-by: Nitin Patel <nitinpatel278@gmail.com>

style: fix formatting in examples/create-react-app

---

src/http/api/routes/webui.js

This fixes a bug that prevented the adding of files 😬 - [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.4).

chore: update to Web UI 2.4.4

---

src/core/runtime/libp2p-nodejs.js
test/core/interface.spec.js
test/http-api/interface.js

Due to performance issues the DHT is disabled for the upcoming release, you can turn it on optionally but your mileage may vary.

refactor: disable DHT

---

README.md

Add back the message warning users about the (lack of) DHT.

docs: revert dht message

---

maintainer.json

In preparation for https://github.com/ipfs/team-mgmt/pull/822

docs: create maintainer.json

---

src/http/api/routes/webui.js

[Release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.5).

chore: update to Web UI 2.4.5

---

package.json

Adds message signing to pubsub.

chore: update libp2p version

---

package.json

fixes https://github.com/ipfs/js-ipfs/issues/2090

chore: update ipld-dag-pb dep

---

.travis.yml

See https://github.com/ipfs/aegir/issues/345

core: remove commitlint from check stage in CI

---

src/core/components/object.js

fix: double callback in object.links for cbor data

---

package.json
src/cli/bin.js

- Added an error message asking the user to update their NodeJS to the minimum required version.
- Exits process with failure code 1.
resolves #2126 
License: MIT
Signed-off-by: Chirag Shinde <shinde.chirag2204@gmail.com>

feat (cli): show error message if minimum node version isn't met

---

package.json

closes: #1705
License: MIT
Signed-off-by: Prabhakar Poudel <yuvrajzohan@gmail.com>

chore: add lint before push

---

package.json
src/core/components/name.js
src/core/components/stats.js

Upgraded `human-to-milliseconds` dependency, since it got a new sync version that allows us to remove the callback logic.

chore: upgrade human-to-milliseconds

---

README.md

Copy paste implies you might use both if you don't read. :grin: Use one of the two.

use one cdn for easy copy&paste 

---

src/cli/commands/name/resolve.js

Value was updated but doc string was not.

docs: change recursive IPNS resolve default value

---

.aegir.js
.travis.yml
README.md

until we fix our deps again `npx aegir build` cmd runs out of memory

chore: add bundle size checks and badge

---

src/cli/commands/add.js

update a couple of minor help doc for add CLI command
License: MIT
Signed-off-by: Prabhakar-Poudel yuvrajzohan@gmail.com

refactor(add command, CLI): update a couple of minor help doc

---

.travis.yml

CI seems to be running tests on 3 windows envs instead of the expected 2.

chore: fix 3 windows environments

---

package.json
src/core/components/name-pubsub.js
src/core/components/name.js
src/core/ipns/index.js
src/core/ipns/publisher.js
src/core/ipns/republisher.js
src/core/ipns/resolver.js
src/core/ipns/routing/offline-datastore.js
src/core/ipns/routing/pubsub-datastore.js
src/core/runtime/dns-nodejs.js
test/core/name.spec.js

`err-code` no longer takes a string as the first argument.
This PR also removes a bunch of useless DEBUG logs that were logging just the error message and adds logging where a caught error is not directly passed back to callbacks. This should help with debuggability.

chore: update err-code dependency

---

src/http/api/routes/webui.js

Release notes of [v2.5.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.0).
Depends on:

chore: update to Web UI v2.5.0

---

.travis.yml

Perms have been revoked again by someone. Lets keep this train moving.

chore: temporarily disable bundle size check

---

package.json

Fix the build in master - apologies
Should have been done in tandom with https://github.com/ipfs/js-ipfs/pull/2409 and https://github.com/ipfs/js-ipfs/pull/2298

revert: update of ipfs-http-client

---

src/http/api/routes/webui.js

See https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.1.

feat: web ui 2.5.1

---

doc/EARLY_TESTERS.md

docs: add npm-on-ipfs to the early testers doc

---

package.json
src/cli/commands/daemon.js
src/cli/commands/file/ls.js
src/cli/commands/init.js
src/cli/commands/version.js
src/core/components/pin/gc.js
src/core/components/pin/pin-manager.js
src/core/config.js
src/core/ipns/publisher.js
src/core/ipns/republisher.js
src/core/ipns/resolver.js
test/cli/file.js
test/cli/files.js
test/cli/gc.js
test/cli/name.js
test/cli/swarm.js
test/core/bitswap.spec.js
test/core/circuit-relay.js
test/core/pin-set.js
test/core/pin.js
test/core/utils.js
test/gateway/index.js
test/http-api/files.js
test/http-api/inject/bootstrap.js
test/http-api/inject/dht.js
test/http-api/inject/name.js
test/http-api/inject/pin.js
test/http-api/inject/ping.js
test/http-api/inject/pubsub.js

chore: update http client

---

examples/browser-add-readable-stream/index.js
examples/browser-browserify/src/index.js
examples/browser-create-react-app/package.json
examples/browser-create-react-app/src/hooks/use-ipfs-factory.js
examples/browser-parceljs/public/index.js
examples/browser-script-tag/index.html
examples/browser-webpack/src/components/app.js
examples/exchange-files-in-browser/public/app.js
examples/explore-ethereum-blockchain/README.md
examples/ipfs-101/README.md

docs: update examples

---

doc/EARLY_TESTERS.md

This PR simply adds the two projects to EARLY_TESTERS.md. Thanks for doing this!

Adding OrbitDB and ipfs-log to EARLY_TESTERS.md

---

src/http/api/routes/webui.js

See https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.6.0.

feat: web ui 2.6.0

---

src/http/api/routes/webui.js

[Release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.1).

feat: web ui 2.7.1

---

src/cli/commands/repo/stat.js

Added alias for `ipfs repo stat`.

---

package.json

chore(package): update libp2p-delegated-content-routing to version 0.4.1

---

src/http/api/routes/webui.js

https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.2

feat: web ui 2.7.2

---

README.md

chore: remove rogue j

---

package.json

fix(package): update semver to version 7.1.2

---

examples/browser-browserify/README.md

Just tried to explain better how to run the example.

docs: improve browserify example readme

---

package.json

chore(package): update aegir to version 21.0.2

---

package.json

Fixes https://github.com/ipfs/js-ipfs/issues/2782

chore(package): move off of deprecated @hapi/ammo

---

docs/core-api/README.md

Hi, 
Nothing extraordinary just a bracket that was messing around. 
Have good day/evening.

docs: fixed link typo

---

packages/interface-ipfs-core/src/repo/gc.js
packages/ipfs-http-client/src/repo/gc.js

Yield the contents of the iterator, not the iterator itself.
Whoops.
Also corrects a small typo in the tests.
Fixes #2999

fix: fix gc tests

---

packages/interface-ipfs-core/src/get.js

Continuing the same theme, though this might be coming to an end as next up we should start implementing the `/add` :)

test: replace ipfs.add with unixfs importer in get.js

---

docs/core-api/FILES.md

I think this was a copy paste error from remove section?

docs: correct files.write arg description

---

packages/ipfs-core-utils/src/files/normalise-input.js

fix: set error code correctly

---

docs/core-api/FILES.md

docs: update files.mv arguments

---

docs/core-api/FILES.md

Stream types had mistakenly got into the single-item-add section

docs: update add definition

---

docs/core-api/FILES.md

docs: small typo fix

---

.travis.yml

chore: revert "chore: run electron main CI on linux"

---

Dockerfile.latest
Dockerfile.next

Run on node 12 instead of node 10

chore: upgrade base node docker image

---

.travis.yml

feat: node 14 support

---

docs/core-api/OBJECT.md

docs: add commas to object patch commands

---

docs/MODULE.md

chore: broken links in docs

---

examples/browser-service-worker/package.json
examples/ipfs-client-add-files/package.json
packages/ipfs-core/.aegir.js
packages/ipfs/.aegir.js

The ipfs version bump was missed. Really need to automate this.

chore: fix examples

---

package.json
scripts/update-example-deps.js

Do the work all in the js script, not half in js and half in the npm script.

fix: run the update example deps script in master and not in ci

---

docs/MODULE.md

docs: update MODULE.md

---

packages/ipfs-http-server/package.json

Pulls in latest version to drop Buffer dependency.

chore: update it-to-buffer dep

---

packages/interface-ipfs-core/package.json
packages/ipfs-cli/package.json
packages/ipfs-client/.aegir.js
packages/ipfs-core-types/package.json
packages/ipfs-core/.aegir.js
packages/ipfs-core/package.json
packages/ipfs-http-client/.aegir.js
packages/ipfs-http-client/package.json
packages/ipfs/.aegir.js

Pulls in the latest borc for the latest buffer

chore: update ipld-dag-cbor

---

packages/ipfs-core/package.json
packages/ipfs-daemon/package.json

Let's make sure everything is working as expected
Needs:

chore: update libp2p 0.31.2

---

examples/browser-exchange-files/public/app.js

Not sure how the build for #3785 passed without this, but it did?

fix: fix up examples

---

packages/ipfs/package.json

chore: update interop tests

---

docs/core-api/BLOCK.md

docs: block.put fix

---

.github/workflows/test.yml
packages/interface-ipfs-core/package.json
packages/ipfs-cli/package.json
packages/ipfs-client/package.json
packages/ipfs-core-config/package.json
packages/ipfs-core-types/package.json
packages/ipfs-core-utils/package.json
packages/ipfs-core/package.json
packages/ipfs-daemon/package.json
packages/ipfs-grpc-client/package.json
packages/ipfs-grpc-protocol/package.json
packages/ipfs-grpc-server/package.json
packages/ipfs-http-client/package.json
packages/ipfs-http-gateway/package.json
packages/ipfs-http-server/package.json
packages/ipfs-message-port-client/package.json
packages/ipfs-message-port-protocol/package.json
packages/ipfs-message-port-server/package.json
packages/ipfs/package.json

The output variable is `releases_created` not `release_created`.
Obviously.

chore: fix release

---

.github/workflows/examples.yml
.github/workflows/externals.yml
.github/workflows/test.yml
packages/interface-ipfs-core/CHANGELOG.md
packages/ipfs-cli/CHANGELOG.md
packages/ipfs-client/CHANGELOG.md
packages/ipfs-core-config/CHANGELOG.md
packages/ipfs-core-types/CHANGELOG.md
packages/ipfs-core-utils/CHANGELOG.md
packages/ipfs-core/CHANGELOG.md
packages/ipfs-daemon/CHANGELOG.md
packages/ipfs-grpc-client/CHANGELOG.md
packages/ipfs-grpc-protocol/CHANGELOG.md
packages/ipfs-grpc-server/CHANGELOG.md
packages/ipfs-http-client/CHANGELOG.md
packages/ipfs-http-gateway/CHANGELOG.md
packages/ipfs-http-response/CHANGELOG.md
packages/ipfs-http-response/package.json
packages/ipfs-http-server/CHANGELOG.md
packages/ipfs-message-port-client/CHANGELOG.md
packages/ipfs-message-port-protocol/CHANGELOG.md
packages/ipfs-message-port-server/CHANGELOG.md
packages/ipfs/CHANGELOG.md

Make changelogs consistent.  Hopefully my regex-fu hasn't made a mess of this.
Fixes: #4137

chore: update changelogs

---

docs/core-api/PUBSUB.md
packages/interface-ipfs-core/package.json
packages/interface-ipfs-core/src/pubsub/subscribe.js
packages/ipfs-core/package.json
packages/ipfs-grpc-client/package.json
packages/ipfs-grpc-client/src/core-api/pubsub/subscribe.js
packages/ipfs-http-client/src/pubsub/subscribe.js
packages/ipfs-http-server/package.json

From field should be a peer id

fix: make pubsub message types consistent

---

packages/ipfs-core/README.md

Context: https://github.com/ipfs/ipfs/issues/487

chore: houseclean ipfs-core/README.md

---

packages/ipfs/README.md

Depends on https://github.com/ipfs/ipfs-docs/pull/1193
Context: https://github.com/ipfs/ipfs/issues/487

chore: houseclean ipfs/README

---

packages/ipfs-message-port-client/src/client/service.js

Not sure why this suddenly started to break but here we are.

fix: query input types

---

packages/ipfs/package.json

The branch was merged so no longer exists.

deps(dev): update interop suite version

---

docs/upgrading/v0.62-v0.63.md

Improve docs around upgrading ts projects to use esm.

docs: add ts section to esm upgrade guide

---

packages/interface-ipfs-core/package.json
packages/ipfs-core/package.json
packages/ipfs-http-client/package.json

Updates to version with latest multiformats dep

deps: update dag-jose to 4.0.0
